/* AI 說故事：把三張盤整理成結構化摘要，送到 Cloudflare Worker 中繼站，串流顯示 Claude 的解讀 */
const AI_URL='https://starlit-ai.rickyyenli.workers.dev/';   // 例如 'https://starlit-ai.xxxx.workers.dev'；空字串時隱藏此功能

const AI_TXT={
 zh:{title:'請 AI 說你的故事',intro:'把你的紫微、星盤、人類圖一起交給 AI，寫一篇專屬於你、有生活場景的完整解讀。每次內容都會不同。',focus:'想聽哪個主題',opts:{pair:'我們兩個人',all:'整體人生',career:'事業',wealth:'財運',love:'感情',year:'今年與明年'},go:'開始說故事',busy:'AI 正在寫…',stop:'停止',again:'再寫一次',err:'暫時連不上，請稍後再試。',limit:n=>`今天的次數用完了（每天 ${n} 次），明天再來。`,note:'以下內容由 AI 根據你的盤面生成，僅供參考。',copy:'複製'},
 en:{title:'Ask AI to tell your story',intro:'Hand your Zi Wei, astrology and Human Design charts to AI for a personal reading full of everyday scenes. Each one comes out different.',focus:'Focus',opts:{pair:'The two of us',all:'Whole life',career:'Career',wealth:'Money',love:'Love',year:'This year & next'},go:'Tell my story',busy:'AI is writing…',stop:'Stop',again:'Write another',err:'Can’t connect right now. Please try again later.',limit:n=>`You’ve used today’s ${n} readings. Come back tomorrow.`,note:'Generated by AI from your charts. For reflection only.',copy:'Copy'},
 ja:{title:'AI にあなたの物語を語ってもらう',intro:'紫微斗数・西洋占星術・ヒューマンデザインをまとめて AI に渡し、日常の場面が浮かぶあなただけの解説を書いてもらいます。毎回内容が変わります。',focus:'テーマ',opts:{pair:'二人のこと',all:'人生全体',career:'仕事',wealth:'お金',love:'恋愛',year:'今年と来年'},go:'物語を書いてもらう',busy:'AI が執筆中…',stop:'停止',again:'もう一度',err:'接続できませんでした。時間をおいてお試しください。',limit:n=>`本日の回数（${n} 回）を使い切りました。また明日どうぞ。`,note:'以下は AI があなたのチャートから生成した内容です。参考程度にご覧ください。',copy:'コピー'},
 fr:{title:'Demander à l’IA de raconter votre histoire',intro:'Confiez vos thèmes Zi Wei, astrologique et Human Design à l’IA pour une lecture personnelle pleine de scènes du quotidien. Chaque version est différente.',focus:'Thème',opts:{pair:'Nous deux',all:'Toute la vie',career:'Carrière',wealth:'Argent',love:'Amour',year:'Cette année et la suivante'},go:'Raconter mon histoire',busy:'L’IA écrit…',stop:'Arrêter',again:'Réécrire',err:'Connexion impossible pour le moment. Réessayez plus tard.',limit:n=>`Vous avez utilisé vos ${n} lectures du jour. Revenez demain.`,note:'Texte généré par l’IA à partir de vos thèmes, à titre indicatif.',copy:'Copier'}};

/* ---------- 盤面摘要（給 AI 的事實資料，不含姓名或出生地） ---------- */
function aiChartData(focus){
  if(focus==='pair'&&PB){let zb=null;try{zb=PB.Z.horoscope(new Date());}catch(e){}
    let m='';try{const r=Pair.zh.render({A:{W,Z,HD},B:PB},Engine);m='\n\n# Starlit 合盤指標\n'+Object.entries(r.M).map(([k,v])=>`${k}: ${v.join('；')||'—'}`).join('\n');}catch(e){}
    return '# A（讀者本人）\n'+aiChartFor(W,Z,HD,ZH,true)+'\n\n# B（對方）\n'+aiChartFor(PB.W,PB.Z,PB.HD,zb,false)+m;}
  return aiChartFor(W,Z,HD,ZH,true);
}
function aiChartFor(W,Z,HD,ZH,withCtx){
  const facts=[];try{const ly=Z.rawDates.lunarDate.lunarYear,now=new Date().getFullYear();facts.push(`今年 ${now} 年，虛歲 ${now-ly+1}`);
    if(ZH&&ZH.decadal&&ZH.decadal.index>=0){const dp=Z.palaces[ZH.decadal.index];facts.push(`目前大限：虛歲 ${dp.decadal.range.join('-')}，大限命宮在本命${dp.name}`);}else facts.push('目前仍在童限');
    if(ZH)facts.push(`今年流年命宮在本命${Z.palaces[ZH.yearly.index].name}，流年四化 ${(ZH.yearly.mutagen||[]).map((x,j)=>x+'化'+'祿權科忌'[j]).join(' ')}`);
    try{const ny=Z.horoscope(new Date(Date.UTC(now+1,6,1)));facts.push(`明年 ${now+1} 年流年命宮在本命${Z.palaces[ny.yearly.index].name}，流年四化 ${(ny.yearly.mutagen||[]).map((x,j)=>x+'化'+'祿權科忌'[j]).join(' ')}`);}catch(e){}
    facts.push(`人類圖類型：${I18N.zh.hd.types[HD.type]}（${I18N.en.hd.types[HD.type]}），權威：${I18N.zh.hd.auth[HD.authority]}`);}catch(e){}
  const head=facts.length?'# KEY FACTS (authoritative; do not infer these from other lines)\n'+facts.join('\n')+'\n\n':'';
  return head+aiChartBody(W,Z,HD,ZH,withCtx);
}
function aiChartBody(W,Z,HD,ZH,withCtx){
  const E=I18N.en,o=[];
  const sgn=l=>E.signs[Math.floor(Engine.norm(l)/30)][0];
  const deg=l=>{const x=Engine.norm(l)%30;return `${Math.floor(x)}°${String(Math.floor((x%1)*60)).padStart(2,'0')}′`;};
  if(withCtx&&(CTX.intent||CTX.status||CTX.job)){const W2=WIZ_TXT.zh;o.push('# 使用者情境（請針對這個問題與狀態來寫）');if(CTX.intent)o.push('最想知道：'+W2.intents[CTX.intent]);if(CTX.status)o.push('感情狀態：'+W2.status[CTX.status]);if(CTX.job)o.push('工作狀態：'+W2.job[CTX.job]);o.push('');}
  o.push('# Western astrology (tropical, Placidus'+(W.equal?' → equal houses at high latitude':'')+')');
  PK.forEach(k=>{const q=W.pos[k];o.push(`${k}: ${sgn(q.lon)} ${deg(q.lon)}, house ${q.house}${q.retro?', retrograde':''}`);});
  if(W.pos.Node)o.push(`North Node: ${sgn(W.pos.Node.lon)} ${deg(W.pos.Node.lon)}, house ${W.pos.Node.house}`);
  o.push(`Ascendant: ${sgn(W.asc)} ${deg(W.asc)}; Midheaven: ${sgn(W.mc)} ${deg(W.mc)}`);
  o.push('House cusps: '+W.houses.map((h,i)=>`${i+1} ${sgn(h)}`).join(', '));
  const AN=['conjunction','sextile','square','trine','opposition'];
  o.push('Aspects: '+W.asp.map(a=>`${a.a} ${AN[a.t]} ${a.b} (orb ${a.orb.toFixed(1)}°)`).join('; '));
  o.push('','# 紫微斗數 (iztro, 全書派四化)');
  o.push(`性別 ${Z.gender}；五行局 ${Z.fiveElementsClass}；命主 ${Z.soul}；身主 ${Z.body}；生年 ${Z.rawDates.chineseDate.yearly.join('')}`);
  Z.palaces.forEach(p=>{
    const st=s=>`${s.name}${s.brightness?'['+s.brightness+']':''}${s.mutagen?'化'+s.mutagen:''}`;
    const mi=p.minorStars.filter(s=>MINOR_KEYS.includes(s.name)).map(st);
    const adj=(p.adjectiveStars||[]).map(s=>s.name).filter(n=>['天刑','天姚','紅鸞','天喜','咸池','天哭','天虛','孤辰','寡宿'].includes(n));
    o.push(`${p.name}${p.isBodyPalace?'（身宮）':''} ${p.heavenlyStem}${p.earthlyBranch}｜主星：${p.majorStars.map(st).join(' ')||'無（借對宮）'}｜輔星：${mi.join(' ')||'—'}${adj.length?'｜雜曜：'+adj.join(' '):''}｜大限 ${p.decadal.range.join('-')} 歲`);});
  if(ZH){const nm=i=>Z.palaces[i]?Z.palaces[i].name:'';
    if(ZH.decadal&&ZH.decadal.index>=0)o.push(`目前大限：${ZH.decadal.heavenlyStem}${ZH.decadal.earthlyBranch}，落本命${nm(ZH.decadal.index)}，大限四化 ${(ZH.decadal.mutagen||[]).map((s,j)=>s+'化'+'祿權科忌'[j]).join(' ')}`);
    else o.push('目前仍在童限');
    o.push(`今年（${new Date().getFullYear()}）流年：${ZH.yearly.heavenlyStem}${ZH.yearly.earthlyBranch}，流年命宮落本命${nm(ZH.yearly.index)}，流年四化 ${(ZH.yearly.mutagen||[]).map((s,j)=>s+'化'+'祿權科忌'[j]).join(' ')}`);}
  o.push('','# Human Design');
  const H=HD,X=E.hd;
  o.push(`Type: ${X.types[H.type]}; Strategy: ${X.strategy[H.type]}; Authority: ${X.auth[H.authority]}; Profile: ${H.profile.join('/')}; Definition: ${X.def?X.def[H.definition]||H.definition:H.definition}`);
  o.push('Defined centers: '+(H.defined.map(c=>X.centers[c]).join(', ')||'none'));
  o.push('Open centers: '+Object.keys(X.centers).filter(c=>!H.defined.includes(c)).map(c=>X.centers[c]).join(', '));
  const hds=(window.HDS&&HDS.en)||null;
  o.push('Channels: '+(H.channels.map(([a,b])=>`${a}-${b}${hds&&hds.channels[`${a}-${b}`]?' '+hds.channels[`${a}-${b}`][0]:''}`).join('; ')||'none'));
  try{const cr=Readings.zh.crossName(H,HDZ);o.push(`Incarnation cross: ${X.angles[H.cross.angle]}, ${cr.en||cr.full} (gates ${(H.cross.gates||[]).join('/')})`);}catch(e){}
  o.push('Personality (conscious): '+Engine.HD_BODIES.map(b=>`${b} ${H.P[b].gate}.${H.P[b].line}`).join(', '));
  o.push('Design (unconscious): '+Engine.HD_BODIES.map(b=>`${b} ${H.D[b].gate}.${H.D[b].line}`).join(', '));
  try{const R=Themes.core.build(W,Z,HD,Engine),T=Themes.zh.TAGS;o.push('','# Starlit 三盤合參 tendency tags (systems agreeing)');
    for(const th of ['career','wealth','love','health','people'])o.push(`${th}: `+R[th].ranked.slice(0,4).map(x=>`${T[th][x.tag][0]} (${[...x.sys].join('+')})`).join(', '));}catch(e){}
  try{const n=new Date().getFullYear(),ys=Highlights.zh.years(W,Z,HD,Engine,n-3,n+5);o.push('','# 逐年走向（流年命宮落本命宮位、流年化祿/化忌落宮、木星/土星行運宮位、重大節點；虛歲）');
    ys.forEach(x=>{const lu=x.muts.find(m=>m.k==='祿'),ji=x.muts.find(m=>m.k==='忌');o.push(`${x.y} ${x.stem}（虛歲 ${x.age}）：流年命宮在本命${x.yp}${x.overlap?'（與大限命宮重疊）':''}；${lu?lu.star+'化祿入'+lu.pal:''}；${ji?ji.star+'化忌入'+ji.pal:''}；Jupiter house ${x.jup}；Saturn house ${x.sat}${x.ms.length?'；節點 '+x.ms.map(m=>m.k+(m.pal?':'+m.pal:'')).join(','):''}`);});}catch(e){}
  return o.join('\n');
}

/* ---------- 簡易 Markdown → HTML ---------- */
function aiMd(md){
  const esc=s=>s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');
  const inl=s=>esc(s).replace(/\*\*([^*]+)\*\*/g,'<b>$1</b>').replace(/\*([^*]+)\*/g,'<i>$1</i>');
  const out=[];let list=null;
  for(const raw of md.split('\n')){const l=raw.trim();
    if(/^[-*]\s+/.test(l)){if(!list){list=[];}list.push(`<li>${inl(l.replace(/^[-*]\s+/,''))}</li>`);continue;}
    if(list){out.push(`<ul>${list.join('')}</ul>`);list=null;}
    if(!l)continue;
    const h=l.match(/^#{1,4}\s+(.*)$/);if(h){out.push(`<h4>${inl(h[1])}</h4>`);continue;}
    out.push(`<p>${inl(l)}</p>`);}
  if(list)out.push(`<ul>${list.join('')}</ul>`);
  return out.join('');
}

/* ---------- 介面 ---------- */
let aiCtl=null,aiText='';
function aiRender(){
  const box=document.querySelector('#ai-box');if(!box)return;
  if(!AI_URL){box.hidden=true;return;}
  box.hidden=false;const T=AI_TXT[LG]||AI_TXT.zh;
  box.querySelector('h2').textContent=T.title;box.querySelector('.ai-intro').textContent=T.intro;
  box.querySelector('.ai-flab').textContent=T.focus;
  const sel=box.querySelector('#ai-focus'),cur=sel.value||({love:'love',work:'career',money:'wealth',year:'year'}[CTX.intent])||'all';
  sel.innerHTML=Object.entries(T.opts).filter(([k])=>k!=='pair'||PB).map(([k,v])=>`<option value="${k}">${v}</option>`).join('');sel.value=[...sel.options].some(o=>o.value===cur)?cur:'all';
  const go=box.querySelector('#ai-go');go.textContent=aiCtl?T.stop:(aiText?T.again:T.go);
  box.querySelector('#ai-copy').textContent=T.copy;
}
async function aiRun(){
  const box=document.querySelector('#ai-box'),T=AI_TXT[LG]||AI_TXT.zh,out=box.querySelector('.ai-out'),st=box.querySelector('.ai-status');
  if(aiCtl){aiCtl.abort();return;}
  aiCtl=new AbortController();aiText='';out.innerHTML='';st.textContent=T.busy;box.querySelector('#ai-copy').hidden=true;aiRender();
  try{
    const r=await fetch(AI_URL,{method:'POST',headers:{'Content-Type':'application/json'},signal:aiCtl.signal,
      body:JSON.stringify({lang:LG,focus:box.querySelector('#ai-focus').value,chart:aiChartData(box.querySelector('#ai-focus').value)})});
    if(!r.ok){let j={};try{j=await r.json();}catch(e){}st.textContent=r.status===429?T.limit(j.limit||5):T.err;return;}
    const rd=r.body.getReader(),dec=new TextDecoder();let buf='';
    st.textContent=T.note;
    for(;;){const {value,done}=await rd.read();if(done)break;buf+=dec.decode(value,{stream:true});
      let i;while((i=buf.indexOf('\n'))>=0){const line=buf.slice(0,i).trim();buf=buf.slice(i+1);
        if(!line.startsWith('data:'))continue;let ev;try{ev=JSON.parse(line.slice(5));}catch(e){continue;}
        if(ev.type==='content_block_delta'&&ev.delta&&ev.delta.text){aiText+=ev.delta.text;out.innerHTML=aiMd(aiText);}
        if(ev.type==='error'){st.textContent=T.err;}}}
  }catch(e){if(e.name!=='AbortError')st.textContent=T.err;}
  finally{aiCtl=null;box.querySelector('#ai-copy').hidden=!aiText;aiRender();}
}
function aiInit(){
  const box=document.querySelector('#ai-box');if(!box)return;
  box.querySelector('#ai-go').addEventListener('click',aiRun);
  box.querySelector('#ai-copy').addEventListener('click',()=>{if(navigator.clipboard)navigator.clipboard.writeText(aiText);});
  aiRender();
}

/* ---------- G：一句話＋小問答（便宜的小互動，用 Haiku） ---------- */
const CHAT_TXT={
 zh:{title:'和星星聊兩句',sub:'抽一句今天給你的話，或問一個小問題。每次回答都會根據你的盤。',note:'給我一句話',ask:'問',ph:'例如：今年適合換工作嗎？（120 字以內）',persona:{gentle:'溫柔一點',direct:'直球一點'},busy:'想一下…',foot:'AI 依你的盤回答，僅供參考。'},
 en:{title:'A word from the stars',sub:'Draw a short message for today, or ask one small question. Every answer is based on your charts.',note:'Give me a message',ask:'Ask',ph:'e.g. Is this a good year to change jobs? (max 120 characters)',persona:{gentle:'Gentle',direct:'Straight talk'},busy:'Thinking…',foot:'AI answers from your charts. For reflection only.'},
 ja:{title:'星とひとこと',sub:'今日のあなたへのひとことを引くか、小さな質問をひとつどうぞ。答えはすべてあなたのチャートにもとづきます。',note:'ひとことください',ask:'聞く',ph:'例：今年は転職に向いていますか？（120字以内）',persona:{gentle:'やさしく',direct:'はっきり'},busy:'考え中…',foot:'AI がチャートをもとに答えます。参考程度にどうぞ。'},
 fr:{title:'Un mot des étoiles',sub:'Tirez un petit message pour aujourd’hui, ou posez une petite question. Chaque réponse s’appuie sur vos thèmes.',note:'Un mot pour moi',ask:'Demander',ph:'ex. : Est-ce une bonne année pour changer de travail ? (120 caractères max)',persona:{gentle:'Avec douceur',direct:'Sans détour'},busy:'Je réfléchis…',foot:'Réponse de l’IA d’après vos thèmes, à titre indicatif.'}};
let chatPersona='gentle',chatBusy=false;
function chatRender(){
  const el=document.querySelector('#chat');if(!el)return;if(!AI_URL){el.hidden=true;return;}el.hidden=false;
  const T=CHAT_TXT[LG]||CHAT_TXT.zh,keep=el.querySelector('.chat-log')?el.querySelector('.chat-log').innerHTML:'',q=el.querySelector('#chat-q')?el.querySelector('#chat-q').value:'';
  el.innerHTML=`<div class="chat-h"><h3>${T.title}</h3><div class="seg mini">${Object.entries(T.persona).map(([k,v])=>`<label><input type="radio" name="persona" value="${k}"${chatPersona===k?' checked':''}><span>${v}</span></label>`).join('')}</div></div>
   <p class="muted">${T.sub}</p>
   <div class="chat-row"><button type="button" class="go2btn" id="chat-note">${T.note}</button></div>
   <form class="chat-row" id="chat-f"><input id="chat-q" maxlength="120" placeholder="${T.ph}"><button type="submit" class="go2btn">${T.ask}</button></form>
   <div class="chat-log">${keep}</div><p class="muted chat-foot">${T.foot}</p>`;
  el.querySelector('#chat-q').value=q;
  el.querySelectorAll('input[name=persona]').forEach(r=>r.addEventListener('change',()=>chatPersona=r.value));
  el.querySelector('#chat-note').addEventListener('click',()=>chatSend('note',''));
  el.querySelector('#chat-f').addEventListener('submit',e=>{e.preventDefault();const v=el.querySelector('#chat-q').value.trim();if(v)chatSend('ask',v);});
}
async function chatSend(mode,q){
  if(chatBusy)return;chatBusy=true;const T=CHAT_TXT[LG]||CHAT_TXT.zh,A=AI_TXT[LG]||AI_TXT.zh,log=document.querySelector('#chat .chat-log');
  const esc=s=>s.replace(/&/g,'&amp;').replace(/</g,'&lt;');
  const item=document.createElement('div');item.className='chat-item';
  item.innerHTML=(q?`<p class="chat-q">${esc(q)}</p>`:'')+`<p class="chat-a">${T.busy}</p>`;log.prepend(item);const a=item.querySelector('.chat-a');
  try{const r=await fetch(AI_URL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode,q,persona:chatPersona,lang:LG,chart:aiChartData('all')})});
    if(!r.ok){let j={};try{j=await r.json();}catch(e){}a.textContent=r.status===429?A.limit(j.limit||20):A.err;return;}
    const rd=r.body.getReader(),dec=new TextDecoder();let buf='',txt='';
    for(;;){const {value,done}=await rd.read();if(done)break;buf+=dec.decode(value,{stream:true});let i;
      while((i=buf.indexOf('\n'))>=0){const line=buf.slice(0,i).trim();buf=buf.slice(i+1);if(!line.startsWith('data:'))continue;let ev;try{ev=JSON.parse(line.slice(5));}catch(e){continue;}
        if(ev.type==='content_block_delta'&&ev.delta&&ev.delta.text){txt+=ev.delta.text;a.textContent=txt.replace(/\*\*/g,'');}}}
    if(!txt)a.textContent=A.err;else if(mode==='ask')document.querySelector('#chat-q').value='';
  }catch(e){a.textContent=A.err;}finally{chatBusy=false;}
}
