/* Human Design data (English) */
(function(){
const HDE={
 bodies:{Sun:['Sun','☉'],Earth:['Earth','⊕'],Moon:['Moon','☽'],Node:['North Node','☊'],SNode:['South Node','☋'],Mercury:['Mercury','☿'],Venus:['Venus','♀'],Mars:['Mars','♂'],Jupiter:['Jupiter','♃'],Saturn:['Saturn','♄'],Uranus:['Uranus','♅'],Neptune:['Neptune','♆'],Pluto:['Pluto','♇']},
 centers:{
  head:{n:'Head Center',k:'Inspiration, questions and mental pressure',
   d:'A defined Head Center keeps producing questions and inspiration in a particular direction, and your way of thinking is consistent. You tend to think about things in a set way, and you often stimulate the thinking of the people around you.',
   u:'An open Head Center absorbs other people’s questions and inspiration, so your mind often fills up with questions that aren’t yours. Remember: not every question needs your answer. Asking “do I really want to know this?” saves a great deal of mental energy.'},
  ajna:{n:'Ajna Center',k:'Conceptualizing, analysis and certainty',
   d:'A defined Ajna means you have a fixed way of thinking and analyzing; your views are steady and you have your own logic. Be careful not to let “thinking it through” replace your body’s authority when you make decisions.',
   u:'An open Ajna makes your thinking very flexible, so you can understand many points of view; but you may grab an answer just to look certain. Allowing yourself to say “I’m not sure yet” is your wisdom.'},
  throat:{n:'Throat Center',k:'Expression, action and being seen',
   d:'A defined Throat gives you a consistent way of expressing yourself and a steady voice. Your speech and actions have a set style, and people hear you easily.',
   u:'An open Throat often feels pressure to get attention, so you may interrupt or talk too much. What you say when you are invited or asked usually carries the most power.'},
  g:{n:'G Center',k:'Identity, direction and love',
   d:'A defined G Center gives you a steady sense of who you are and where you are going; your direction comes from within.',
   u:'With an open G Center, your sense of identity shifts with your surroundings, so where you are and who you are with matters a lot. The right place will lead you to the right people and direction.'},
  heart:{n:'Heart (Ego) Center',k:'Willpower, commitment and self-worth',
   d:'A defined Heart Center gives you steady willpower: you do what you say. But it also needs rest, so only promise what you can really deliver.',
   u:'An open Heart Center easily wants to prove itself and agrees to more than it can handle. You don’t need to prove your worth; avoid making promises just to save face.'},
  sacral:{n:'Sacral Center',k:'Life force, work energy and sexual energy',
   d:'A defined Sacral is a sustained life force. You have an inexhaustible supply of work energy, but you only feel more and more satisfied when you are doing what your body responds to.',
   u:'An open Sacral has no consistent energy of its own, so you are easily carried along by other people’s energy and don’t know when to stop. Learning to rest before you are exhausted is your most important lesson.'},
  spleen:{n:'Spleen Center',k:'Intuition, health and safety in the moment',
   d:'A defined Spleen gives you steady intuition and immunity. Your first feeling is usually right, and it speaks only once.',
   u:'An open Spleen is very sensitive to the body and to how others are doing, and out of fear you may cling to unhealthy relationships or habits. Learn to let go of what makes you feel safe but isn’t actually good for you.'},
  sp:{n:'Solar Plexus Center',k:'The emotional wave, feelings and passion',
   d:'A defined Solar Plexus means you have your own emotional wave, and highs and lows are normal. There is no truth in the now: make important decisions only once your emotions have settled.',
   u:'An open Solar Plexus amplifies other people’s emotions, and you may hold back the truth to avoid conflict. Asking “is this my emotion or someone else’s?” will make life much easier.'},
  root:{n:'Root Center',k:'Pressure, drive and the sense of time',
   d:'A defined Root lets you handle pressure in a consistent way. You have a steady drive and aren’t easily rushed by outside pressure.',
   u:'An open Root is easily driven by pressure, wanting to finish things quickly just to be free of it. Remind yourself: not everything is urgent, and slowing down is fine.'}},
 types:{
  generator:{n:'Generator',en:'Generator',strategy:'Wait to respond',sig:'Satisfaction',ns:'Frustration',
   txt:'You have an inexhaustible supply of Sacral energy: you are one of the builders of the world. Your energy is best spent on things your body responds to. When people or things come along, you hear an inner “uh-huh” (yes) or “uhn-uhn” (no). Follow that response and you get more energized the more you do; decide with your head and keep blindly busy, and frustration sets in.',
   tips:['Turn life’s choices into yes-or-no questions: let people ask you, and answer with your body.','Use up your energy before going to bed, and you will sleep much better.','When you feel frustrated, it isn’t because you aren’t trying hard enough; you are doing something you never responded to.']},
  mg:{n:'Manifesting Generator',en:'Manifesting Generator',strategy:'Wait to respond, then inform',sig:'Satisfaction',ns:'Frustration and anger',
   txt:'You have both a Generator’s lasting energy and a Manifestor’s speed: you can handle several things at once and often skip steps. Your strategy is still to wait to respond; after responding, tell the people who will be affected before you act, which reduces resistance. Now and then you will need to go back and fill in the steps you skipped. That isn’t failure; it is simply how you work efficiently.',
   tips:['Allow yourself to multitask and switch tracks; you don’t have to finish one thing before starting the next.','A quick “I’m about to start X” before you act avoids a lot of misunderstanding.','When frustration or impatience shows up, check whether you charged ahead without waiting to respond.']},
  manifestor:{n:'Manifestor',en:'Manifestor',strategy:'Inform',sig:'Peace',ns:'Anger',
   txt:'You are one of the few types who can initiate, with the power to make something out of nothing. Your strategy is to inform: let the people who will be affected know before you act. It isn’t asking for permission; it reduces resistance. Your energy comes in bursts, and you need rest after each one.',
   tips:['Inform before you act, and you will feel far less anger.','You don’t have to force yourself into other people’s rhythm; keep time for yourself.','Rest when your energy runs out, and don’t hold yourself to a Generator’s standard.']},
  projector:{n:'Projector',en:'Projector',strategy:'Wait for the invitation',sig:'Success',ns:'Bitterness',
   txt:'You are a natural guide, good at seeing how people and systems work. You don’t have consistent Sacral energy, so the key is to wait to be recognized and invited, especially for the big things in life (work, love, moving home). When you are properly invited, your advice is valued; uninvited advice tends to bring bitterness.',
   tips:['Put your effort into mastering your craft and being seen, not into pushing yourself.','Keep rest time every day, and don’t compare your workload with a Generator’s.','When you feel bitter, check whether you have been giving advice where you weren’t invited.']},
  reflector:{n:'Reflector',en:'Reflector',strategy:'Wait a lunar cycle (about 28 days)',sig:'Surprise',ns:'Disappointment',
   txt:'All nine of your centers are open. Like a mirror, you reflect the health of your environment and community. You very much need the right environment and the right people. Give yourself a full lunar cycle for major decisions, talk them over a few times with people you trust, and the answer will slowly become clear.',
   tips:['Choose the right environment and half your life falls into place.','Wait at least 28 days before major decisions.','When you feel disappointed, ask whether the environment is wrong for you.']}},
 authorities:{
  emotional:{n:'Emotional Authority',txt:'Your Solar Plexus is defined, so your decisions rise and fall with your emotional wave. There is no truth in the now: don’t say yes to anything important at the very top or bottom of your wave. Give yourself time (often a night to a few days) for the wave to pass and your inner state to calm down; that is when clarity appears.'},
  sacral:{n:'Sacral Authority',txt:'Your answers come from your body’s response in the moment: “uh-huh” is yes, “uhn-uhn” is no. The response is instant and needs no long thought; the reasons your head gives usually come afterward. Having someone you trust ask you yes-or-no questions is the easiest way to hear it.'},
  splenic:{n:'Splenic Authority',txt:'Your intuition speaks once, in the moment, and doesn’t repeat itself. It is quiet and fast. That feeling of “something’s off” or “this is it” is your body protecting you. Don’t wait until you have it all figured out; your very first feeling is the most accurate.'},
  'ego-m':{n:'Ego Authority (manifested)',txt:'Your answers come from what you truly want deep down. Listen to what comes out of your mouth: “I want…”, “I don’t want…”. That is your authority.'},
  'ego-p':{n:'Ego Authority (projected)',txt:'To decide, ask yourself: “What’s in it for me? Do I really want this?” After you are invited, let your willpower confirm whether it is worth committing to.'},
  self:{n:'Self-Projected Authority',txt:'Your answer is in the sound of your own voice. Talk with people you trust, not so they can give you advice, but so you can hear what you say and where your sense of direction comes from.'},
  mental:{n:'Mental Authority (environmental, no inner authority)',txt:'You have no inner bodily authority; clarity comes from your environment and from conversation. Use a few trusted people as sounding boards and talk your ideas through in the right setting; the answer will emerge from the discussion.'},
  lunar:{n:'Lunar Authority',txt:'Your clarity takes time: the Moon takes about 28 days to complete its cycle, passing through all of your gates in turn. For major decisions, feel things out and talk them over during that time before you reach a conclusion.'}},
 definitions:{
  none:['No Definition','All your centers are open, so your energy is completely open to your environment.'],
  single:['Single Definition','All your defined centers are connected, so your energy is self-contained. You don’t really need others to “connect” you; you feel whole on your own and decide relatively quickly.'],
  split:['Split Definition','Your energy is split into two separate areas that usually run on their own. You tend to look for particular people or situations that “bridge” you, and when the right ones come along you get a sudden sense of everything clicking. Give decisions a little more time so both sides can connect.'],
  triple:['Triple Split Definition','Your energy is split into three areas, and you need to move between different people and environments to connect yourself. Busy, varied settings suit you, and decisions need even more time.'],
  quad:['Quadruple Split Definition','Your energy is split into four areas, and you really need time and a wide variety of people. Taking it slowly and not being rushed is the key to your clarity.']},
 lines:{
  1:{n:'Investigator',k:'needs a solid foundation to feel secure',d:'Before you act, you want to research things thoroughly; you only feel at ease once you have enough information. Knowledge is your foundation.',e:'Before buying anything, you read every review and compare the specs, or you just don’t feel right.'},
  2:{n:'Hermit',k:'natural talent that needs time alone',d:'You have gifts you were born with, though you may not notice them yourself. You need undisturbed time, and you are often “called out” to use your talent while you are on your own.',e:'You are happily doing something at home; a friend sees it and says, “You’re really good at this, make me one too.”'},
  3:{n:'Martyr',k:'learns through trial and collision',d:'You have to bump into something yourself before you believe it. Falling down isn’t failure but field data; you are the one who finds all the potholes for everyone else.',e:'You never read the manual for a new appliance; you press buttons until it jams, then suddenly get it. On a trip you walk into a terrible restaurant, yet feel a satisfying “now I know.”'},
  4:{n:'Opportunist',k:'opens doors through a network of people',d:'Your opportunities come from the people you know. You value friendship and stable relationships, and your influence comes from trust.',e:'Your good jobs usually come through friends’ introductions rather than sending out résumés.'},
  5:{n:'Heretic',k:'carries others’ projections and offers practical solutions',d:'People often project their expectations onto you, sure that you will know what to do. Get it right and you are hailed as a savior; get it wrong and you are blamed twice as hard.',e:'When the company has a stuck, messy problem, your boss thinks of you first; when a friend goes through a breakup, you are the one they want to talk to.'},
  6:{n:'Role Model',k:'three stages of life, ending as an example to others',d:'For the first thirty years you experiment like a 3rd line; from thirty to fifty you retreat to the roof to observe; after fifty you become a role model for living authentically.',e:'You change jobs many times when young, become a calm observer in middle age, and end up as the person younger people come to for advice.'}},
 profiles:{
  '1/3':'Investigator / Martyr: you research the foundations thoroughly first, then test them yourself. Holding both knowledge and experience, you are a reliable expert type.',
  '1/4':'Investigator / Opportunist: you influence those around you with solid knowledge, and opportunities come through your network. When your foundation is firm, so is your network.',
  '2/4':'Hermit / Opportunist: you need time alone to cultivate your gifts, then get called out to use them through the people you know.',
  '2/5':'Hermit / Heretic: your talents show naturally, and the public easily projects expectations onto you. Keep time alone so you can deliver when you are called.',
  '3/5':'Martyr / Heretic: your life is about stumbling through collisions (line 3) but finally getting up to solve big problems (line 5). You experience life through lots of interaction and trial with the world: having fallen into a hundred potholes behind the scenes, you can solve the problem in one move on stage.',
  '3/6':'Martyr / Role Model: lots of trial and error in the first half of life, then distilling that experience into wisdom in the second half and becoming a reference for others.',
  '4/6':'Opportunist / Role Model: you influence others through your network, and later in life you become a model within your circle.',
  '4/1':'Opportunist / Investigator: a fixed-fate role with a firm stance. You don’t change direction easily, and you move forward through people and knowledge.',
  '5/1':'Heretic / Investigator: the public expects solutions from you, and your confidence comes from solid research. When you are well prepared, you are the rescuer.',
  '5/2':'Heretic / Hermit: you are projected on as a savior, yet inside you need solitude. Answer the call selectively so you aren’t swamped by expectations.',
  '6/2':'Role Model / Hermit: your natural talent matures through the three stages of life, and you finally become a unique example.',
  '6/3':'Role Model / Martyr: a life full of experiments and adjustments, finally lived as an example of facing failure and growth honestly.'},
 angles:{right:['Right Angle Cross','Personal destiny: your life’s theme centers on your own experiences and growth, and you fulfill your purpose naturally by living out your design.'],jux:['Juxtaposition Cross','Fixed fate: your path through life is steady and singular, like a unique track that you travel in your own way.'],left:['Left Angle Cross','Transpersonal karma: your life’s theme is closely interwoven with others, and you fulfill your purpose through relationships and interaction.']},
 crossNames:{},
 channels:{
  '1-8':['Channel of Inspiration','A Creative Role Model','You show the world new possibilities through your own unique way of expressing yourself.'],
  '2-14':['Channel of the Beat','Keeper of Keys','You hold the resources and drive to set direction, and know where money and effort should go.'],
  '3-60':['Channel of Mutation','Energy Which Fluctuates and Initiates','You brew breakthroughs within limitation, and change often arrives suddenly.'],
  '4-63':['Channel of Logic','Mental Ease Mixed with Doubt','You use doubt and formulas to find patterns, and you are good at finding answers.'],
  '5-15':['Channel of Rhythm','Being in the Flow','You have your own rhythm and habits, and can sync with the rhythms of nature.'],
  '6-59':['Channel of Mating','Focused on Reproduction','You can break through the barriers between people to build intimacy and cooperation.'],
  '7-31':['Channel of the Alpha','Leadership','A natural leader, suited to setting direction once you are recognized.'],
  '9-52':['Channel of Concentration','Determination','You can focus on details for a long time, sitting still and going deep.'],
  '10-20':['Channel of Awakening','Commitment to Higher Principles','You live in the present, are yourself, and lead by example.'],
  '10-34':['Channel of Exploration','Following One’s Convictions','You act in your own way, and your power comes from being true to yourself.'],
  '10-57':['Channel of Perfected Form','Survival','You know intuitively how to live well and beautifully.'],
  '11-56':['Channel of Curiosity','A Searcher','You hold many ideas and stories, and stimulate others by sharing your experiences.'],
  '12-22':['Channel of Openness','A Social Being','When the mood is right, your expression is deeply moving.'],
  '13-33':['Channel of the Prodigal','A Witness','You collect other people’s stories and secrets, and after reflecting, share the wisdom of life.'],
  '16-48':['Channel of the Wavelength','Talent','Through repetition and practice you turn depth into skill.'],
  '17-62':['Channel of Acceptance','An Organizational Being','You are good at turning ideas into clear details and structures.'],
  '18-58':['Channel of Judgment','Insatiability','You see where things could be better and are passionate about correcting and improving them.'],
  '19-49':['Channel of Synthesis','Sensitivity','You are sensitive to needs and principles, and care about fairness and resources in relationships.'],
  '20-34':['Channel of Charisma','Where Thoughts Must Become Deeds','You turn energy straight into action: busy and charismatic.'],
  '20-57':['Channel of the Brain Wave','Penetrating Awareness','Your intuition in the moment is very sharp, and you can name the key point on the spot.'],
  '21-45':['Channel of Money','A Materialist','You are good at managing resources and people, and suited to making the material decisions.'],
  '23-43':['Channel of Structuring','Individuality (Genius to Freak)','You have unique insights that are understood only when someone asks for them.'],
  '24-61':['Channel of Awareness','A Thinker','You keep pondering the mysteries of life, and inspiration arrives suddenly.'],
  '25-51':['Channel of Initiation','Needing to Be First','You have the courage to rush into the unknown and bring awakening through shock.'],
  '26-44':['Channel of Surrender','A Transmitter','You are good at selling and passing things on, and you know what people need.'],
  '27-50':['Channel of Preservation','Custodianship','You care for and protect others, and take values and responsibility seriously.'],
  '28-38':['Channel of Struggle','Stubbornness','You are willing to fight to the end for what is meaningful.'],
  '29-46':['Channel of Discovery','Succeeding Where Others Fail','Once you commit, you give yourself fully and discover meaning along the way.'],
  '30-41':['Channel of Recognition','Focused Energy','You long for new experiences and carry dreams and passion.'],
  '32-54':['Channel of Transformation','Being Driven','You have the ambition to climb, and know how to recognize what is worth carrying on.'],
  '34-57':['Channel of Power','An Archetype','You survive in the moment through intuition and power, with very fast reactions.'],
  '35-36':['Channel of Transitoriness','A Jack of All Trades','You chase new experiences and feelings, and gather wisdom from the ups and downs.'],
  '37-40':['Channel of Community','A Part Seeking a Whole','You value agreements and a fair balance of giving, and are a pillar of the group.'],
  '39-55':['Channel of Emoting','Moodiness','Your emotions swing widely, and you are rich in spirit and creativity.'],
  '42-53':['Channel of Maturation','Balanced Development','You carry things from beginning to completion, and grow through cycles.'],
  '47-64':['Channel of Abstraction','Mental Activity Mixed with Clarity','You turn past experiences into meaning and understanding.']},
 gates:{1:'Self-Expression',2:'Direction of the Self',3:'Ordering',4:'Formulization',5:'Fixed Rhythms',6:'Friction',7:'The Role of the Self',8:'Contribution',9:'Focus',10:'Behavior of the Self',11:'Ideas',12:'Caution',13:'The Listener',14:'Power Skills',15:'Extremes',16:'Skills',17:'Opinions',18:'Correction',19:'Wanting',20:'The Now',21:'The Hunter',22:'Openness',23:'Assimilation',24:'Rationalization',25:'The Spirit of the Self',26:'The Egoist',27:'Caring',28:'The Game Player',29:'Perseverance',30:'Feelings',31:'Influence',32:'Continuity',33:'Privacy',34:'Power',35:'Change',36:'Crisis',37:'Friendship',38:'The Fighter',39:'Provocation',40:'Aloneness',41:'Contraction',42:'Growth',43:'Insight',44:'Alertness',45:'The Gatherer',46:'Determination of the Self',47:'Realization',48:'Depth',49:'Principles',50:'Values',51:'Shock',52:'Stillness',53:'Beginnings',54:'Ambition',55:'Spirit',56:'Stimulation',57:'Intuitive Clarity',58:'Vitality',59:'Sexuality',60:'Acceptance',61:'Mystery',62:'Details',63:'Doubt',64:'Confusion'}
};
const Z=globalThis.HDZ||(typeof HDZ!=='undefined'?HDZ:null);
if(Z){HDE.crossTable=Z.crossTable;Object.keys(Z.crossNames).forEach(k=>{HDE.crossNames[k]=k;});}
var HDS=globalThis.HDS||{};HDS.en=HDE;globalThis.HDS=HDS;
})();
