/* Highlights, answer card, calendar and compatibility: English text pack (assembled by js/hl-i18n.js) */
(function(root){
const PN={'命宮':'Life','兄弟':'Siblings','夫妻':'Spouse','子女':'Children','財帛':'Wealth','疾厄':'Health','遷移':'Travel','僕役':'Friends','官祿':'Career','田宅':'Property','福德':'Fortune','父母':'Parents'};
const ord=n=>{const v=n%100;return n+((v>=11&&v<=13)?'th':({1:'st',2:'nd',3:'rd'})[n%10]||'th');};
const cap=s=>s?s.charAt(0).toUpperCase()+s.slice(1):s;
const list=a=>a.length<=1?(a[0]||''):a.length===2?`${a[0]} and ${a[1]}`:`${a.slice(0,-1).join(', ')} and ${a[a.length-1]}`;
const pal=n=>`${PN[n]} palace`,house=h=>`${ord(h)} house`;
const MUT={'祿':'Hua Lu (gain)','權':'Hua Quan (power)','科':'Hua Ke (fame)','忌':'Hua Ji (snag)'};
const swap=(s,a,b)=>String(s).replace(new RegExp(`\\b${a}\\b`,'g'),b).replace(new RegExp(`\\b${cap(a)}\\b`,'g'),cap(b));
const T={
 locale:'en-US',
 q:t=>`“${t}”`,
 first:t=>{const m=String(t||'').match(/^[\s\S]*?[.!?]["”’)]?(?=\s|$)/);return m?m[0]:String(t||'');},
 sep:', ',sep2:'; ',colon:': ',stop:'.',dot:' · ',paren:t=>` (${t})`,list,
 pal,your:n=>`your ${pal(n)}`,house,mut:k=>MUT[k],asc:'Ascendant',
 lunar:(m,leap)=>`${leap?'Leap ':''}${ord(m)} lunar month`,
 decade:s=>swap(s,'this year','this decade'),
 month:s=>swap(s,'this year','this month'),
 TONE:{up:['Tailwind','up'],even:['Steady','even'],hard:['Effort','hard']},
 DOM:{'命宮':'yourself','兄弟':'siblings and friends','夫妻':'love and partnership','子女':'children, investments and partnerships','財帛':'money','疾厄':'your body and daily rhythm','遷移':'travel, moving and chances away from home','僕役':'your network, colleagues and team','官祿':'work and career','田宅':'home, property and savings','福德':'your mood and quality of life','父母':'elders, bosses and paperwork'},
 DOMY:{'命宮':'you yourself','兄弟':'siblings and friends','夫妻':'love','子女':'children, investments and partnerships','財帛':'money','疾厄':'your health','遷移':'travel and moving','僕役':'your network','官祿':'work','田宅':'home and property','福德':'your state of mind','父母':'elders and bosses'},
 FOCUS:{
  '命宮':'This year brings you back to yourself. You care more about who you want to become; it is a good time to sort out your direction, refresh your look and set new goals.',
  '兄弟':'This year you interact more with the people around you: siblings, old friends, potential partners. Someone may invite you to do something together, or you may need to work out boundaries.',
  '夫妻':'This year is about love. If you are single, someone is likely to appear; if you are in a relationship, you will face the question of whether to take the next step.',
  '子女':'This year is about what you put out into the world: children, students, creative work, investments, partnerships. You will want to channel your energy somewhere new.',
  '財帛':'This year you feel money more keenly. How you earn, how you spend and how you save all get rethought.',
  '疾厄':'This year your body reminds you it is there. Sleep, food and exercise are the best things to invest in this year.',
  '遷移':'This year favors heading out: business trips, travel, moving, a change of scene, projects in other places. There are more chances out there than at home.',
  '僕役':'This year your network is key. New colleagues, clients and circles will shape the road ahead. Learn to tell who is sincere.',
  '官祿':'This year work takes center stage. A promotion, a career change or a big project may come along: busy, but rewarding.',
  '田宅':'This year the focus comes home: moving, renovating, buying property, family matters, or finally getting serious about savings.',
  '福德':'This year your inner life matters more. You want to slow down and learn things you love; it is a good time to look after your feelings.',
  '父母':'This year you deal more with elders, bosses and institutions. Exams, certificates, documents and contracts are in focus.'},
 LU:{
  '命宮':'You get along better with people overall, and others are more willing to help.','兄弟':'Friends or siblings bring good news, and collaborations come together easily.','夫妻':'Love gets sweeter; a partner or love interest brings you luck.','子女':'Investments, partnerships, children or creative work pay off.',
  '財帛':'Money flows more smoothly: a raise, a bonus or a new source of income is likely.','疾厄':'You are in good shape; a great time to build healthy habits.','遷移':'Helpful people appear when you are away from home; travel and opportunities elsewhere are especially good.','僕役':'Colleagues, clients and friends bring resources and opportunities.',
  '官祿':'Work goes smoothly, with chances to shine and be promoted.','田宅':'Home life goes well: a good time to tidy up, move or buy things for the house.','福德':'You are in good spirits, life feels richer, and you can enjoy yourself a little more.','父母':'Elders or bosses back you up, and exams and paperwork go smoothly.'},
 JI:{
  '命宮':'You may demand too much of yourself and overthink; leave yourself some slack.','兄弟':'There may be friction with friends or siblings; be careful about lending money or co-signing.','夫妻':'Communication in love can get stuck; dig up the past less and listen more.','子女':'Be conservative with investments and partnerships; you may also worry about children or students.',
  '財帛':'Income and spending swing more; avoid high-risk bets and build an emergency fund first.','疾厄':'Fatigue builds up easily; keep a regular routine and get check-ups.','遷移':'Things are harder away from home; take care when traveling and keep a low profile.','僕役':'Choose partners carefully; others may drag you down or misunderstand you.',
  '官祿':'Work pressure is high and things may stall; ask for advice before big decisions.','田宅':'Home or property matters weigh on you; be disciplined about saving.','福德':'You may wear yourself out emotionally or sleep badly; schedule time to unwind.','父母':'Talking with bosses or elders is harder; read contracts and documents carefully.'},
 KID_FOCUS:{'夫妻':'This year is about the people closest to you: best friends and classmates you like. A time to learn to share your feelings and to respect others.','子女':'This year is great for hobbies and making things: drawing, music, sports, building. Your energy wants to reach outward.','財帛':'This year is a good time to learn how to use and save pocket money, and to build a basic sense of money.','遷移':'This year favors heading out: trips, camps, a new school or a move. Being out in the world broadens your horizons.','僕役':'This year classmates and friends have a big influence; new groups and clubs bring lots of learning.','官祿':'This year school takes center stage: tests, competitions and choices. Effort gets noticed.','田宅':'This year the focus is at home: moving, a new room, family matters. The mood at home matters a lot.'},
 KID_LU:{'夫妻':'Friendships are going well, and it is easy to meet people you click with.','財帛':'Rewards, red envelopes or scholarships come easily; a good time to learn to save.','官祿':'Schoolwork goes well, with good results in tests and competitions.','僕役':'Classmates and friends help out, and group life is fun.','子女':'Hobbies and creative work pay off; show them off more.','田宅':'The mood at home is good and life feels settled.'},
 KID_JI:{'夫妻':'Small misunderstandings with close friends are likely; say how you feel.','財帛':'Pocket money goes too fast; learn to keep track and budget.','官祿':'Schoolwork is more stressful; plan time for both study and rest.','僕役':'Friction among classmates is likely; if something bothers you, tell a grown-up.','子女':'Setbacks in hobbies are likely; give yourself more time.','田宅':'Family matters can be upsetting; talk more with your family.','遷移':'Stay safe when you are out and about, and stick with the grown-ups.'},
 STU_FOCUS:{'遷移':'This year favors heading out: travel, exchanges, camps, living in a dorm or studying elsewhere. Being out in the world broadens your horizons.','兄弟':'This year you spend more time with siblings and close friends. You may team up on something, and learn to handle boundaries.','夫妻':'This year is about love and close friendships: you may have a crush, and you will learn how to express yourself and get along.','子女':'This year is good for developing hobbies, creative work and clubs; your energy wants to reach outward.','財帛':'This year is a good time to learn to manage pocket money or part-time income, and to build a sense of money.','官祿':'This year school takes center stage: exams, admissions, choosing a major or a first internship. Effort gets noticed.','僕役':'This year classmates, clubs and new friends have a big influence on where you go next.','父母':'This year you deal more with teachers and parents; exams, certificates and applications are in focus.','田宅':'This year the focus is on home and where you live: moving, dorms, family matters. The mood at home matters a lot.'},
 STU_LU:{'僕役':'Classmates and friends bring help and opportunities.','兄弟':'Siblings or close friends bring good news, and joint projects go well.','夫妻':'You are popular and lucky in love; it is easy to meet people you click with.','財帛':'Scholarships, part-time work or extra income come your way.','官祿':'Studies go well, with good results in exams, competitions and applications.','父母':'Teachers and parents support you, and exams and paperwork go smoothly.','子女':'Hobbies and creative work pay off; show them off more.'},
 STU_JI:{'僕役':'Misunderstandings with classmates are likely, or others may drag you down; choose sincere friends.','兄弟':'There may be friction with siblings or close friends; be careful about lending money.','夫妻':'Misunderstandings in love or friendship are likely; say how you feel.','財帛':'Money goes too fast; learn to keep track and budget.','官祿':'Study pressure is high; plan time for both study and rest.','父母':'Talking with teachers or parents is harder; read application documents carefully.','子女':'Setbacks in hobbies are likely; give yourself more time.'},
 SEN_DOM:{'官祿':'your daily focus and roles','財帛':'pension and spending','子女':'children and grandchildren','夫妻':'your spouse and those closest to you','僕役':'friends and your social circle','父母':'paperwork, insurance and formalities'},
 SEN_FOCUS:{'夫妻':'This year is about life with your spouse or the person closest to you: plan your days and outings together, and look after each other.','子女':'This year you see more of your children and grandchildren; a good time to pass your experience on.','財帛':'This year you feel money more keenly: pension, insurance and everyday spending are worth reviewing, with stability first.','官祿':'This year your daily focus and roles shift: retirement plans, volunteering, clubs or something you have always wanted to learn can bring a new sense of achievement.','僕役':'This year friends and your social circle matter: clubs, reunions and neighborhood activities lift your mood.','父母':'This year brings more paperwork, insurance, ID renewals and formalities; read carefully before you sign.','遷移':'This year is good for getting out: travel, visiting family, a change of scene, as long as you pace yourself.','兄弟':'This year you see more of your siblings and old friends, and you look out for each other.'},
 SEN_LU:{'兄弟':'Siblings or old friends bring good news, and you look out for each other.','夫妻':'Life with your spouse or close ones is harmonious; you lean on each other.','子女':'Children and grandchildren bring good news and care.','財帛':'Money feels more comfortable, and pension or financial plans go smoothly.','官祿':'Your days feel steady, and what you take part in brings a sense of achievement.','僕役':'Friends and clubs bring company and good cheer.','父母':'Formalities and paperwork go smoothly.'},
 SEN_JI:{'遷移':'Take care with traffic and safety when you are out, and don’t overpack your schedule.','夫妻':'Small squabbles with your spouse are likely; be understanding and say thank you more.','子女':'You may worry about children or grandchildren; care, but you don’t need to step into everything.','財帛':'Be conservative with money, avoid high-risk investments, and watch out for scams.','官祿':'Your routine may get disrupted; don’t take on too much at once.','僕役':'Misunderstandings with others are likely; be careful about lending money or co-signing.','父母':'Formalities and paperwork are error-prone; go over important matters with family.','疾厄':'Your body needs extra care; regular check-ups and a steady routine matter most.'},
 STU_DOM:{'官祿':'school','子女':'hobbies and creative work','財帛':'pocket money and part-time work','夫妻':'love and close friendships','僕役':'classmates and friends','父母':'parents and teachers'},
 KID_DOM:{'夫妻':'close friends and getting along','財帛':'pocket money'},
 JUP:['confidence and visibility grow; a good time to start new plans','chances for more income or resources','more learning, writing and short trips','good changes in family life and your living space','luck in romance, creativity and fun','work routines and health habits improve easily','partnerships and relationships bring opportunities','shared resources, investments or deep change pay off','further study, travel abroad and broader horizons','career visibility and chances for promotion','your circle of friends grows, and groups bring opportunities','a time for rest, reflection and inner repair'],
 SAT:['you expect more of yourself; a time to redefine who you are','you need to face money and self-worth seriously','communication and learning need more care and groundwork','family and household responsibilities grow','love and creative work must stand the test of time','workload and health need managing','partnerships enter a phase of testing and commitment','deep lessons around shared money and intimacy','beliefs and direction need a fresh look','you carry more responsibility at work, and your effort will be seen','your circle gets filtered, leaving the people truly on your path','closing an old cycle and preparing for the next'],
 JUP_Y:['confidence grows; a good time to try new things','rewards, scholarships or resources come easily','more learning, reading and writing, with a chance to improve your grades','a good mood at home, with family support','luck with play, creativity and making friends','daily habits improve and you feel healthier','close friendships bring good chances','you understand things more deeply','a good time for exchanges abroad, camps and broader horizons','you get noticed at school, in competitions or on stage','your circle of friends grows, and clubs bring opportunities','a good time for rest and reflection'],
 SAT_Y:['you start to expect more of yourself and learn independence','learning to manage your own things and pocket money','study needs steady groundwork; the basics matter','more is going on at home; be understanding with family','hobbies and friendships are put to the test','schoolwork and routines need good management','learning to give and take in close friendships','facing deeper emotional lessons','time to rethink what you want to study','more responsibility at school, and your effort will be seen','your circle gets filtered, leaving the people you truly click with','closing one stage and getting ready for a new environment'],
 JUP_S:['good energy and a taste for new things','finances feel comfortable, or family looks after you','more joy in learning, reading and chatting with people','good changes at home, and family gatherings','hobbies, fun and time with grandchildren are a delight','healthy habits are easier to build','good things happen with your spouse or close ones','a deeper understanding of life','a good time to travel a little farther afield','your experience is valued and respected','friends and clubs bring company','a good time for quiet rest and self-care'],
 SAT_S:['your energy and spirits need looking after','be conservative with money and plan well','be patient in conversations and double-check','home safety and family matters need attention','enjoy hobbies and entertainment at your own pace','health needs a regular routine and check-ups','you and your spouse need to make allowances for each other','facing deeper life questions','rethinking the direction of daily life','you still carry responsibilities; do what you comfortably can','your circle gets smaller, leaving those you treasure most','a good time to wrap up, sort out and let go']
};
T.hl={
 basis:'Based on',
 agree:s=>`${cap(s)} agree`,youAre:(th,tag)=>`${th}: ${T.q(tag)}`,
 core:'Your core',
 mingWhy:(empty,stars)=>`Life palace${empty?' (no main star, borrowing the opposite palace)':''}: ${stars}`,
 sunAsc:(s,a)=>`Sun in ${s}, Ascendant in ${a}`,hdWhy:(t,p)=>`Human Design: ${t}, ${p}`,
 chapter:r=>`This chapter (age ${r[0]}–${r[1]})`,chapter0:'This chapter',
 focusOn:d=>`Focus on ${d}`,
 thisYear:(y,yp)=>`This year (${y}), your yearly Life palace moves to your ${pal(yp)}.`,
 decWhy:(p,g)=>`Ten-year Life palace in your natal ${pal(p)} (${g})`,
 decStars:(s,empty)=>`Main stars of the decade: ${s}${empty?' (empty palace, borrowing the opposite one)':''}`,
 yearWhy:(g,yp)=>`Year ${g}; yearly Life palace in your ${pal(yp)}`,
 unbornT:'Not born yet',unbornB:'This birthday is in the future, so there are no ten-year periods or yearly cycles to read yet; the natal chart still applies.',unbornW:by=>`Lunar birth year ${by}`,
 doneT:'All twelve ten-year periods are complete',doneB:(a,l)=>`At age ${a} (East Asian count), you are past the last ten-year period on the chart, which ends at ${l}. The decade readings no longer apply, but the natal chart and the yearly cycles still do.`,doneW:l=>`The last ten-year period ends at age ${l}`,
 childT:'Still in the childhood period',childB:'The first ten-year period has not started yet; for now, the Life palace and the family environment shape the direction most.',childW:f=>`The first ten-year period starts at age ${f}`,
 newDec:(r,p)=>`A new ten-year period begins (age ${r[0]}–${r[1]}, ${pal(p)})`,
 decFocus:d=>`These ten years center on ${d}.`,
 around:(ms,first)=>` (around ${list(ms)}${first?'':', continuing from last year'})`,
 satReturn:'Saturn return',satReturnT:'a major life test that comes about every 29 years. It pushes you to face the life you really want and let go of what no longer fits.',
 satOpp:'Saturn opposite natal Saturn',satOppT:'a midlife checkpoint where past choices get re-evaluated.',
 jupReturn:'Jupiter return',jupReturnT:'the start of a new cycle that comes about every 12 years; a good time to start fresh and think bigger.',
 uraOpp:'Uranus opposition',uraOppT:'the well-known “midlife turning point.” The urge to break through and change is strong; a good time to do something you have always wanted to do.',
 hd6up:'Human Design 6th line: onto the roof',hd6upT:'from around 30, you shift from learning by trial and error to a phase of observing and maturing.',
 hd6down:'Human Design 6th line: off the roof',hd6downT:'from around 50, the experience you have gathered makes you a role model for others.',
 decHead:(p,title)=>`New ten-year period (${pal(p)})${title?': '+title:''}`,
 ypLine:(yp,ov)=>`Yearly Life palace in your ${pal(yp)}${ov?' (overlapping the ten-year Life palace, so highs and lows are amplified)':''}`,
 alsoYearly:(yp,d)=>` (also this year’s yearly ${pal(yp)}, which touches ${d==='yourself'?'you':d} too)`,
 mutIn:(s,k,p)=>`${s} ${MUT[k]} enters your ${pal(p)}`,
 notes:{
  nji:(s,p,d)=>`<b>Your birth-year Hua Ji star, ${s}, sits in this year’s yearly Life palace</b>: old issues may resurface this year; be extra patient with ${d}.`,
  dji:(s,p)=>`<b>Double Hua Ji: ${s} has Hua Ji at birth and again this year</b>: your ${pal(p)} is the place to be most careful this year; slow down on big decisions.`,
  nlu:s=>`<b>Your birth-year Hua Lu star, ${s}, sits in this year’s yearly Life palace</b>: your natural luck gets switched on, and things go more smoothly.`,
  dlu:(s,p)=>`<b>Double Hua Lu: ${s} has Hua Lu at birth and again this year</b>: the good things in your ${pal(p)} are doubled.`,
  dcji:s=>`<b>The decade’s Hua Ji star, ${s}, sits in this year’s yearly Life palace</b>: the pressure of this ten-year period is felt most this year.`,
  dclu:s=>`<b>The decade’s Hua Lu star, ${s}, sits in this year’s yearly Life palace</b>: the opportunities of this ten-year period are easiest to catch this year.`},
 ingFrom:m=>`from ${m}`,ingInto:(m,h)=>`entering your ${house(h)} in ${m}`,
 jupLine:h=>`Jupiter spends most of this year in your ${house(h)}`,satLine:(h,hard)=>hard?`Saturn spends most of this year in your ${house(h)}, this year’s heavier area`:`Saturn spends most of this year in your ${house(h)}`,satHard:'',ingBack:m=>`back from ${m}`,
 age:n=>`age ${n}`,
 past:'Looking back: did you go through any of this that year?',
 tlTitle:'Your path, year by year',
 tlIntro:(a,b)=>`From ${a} to ${b}. Past years are there to check against your memory. “Tailwind / Steady / Effort” is an overall estimate based on where the yearly Si Hua (four transformations) land and on Jupiter and Saturn transits, including how the birth-year and ten-year Si Hua touch the yearly Life palace. It is not a verdict of good or bad. Ages use the East Asian count (age 1 at birth), as in Zi Wei.`,
 tlUnborn:'Not born yet in this period, so there are no yearly cycles to read.'
};
T.intent={
 kicker:'What you asked',more:'See the full theme report →',
 kidT:'Still growing up',kidB:a=>`This chart is at age ${a} (East Asian count), so the timing of love, work and income will mean more a little later. For now, the core traits above and the school, family and hobby notes in the timeline below are more useful.`,
 STATUS:{
  single:{ask:'When will I meet the right person?',good:'Years with more chances for love',tip:'In these years, go out more, join friends’ gatherings or say yes to introductions. It works better than waiting quietly.'},
  crush:{ask:'Can this almost-relationship move forward?',good:'Years for making things clear and taking a step forward',tip:'If you have been waiting a long time, pick a relaxed moment and say how you feel. It beats guessing.'},
  dating:{ask:'What is the next step for us?',good:'Years for next steps like moving in, meeting the family or getting married',tip:'Raise big decisions in the smoother years; agreement comes more easily then.'},
  married:{ask:'How can we make our marriage even better?',good:'Years when things get sweeter and are good for planning together',tip:'In smooth years, plan a trip or a shared goal; in tougher years, be a little more patient and leave old arguments in the past.'},
  broke:{ask:'How do I let go, and when will something new begin?',good:'Years when new connections come more easily',tip:'Look after yourself first: sleep well, eat well and talk to friends you trust. Give yourself time without pressure to decide anything. Whether to go back is your call, not the chart’s; you deserve a relationship that feels safe.'},
  none:{ask:'How will love unfold?',good:'Years with more chances for love',tip:''}},
 loveT:a=>`Love: ${a}`,loveYou:t=>`How you are in love: ${t}.`,
 threeSay:t=>`Across all three charts, your strongest notes are ${t}.`,threeType:t=>`Across all three charts, your strongest notes are ${t}.`,
 relative:' (relatively)',
 loveNone:'No single year stands out for love in the next few years. Chances are spread fairly evenly, so what matters most is that you take the initiative.',
 loveBad:'Years that call for a little more patience',
 loveSen:'At this stage, love is about how you and your spouse or the important people around you get along and look after each other. Smooth years are good for trips and shared plans; tougher years call for a bit more understanding.',
 JOB:{
  student:{ask:'Which direction should I take?',good:'Years to push for exams and settle on a direction',tip:'While you are still studying, try lots of things. The strengths in your chart show which things come easily to you.'},
  seeking:{ask:'When will it be easier to find a good job?',good:'Years when job hunting and interviews go more smoothly',tip:'Even if this is not the smoothest year, get your portfolio and résumé ready now so you can catch the chance when it comes.'},
  employee:{ask:'Promotion or a new stage?',good:'Years when your work gets noticed and a promotion is worth going for',tip:'In smooth years, ask for what you want; in tougher years, build your skills and don’t rush to jump.'},
  founder:{ask:'When should I expand, and when should I hold?',good:'Years to expand and make your move',tip:'Expand in smooth years; in tougher years, protect your cash flow and your team first.'},
  change:{ask:'When is a good time to change careers?',good:'Years for switching tracks and starting something new',tip:'Before switching, test the waters on a small scale with a side project or a course, and commit fully once you get a response.'},
  none:{ask:'How will my career unfold?',good:'Years with more work opportunities',tip:''}},
 workT:a=>`Work: ${a}`,moneyT:'Money: when is it smoother, and when should I hold back?',
 workYou:t=>`Your way of working: ${t}.`,moneyYou:t=>`How you make money: ${t}.`,
 fields:f=>`Directions that suit you: ${f}`,
 moneyGood:'Years when income and opportunities flow more smoothly',
 workNone:'No particular years stand out in the next few; steady building matters more than waiting for the right moment.',
 workBad:'Years to hold steady and build up',moneyBad:'Years to be conservative with money',
 workSen:'At this stage it is less about promotion and more about how you spend your days: smooth years are good for volunteering, clubs, teaching or something you have always wanted to learn; in tougher years, do what you comfortably can.',
 moneySen:'In smooth years you can enjoy life a little more; in conservative years, focus on your pension and insurance, avoid high-risk investments and watch out for scams.',
 moneyTip:'In smooth years, save part of any extra income first; in conservative years, avoid high-risk investments and build up six months of emergency funds.',
 yearT:y=>`How will this year (${y}) go?`,
 yearBody:o=>{let s=`<b>This year centers on ${o.focus}.</b>`;const a=[];if(o.lu)a.push(`things flow in ${o.lu.dom} (${o.lu.how})`);if(o.ji)a.push(`what needs more care is ${o.ji.dom} (${o.ji.how})`);if(a.length)s+=' '+cap(a.join('; '))+'.';
   const b=[];if(o.jup)b.push(`Jupiter moves through your ${house(o.jup)}`);if(o.sat)b.push(`Saturn sits in your ${house(o.sat)}`);if(b.length)s+=' '+b.join(', and ')+'.';return s;},
 nextYear:(y,d,dec)=>`<b>Next year (${y})</b>, the focus shifts to ${d}${dec?', and a new ten-year period begins':''}.`,
 yearTip:y=>`The year ${y} is already expanded in the timeline below, with all the details.`,
 mixed:t=>`; but the same year also has ${t}, so expect a mix`,
 R:{yp:(s,p)=>`yearly Life palace in your ${pal(p)}`,lu:(s,p)=>`${s} Hua Lu enters your ${pal(p)}`,quan:(s,p)=>`${s} Hua Quan enters your ${pal(p)}`,ji:(s,p)=>`${s} Hua Ji enters your ${pal(p)}`,
   ylu:(s,p)=>`${s} Hua Lu enters the yearly ${pal(p)}`,yji:(s,p)=>`${s} Hua Ji enters the yearly ${pal(p)}`,jup:(s,p,h)=>`Jupiter in your ${house(h)}`,sat:(s,p,h)=>`Saturn in your ${house(h)}`}
};
T.cal={
 TONE:{up:['Smooth','up'],even:['Even','even'],hard:['Watch','hard']},
 mpLine:p=>`Monthly Life palace in your ${pal(p)}`,monthly:p=>`monthly ${pal(p)}`,
 RETRO:{Mercury:['Mercury retrograde','double-check contracts, gadget purchases, travel plans and important conversations. Good for reviewing and fixing, not for rushing into new starts.'],Venus:['Venus retrograde','slow down on decisions about love and spending; old flames and old friends may come back into your life.'],Mars:['Mars retrograde','action may stall or need redoing. Let conflicts cool before dealing with them, and build slack into your plans.']},
 ing:(k,d,h)=>`${k==='Jupiter'?'Jupiter':'Saturn'} enters your ${house(h)} around ${d}`,
 nowK:(lab,r)=>`This month (${lab}, about ${r})`,
 title:y=>`${y} month-by-month calendar (lunar year ${y})`,
 intro:'Each month is read from the monthly Life palace and where the monthly Si Hua (four transformations) land in your natal chart, plus Mercury, Venus and Mars retrogrades and Jupiter and Saturn changing houses. Dates are approximate, and “Smooth / Even / Watch” is only a rough overall estimate.'
};
const PD={'命宮':'confidence and overall luck','兄弟':'friendships and sibling ties','夫妻':'love life','子女':'children, investments and collaborations','財帛':'finances','疾厄':'health and well-being','遷移':'life out in the world','僕役':'social circle','官祿':'career','田宅':'home life','福德':'peace of mind','父母':'family and elders'};
const ASPV=['conjunct','sextile','square','trine','opposite'];
T.pair={
 who:nm=>nm?{n:nm,N:nm,poss:nm+'’s',Poss:nm+'’s'}:{n:'the other person',N:'The other person',poss:'the other person’s',Poss:'The other person’s'},
 item:(it,c)=>{const nb=c.nb;switch(it.t){
  case 'syn':return `your ${c.planet(it.s.a)} ${ASPV[c.ai(it.s)]} ${nb.poss} ${c.planet(it.s.b)}`;
  case 'hdem':return `Human Design electromagnetic channel ${it.k}`;case 'hdcomp':return `shared Human Design channel ${it.k}`;case 'hdcmp':return `Human Design compromise channel ${it.k}`;case 'hddom':return `Human Design dominance channel ${it.k}`;
  case 'zlu':return it.dir==='AB'?`${nb.poss} birth-year Hua Lu enters your ${pal(it.pal)}`:`your birth-year Hua Lu enters ${nb.poss} ${pal(it.pal)}`;
  case 'zji':return it.dir==='AB'?`${nb.poss} birth-year Hua Ji enters your ${pal(it.pal)}`:`your birth-year Hua Ji enters ${nb.poss} ${pal(it.pal)}`;
  case 'match':return it.dir==='AB'?`${nb.poss} Life palace stars (${it.stars.map(c.star).join(', ')}) are the very stars of your Spouse palace`:`your Life palace stars (${it.stars.map(c.star).join(', ')}) are the very stars of ${nb.poss} Spouse palace`;
  case 'zod':return {he:'zodiac animals in Liu He (six harmonies)',san:'zodiac animals in San He (three harmonies)',chong:'zodiac animals in clash'}[it.rel];
  case 'ov':return it.dir==='AB'?`${nb.poss} ${c.planet(it.k)} in your ${house(it.h)}`:`your ${c.planet(it.k)} in ${nb.poss} ${house(it.h)}`;}return '';},
 LV:['Not obvious','Some','Clear','Very strong'],LVF:['Few','Some','Quite a few','Many'],
 MN:{attract:['Attraction','The spark and chemistry between you'],sync:['Rapport','Whether you click and understand each other'],stable:['Stability','Whether this can last and feel safe'],friction:['Friction','Where you get stuck and need to work things out']},
 basis:n=>`${n} ${n===1?'indicator':'indicators'}`,
 sumNone:nb=>`Putting your three charts next to ${nb.poss}, attraction, rapport and stability show no standout markers. The shape of this relationship depends more on how you both nurture it than on any built-in pull.`,
 sumTop:(nb,a,b)=>`Putting your three charts next to ${nb.poss}, the clearest thing between you is <b>${a.toLowerCase()}</b>${b?`, followed by <b>${b.toLowerCase()}</b>`:''}.`,
 frMany:'There is also a fair amount of friction. That is not a bad thing: many lasting relationships are forged through arguments, and the key is knowing where you tend to get stuck.',
 frFew:'There is little friction, so being together takes less effort.',
 noSign:'no clear indicators',
 h:{sum:'Overview',west:'Synastry',aspects:'Key aspects between you',ovAB:nb=>`Where ${nb.poss} planets fall in your chart`,ovBA:nb=>`Where your planets fall in ${nb.poss} chart`,zw:'Zi Wei compatibility',fly:'Birth-year Si Hua across the two charts',match:'Is this person the type your Spouse palace describes?',zod:'Chinese zodiac',hd:'Human Design compatibility',withB:nb=>`Getting along with ${nb.n}`,bWithYou:nb=>`How ${nb.n} can get along with you`,tips:'Advice for you both'},
 orb:x=>`orb ${x}°`,
 noAsp:'There are no close aspects between your personal planets; the heart of this relationship lies more in the other systems.',
 SYN:{
  'Moon-Sun':{conj:'One person’s Sun meets the other’s Moon, the classic compatibility pairing: what one wants to do, the other supports from the heart. Together you often feel truly understood.',soft:'One person’s sense of direction fits the other’s emotional needs. Daily life together feels natural, and adjusting to each other takes little effort.',hard:'One wants to charge ahead while the other needs security. Your rhythms often don’t line up, so say what you need instead of making the other person guess.'},
  'Sun-Sun':{conj:'Your core traits are very alike, like looking in a mirror: easy to understand each other, though you may both want to be the lead.',soft:'Your life directions echo each other, and you work in sync when you do the same thing.',hard:'You express yourselves differently, and neither wants to give way first. Clear roles and a stage for each of you mean fewer clashes.'},
  'Moon-Moon':{conj:'Your emotional habits are almost the same, so being together feels like coming home. The downside: when one is down, you may both sink together.',soft:'You handle feelings in compatible ways, and you make up more easily after a fight.',hard:'One of you needs to talk it out, the other needs quiet. When emotions rise, start by asking, “What do you need right now?”'},
  'Mars-Venus':{conj:'Strong attraction: one person’s charm sets off the other’s drive. A pairing with real sparks.',soft:'Natural chemistry: pursuing and being pursued both feel easy, and closeness builds quickly.',hard:'The attraction is strong, and so is the friction. The more you care, the more you argue, and afterward you want to be close again.'},
  'Venus-Venus':{conj:'You like the same things: taste, kinds of dates and ways of showing love all match.',soft:'You share a feel for beauty and pleasure, so everyday life together is enjoyable.',hard:'You show love differently: one feels they give a lot, the other doesn’t receive it. Spell out each other’s “love language.”'},
  'Mars-Mars':{conj:'You have the same drive. You act efficiently together, and you can also blow up at the same time.',soft:'Your pace of action matches, so exercising or working on projects together goes smoothly.',hard:'You handle conflict differently, and small things can turn into standoffs. Cool down first, then talk.'},
  'Mercury-Mercury':{conj:'You think in similar ways, and often the other gets it before you finish speaking.',soft:'You enjoy talking, communication flows, and you can discuss all kinds of things together.',hard:'You think differently: one goes for the big point, the other for details. Misunderstandings come easily, so write important things down or double-check.'},
  'Sun-Venus':{conj:'One really admires the other. That “I like you just as you are” feeling is very warm.',soft:'You appreciate each other and make each other feel attractive.',hard:'Admiration with a bit of tug-of-war: you like each other but may also want to change each other.'},
  'Moon-Venus':{conj:'A gentle, caring pairing; being together feels comfortable, like being well looked after.',soft:'You are good at caring for each other’s feelings and fit well in everyday details.',hard:'One wants to be cared for, the other wants to be admired. When expectations differ, say so.'},
  'Mars-Sun':{conj:'One fires up the other’s fighting spirit. Lots of energy together, and some rivalry too.',soft:'You push each other forward and get goals done together.',hard:'You can provoke each other and compete for control. Give each other room to make your own decisions.'},
  'Mars-Moon':{conj:'Feelings and action are bound together. The passion is direct, and it can sometimes hit the other’s sensitive spots.',soft:'One person’s drive protects the other’s feelings, which brings a sense of safety.',hard:'One speaks too bluntly and the other gets hurt easily. Think about the other person’s feelings before you speak.'},
  'Saturn-Sun':{conj:'A responsible bond: one is like the other’s teacher or rock. Stable, though it can also feel like pressure.',soft:'You bring each other stability and a sense of commitment, good for the long haul.',hard:'One may feel managed or restricted. Turn “demands” into “let’s talk it over.”'},
  'Moon-Saturn':{conj:'A bond with a strong sense of commitment, though one may feel their feelings aren’t being held.',soft:'You give each other security, and the relationship grows steadier with time.',hard:'One person’s feelings can be smothered by the other’s calm or strictness. Say “I understand you” a little more often.'},
  'Saturn-Venus':{conj:'A pairing that takes the relationship seriously, common in long-term couples, though romance needs deliberate care.',soft:'Love comes with responsibility, and you can plan the future together.',hard:'Love feels like pressure: one feels not loved enough, the other feels asked for too much.'},
  'ASC-Sun':{conj:'One feels it the moment they see the other. A strong first impression, often like meeting an old friend.',soft:'You make a good first impression on each other, and being together feels natural.',hard:'First impressions may clash a little; you only see each other’s good side once you get to know each other.'},
  'ASC-Venus':{conj:'An attraction of looks or presence: one finds the other especially easy on the eye.',soft:'You admire each other’s style, and you look natural together.',hard:'Your tastes or lifestyles differ somewhat, so you need to make room for each other.'},
  'ASC-Moon':{conj:'One makes the other feel very safe, like an old friend.',soft:'You are at ease together, with no need to pretend.',hard:'One person’s mood is easily swayed by how the other comes across.'}},
 OV_AB:{Sun:nb=>`${nb.N} makes you feel more present here and eager to shine.`,Moon:nb=>`${nb.N} makes this area feel familiar and safe to you, and it is where your feelings are stirred most easily.`,Venus:nb=>`${nb.N} makes this area feel pleasant and attractive to you.`,Mars:nb=>`${nb.N} stirs up your drive here; it is also where sparks or clashes come most easily.`},
 OV_BA:{Sun:nb=>`You make ${nb.n} feel more present here and eager to shine.`,Moon:nb=>`You make this area feel familiar and safe to ${nb.n}, and it is where ${nb.poss} feelings are stirred most easily.`,Venus:nb=>`You make this area feel pleasant and attractive to ${nb.n}.`,Mars:nb=>`You stir up ${nb.poss} drive here; it is also where sparks or clashes come most easily.`},
 flyIntro:'Place one person’s birth-year Si Hua (four transformations) on the other person’s chart to see what each brings the other and what each makes the other care about.',
 luAB:(nb,st,s,p)=>`${nb.Poss} Hua Lu (born in a ${st} year), ${s}, enters your ${pal(p)}`,
 jiAB:(nb,s,p)=>`${nb.Poss} Hua Ji, ${s}, enters your ${pal(p)}`,
 luBA:(nb,st,s,p)=>`Your Hua Lu (born in a ${st} year), ${s}, enters ${nb.poss} ${pal(p)}`,
 jiBA:(nb,s,p)=>`Your Hua Ji, ${s}, enters ${nb.poss} ${pal(p)}`,
 LU_P:{
  '命宮':nb=>`${nb.N} makes you more confident and luckier overall; together, you feel more like yourself.`,
  '兄弟':nb=>`${nb.N} gets on well with your friends and siblings, or helps you like a true teammate.`,
  '夫妻':nb=>`${nb.N} brings sweetness to your love life: a classic “meant to meet” pairing.`,
  '子女':nb=>`${nb.N} brings you luck with children, investments and collaborations.`,
  '財帛':nb=>`${nb.N} is good for your finances; money matters go more smoothly together.`,
  '疾厄':nb=>`${nb.N} helps you relax body and mind; around ${nb.n}, you take better care of yourself.`,
  '遷移':nb=>`${nb.N} takes you out into the world and widens your horizons and opportunities.`,
  '僕役':nb=>`${nb.N} brings connections and makes your social circle better.`,
  '官祿':nb=>`${nb.N} is good for your career and may be a real ally at work.`,
  '田宅':nb=>`${nb.N} gives you a sense of home; good for building a family or buying property together.`,
  '福德':nb=>`${nb.N} lifts your mood and makes you feel rich inside.`,
  '父母':nb=>`${nb.N} gets on well with your family and elders, or supports you the way an elder would.`},
 JI_P:{
  '命宮':nb=>`You care a lot about everything ${nb.n} does, and your moods swing most easily because of ${nb.n}.`,
  '兄弟':()=>'Friends, siblings or money between you can easily lead to resentment.',
  '夫妻':()=>'You hold on tight to this relationship; the more you care, the more easily communication gets stuck.',
  '子女':()=>'You may disagree about children, investments or collaborations.',
  '財帛':()=>'Your views on money may differ; talk through shared finances first.',
  '疾厄':nb=>`Stress can build up in your body when you are with ${nb.n}; keep some space for rest on both sides.`,
  '遷移':()=>'Outings, moves or long distance can cause friction.',
  '僕役':nb=>`Misunderstandings may arise over ${nb.poss} friends or a third party.`,
  '官祿':nb=>`${nb.N} can sway your work decisions, and you may disagree about careers.`,
  '田宅':()=>'You may disagree about family, where to live or property.',
  '福德':nb=>`${nb.N} can make you overthink; you may need some emotional adjusting.`,
  '父母':nb=>`Getting along with ${nb.poss} family and elders takes extra care.`},
 luBAT:(nb,p)=>`You bring ease and good luck to ${nb.poss} ${PD[p]}; with you around, this side of life tends to go better for ${nb.n}.`,
 jiBAT:(nb,p)=>`This is where ${nb.n} cares most about what you do, and where friction can build up around ${nb.poss} ${PD[p]}. Talk things through before they pile up.`,
 matchAB:(nb,sp,mg,m)=>`Your Spouse palace stars: ${sp}; ${nb.poss} Life palace stars: ${mg}. ${m?`<b>They overlap on ${m}</b>, so ${nb.n} is very much the kind of partner your chart describes.`:`No overlap: ${nb.n} is not the textbook type from your Spouse palace, so this relationship introduces you to a different kind of person.`}`,
 matchBA:(nb,sp,mg,m)=>`${nb.Poss} Spouse palace stars: ${sp}; your Life palace stars: ${mg}. ${m?`<b>They overlap on ${m}</b>, so you are very much the partner ${nb.poss} chart describes.`:'No overlap.'}`,
 ANI:['Rat','Ox','Tiger','Rabbit','Dragon','Snake','Horse','Goat','Monkey','Rooster','Dog','Pig'],
 zod:(nb,a,b,rel)=>`You were born in the year of the ${a}, and ${nb.n} in the year of the ${b} (by lunar year). `+({same:'Same animal: similar personalities and values, so being together feels like old friends.',he:'Liu He (six harmonies): traditionally a complementary, mutually supportive pairing.',san:'San He (three harmonies): traditionally like-minded and easy to work with.',chong:'A clash: traditionally different temperaments and paces that need more tolerance; it is also often where attraction starts.',hai:`A “harm” pairing (${a} and ${b}): traditionally prone to small misunderstandings or grudges. It is only a small reminder: say things clearly and don’t let feelings pile up.`,po:`A “break” pairing (${a} and ${b}): traditionally different rhythms or habits that occasionally upset each other’s plans. The effect is small; talk ahead and leave each other some flexibility.`,none:'There is no particular harmony or clash between your animals; other factors matter more.'})[rel],
 folk:' (Folk tradition; take it lightly.)',
 types:(nb,a,b)=>`You are a ${a}; ${nb.n} is a ${b}.`,
 TIP:{
  generator:nb=>`Talk with ${nb.n} using yes-or-no questions so the answer can come from the gut, rather than asking for an instant decision.`,
  mg:nb=>`${nb.N} moves fast and often does many things at once. Agree on a heads-up before acting; it saves a lot of misunderstandings.`,
  manifestor:nb=>`${nb.N} needs room to start things freely. Don’t try to control ${nb.n}, and ask for a heads-up to the people affected before acting.`,
  projector:nb=>`${nb.N} needs to be seen and invited. Sincerely ask for ${nb.poss} opinion, and you will get spot-on advice.`,
  reflector:nb=>`${nb.N} needs time (about a month) to make big decisions, so don’t rush. ${nb.N} reflects the true state of your relationship.`},
 TIP_YOU:{
  generator:nb=>`${nb.N} can talk with you using yes-or-no questions, so your answer can come from the gut, rather than expecting an instant decision.`,
  mg:nb=>`You move fast and often do many things at once. Agree with ${nb.n} to give a heads-up before acting; it saves a lot of misunderstandings.`,
  manifestor:nb=>`You need room to start things freely. ${nb.N} doesn’t need to control you; just let ${nb.n} know before you act.`,
  projector:nb=>`You need to be seen and invited. When ${nb.n} sincerely asks for your opinion, your advice is spot-on.`,
  reflector:nb=>`You need time (about a month) to make big decisions, so ${nb.n} shouldn’t rush you. You reflect the true state of this relationship.`},
 CH:{em:['Electromagnetic','Each of you has one half, and together the channel is complete: a source of attraction and sparks, and also where you most easily get “stuck” on each other.'],comp:['Companionship','Channels you both have: you are alike here, at ease together, with a shared language.'],dom:['Dominance','Only one of you has it and the other has no part of it: here one leads and the other is deeply influenced.'],cmp:['Compromise','One has the full channel and the other only half: here one of you may feel they always have to adapt.']},
 full:(isA,nb)=>isA?'you have the full channel':`${nb.n} has the full channel`,
 TIPS:{friction:'With lots of friction, deal with feelings first and the issue second when you argue. Agree on a “pause” signal.',attract:'Strong attraction is your asset; keep time just for the two of you even when life gets busy.',sync:'Rapport takes practice: one small thing you do together regularly (a walk, cooking, a show) works better than an occasional big outing.',stable:'Stability comes from agreements: talk early about what you expect from the future (money, where to live, children).'}
};
if(root.HLI)root.HLI.reg('en',T);
})(typeof globalThis!=='undefined'?globalThis:this);
