/* Starlit Western chart story content (English): Ascendant (first impression, how you meet the world) x Sun (core self) */
globalThis.STORY_WEST_ASC_EN={
ascSun:[
/* Aries rising */
[
`Your front door and your living room are lit by the same fire, and the gap between them is unusually small. You look impatient and you really are; you look bold and you really are. If the food is slow at a restaurant, you get up and ask at the counter, and what you say out loud is exactly what you think. People read you easily, and that directness is your gift. A reminder: count to three before you speak, so others have time to catch up.`,
`When people first meet you, you seem brisk and impatient, as if you want everything sorted right now. What you truly care about is building slowly and living a solid, steady life. Give a colleague the slightest nudge and you say "I'll do it," then you work through it carefully, making every step sound. Your reactions are fast; your resolve is slow and deep. Try this: say up front how much time you need, so no one mistakes your pace for losing steam.`,
`To strangers you look full of drive, the kind who acts the moment an idea lands. Underneath, you want to taste everything and talk the whole world through. Both sides are fast, and together they work like an accelerator. A friend mentions a new exhibition and you book tickets on the spot, then look up three nearby cafés on the way. You are rarely bored, but you scatter easily. One line for you: each season, pick one thing and see it through, so your curiosity leaves something behind.`,
`You arrive with a burst of energy, speaking plainly and moving fast, so people assume you are tough. Your core is soft, and what you worry about most is your family and your inner circle. You might argue hard with a shop on a friend's behalf, then come home and feel guilty all night because your mother said, "You hardly visit anymore." That armor exists to protect people. A reminder: with people you trust, you can take it off.`,
`You walk in already warm, direct and commanding, and deep down you want to make work that is truly yours and be seen for it. Two fires burn in the same direction, so you are built to stand at the front. When your club runs an event, you volunteer to host first, then reshape the whole program in your own style. The blind spot is that when you are eager to shine, you stop listening. Try this: share some of the stage with your teammates, and the applause gets louder.`,
`At first glance people see someone outspoken, quick and a little rash. The real direction of your life is to do things right and make them useful. The two sides often tug at each other: your mouth says yes, then your mind starts hunting for gaps. Your manager asks and you say "No problem," then you go back to your desk, list twenty open questions and stay up late filling them in. A reminder: before you agree, add "Let me check the details and get back to you."`,
`An Aries Ascendant sits exactly opposite a Libra Sun. You come across as straight to the point, yet inside you care a great deal about harmony and fairness. When friends plan a trip, you are the first to declare "Let's go to the coast," and the moment you say it you worry someone is unhappy, so you quickly add "What do you all think?" You can lead and you can mediate. One line for you: stating your view first is not selfish, as long as you really listen afterward.`,
`You look like someone who charges straight in, says what they think and takes on any fight. The real you runs very deep, wants to get to the bottom of things and see the whole board. People think they have figured you out when they have only seen the surface. In a meeting you seem to toss off a casual objection, and only later does everyone realize you had studied the other proposal inside out. Try this: let the people close to you see your calculations, and their trust will grow steadier.`,
`Both your first impression and your nature carry fire: you look ready to charge, and inside you want to go further still. The difference is that your outside is in a hurry about now, while your inside wants meaning and freedom. When the company asks for someone to open a market overseas, you raise your hand on the spot and start reading that country's history and language that same night. Your enthusiasm moves people, but you often promise too much. A reminder: before you nod, add up the time and the budget.`,
`On first meeting, people see impatience and drive. At heart you are actually very patient and care about long-term achievement and responsibility. Together, you sprint off the line and then run the whole course steadily. You grab a new project first, then lay out a three-year timeline in perfect detail. Others usually only notice the impulse. One line for you: talk about your long-term plans, so people can see your steadiness too.`,
`You come across as independent, direct and willing to fire the first shot. Deep down you want to do something different that matters to the group. Neither side likes being managed, so you often run ahead of the rules. While the company is still meeting about whether to adopt a new system, you have already tested it for a week and posted your notes in the group chat. Try this: when you are out in front, look back to see whether anyone can keep up.`,
`You enter crisp and decisive, as if nothing scares you. Inside, you are sensitive and imaginative, easily moved by other people's feelings. That contrast often makes people think you are tougher than you are. When a friend goes through a breakup you say, "Stop crying, come on, let's get a late-night snack," then go home and lie awake feeling sad for them. A reminder: you don't always have to cover your softness with action. Saying how you feel is a kind of courage too.`
],
/* Taurus rising */
[
`When people first meet you, you seem mild, unhurried and easy to be around. The real you is eager to start things and prove yourself. The outside is a gentle slope with an engine hidden inside. In a meeting you nod quietly while everyone argues, then speak once at the end, set the direction in one sentence and start executing the next day. Try this: don't hold your drive back too long. Let people know sooner that you already have a plan.`,
`Your front and your core are both Taurus, so what people see is what you are: steady, unhurried, dependable and good at enjoying life. That consistency puts people at ease, and you rarely need to perform. Your friends know that if they invite you to dinner, you will pick the noodle place you have loved for five years and never been let down by. The blind spot is that when change arrives, neither your inside nor your outside wants to move. A reminder: schedule small adventures for yourself, so your life doesn't keep narrowing.`,
`On first meeting you give off a calm, unhurried feeling, like someone who rarely changes their mind. Underneath, you love new ideas and conversation, and your mind never stops. At a dinner you say little and work slowly through your plate, then afterward you send ten links and chat with friends until midnight. The better people know you, the more interesting you get. One line for you: let your curiosity show early; you don't need to wait until you are close to someone to open up.`,
`You look gentle and steady, and people relax the moment they meet you. At heart, home and feelings come first, and you are wonderful at caring for people. The two fit together like an old house with the heater on in winter. When a friend moves, you don't just carry boxes; you quietly bring a pot of soup and a small plant. You are often everyone's safe harbor, and the blind spot is putting yourself last to accommodate others. Try this: put your own needs on the calendar too.`,
`To strangers you seem low-key and steady, not one to grab the spotlight. Your core wants to be seen and to have a stage of its own. The surface is calm, and inside a spotlight is waiting to switch on. You decorate your home with great care and say "Oh, I just threw it together," while hoping friends notice every corner. A reminder: say plainly how much thought you put in, and give people a chance to compliment you.`,
`Your first impression is grounded, reliable and unhurried. What you care about is usefulness and getting things right, always making them a bit better. Two layers of earth energy make you a natural maker. A colleague hands you a messy pile of data and you quietly sort it out, then attach a one-page guide. You rarely make mistakes, yet people often take you for granted. One line for you: let people see what you have finished, and ask out loud for what you are owed.`,
`You come across as gentle, tasteful and pleasant to be around, and inside you value fairness and beauty in relationships. Venus rules both your Ascendant and your Sun, so you know how to put people at ease. When friends fall out, you book a restaurant with a nice atmosphere and help everyone talk it through over dinner. The blind spot is swallowing your own complaints. Try this: keeping the peace doesn't mean staying silent. Now and then, say what you really want.`,
`A Taurus Ascendant sits opposite a Scorpio Sun. On the outside you are gentle, slow to warm up and easy to deal with; inside you are intense and deep, with strong loves and hates. People assume you are easy to negotiate with, and only when they hit your limit do they learn how firm you are. A partner keeps paying late and you politely say "It's fine," while privately keeping a full record of every exchange. A reminder: naming your limit early takes far less energy than silently keeping score.`,
`People see you as steady, unhurried and fond of the familiar. Underneath, you long for faraway places and a bigger world. This contrast often leaves you hesitating between security and freedom. You badly want to backpack through South America, plan it for three years, and still decide to get the mortgage under control first. One line for you: you don't have to leap all at once. Book a short three-day trip and let the explorer inside you breathe.`,
`Both your outside and your nature are practical: you look steady, and inside you want to build results step by step. People sense right away that you can be relied on, and you really don't give up easily. On the day you got your first paycheck, you opened an account just for a home, and ten years later you got the keys. The blind spot is being too serious and playing too little. Try this: on the way to your goals, keep some time that is purely for fun, with nothing to show for it.`,
`On first meeting you seem gentle, rule-abiding, maybe even a little conservative. The ideas in your head are new, though, and often go against the mainstream. At a family gathering you eat quietly until the older relatives bring up a social issue, and then one comment from you leaves the whole table stunned. Your manner reassures; your views surprise. A reminder: share new ideas gradually and pair them with real examples, and people will take them in more easily.`,
`You come across as gentle, steady and approachable. Inside you are perceptive and deeply empathetic, easily moved by music, stories and what other people go through. You are like a couch people sink into. When a friend cries at your place, you don't rush to give advice; you hand over a hot tea and sit with them late into the night. One line for you: you absorb a lot of other people's feelings, so remember to clear them out regularly.`
],
/* Gemini rising */
[
`Your first impression is clever, chatty and quick, and deep down you have an urge to be first and to break new ground. Together, you can talk and charge forward at the same time. In a pitch meeting you warm up the room with a few jokes, then put your own plan on the table the next second and say "I'll own this one." A reminder: your mouth is quick, so leave a little time to think before you commit.`,
`When people first meet you, you seem lively and talkative, able to pick up any topic. The real you values stability and substance and doesn't change your mind easily. A friend pitches you a new investment and you can chat about it excitedly for an hour, then still say, "I'll wait and see." Flexible in speech, settled in mind. Try this: let people know that an enthusiastic chat isn't a yes, and you'll avoid a lot of misunderstandings.`,
`Your Ascendant and Sun are both in Gemini, an unusual match between inside and outside: you look curious and chatty, and you really do want to know everything. People tune in to your wavelength quickly. Waiting for the bus, you strike up a conversation with a stranger about their job, then go home and read up on that industry. You learn fast and switch interests fast. One line for you: keep one long-term project going, to prove you're more than a passing breeze.`,
`You seem relaxed, funny and easy to talk to, yet inside you feel deeply and care most about whether your people feel safe. Many assume nothing gets to you, when in fact you remember everyone's troubles. In the group chat you're the one cracking jokes, and privately you message the friend who has gone quiet lately. A reminder: let people see that you care now and then, instead of wrapping it all in jokes.`,
`Your first impression is smart, witty and approachable, and your core longs to be seen and to have a stage of its own. Your way with words is the tool; shining is the goal. At a party you start a casual story, and by the end the whole table is listening in silence, which you secretly love. Try this: put your talent with words into work you really care about, not just into entertaining everyone.`,
`When people first meet you, you seem nimble and quick-thinking. At heart you value precision and usefulness and like to get things clear. Mercury rules both your Ascendant and your Sun, which makes you a born analyst. A friend asks which vacuum is best; you chat for five minutes, and the next day you send a spec comparison table. A reminder: when your mind won't stop you get anxious, so give yourself some time away from information.`,
`You come across as breezy, friendly and great at conversation, and inside you value relationships, fairness and beauty. Two doses of air energy make you very well liked. At a new colleague's welcome party you get everyone talking quickly, notice who is being left out, and steer the conversation their way. The blind spot is saying things you don't mean to keep the mood up. One line for you: on things that matter, state your own position first.`,
`You seem talkative, as if you're happy to share anything. The real you is deep and private, with a lot you never say. People think they know you well when they've only talked about surface things. At a party you tell a string of funny stories, then get home and realize you didn't say one honest thing about yourself. Try this: find one or two people you trust and let them see the deeper you.`,
`A Gemini Ascendant sits opposite a Sagittarius Sun. You come across as inquisitive and full of information, yet what you pursue deep down is bigger meaning and faraway places. You can spend a whole lunch talking news with coworkers, while what you really want is to study abroad and understand how the world works. You can hold both the details and the big picture. A reminder: don't let scraps of information drown out your larger direction.`,
`When people first meet you, you seem young, clever and a bit mischievous. At heart you are practical, with long-range plans and a strong sense of responsibility. At work you're seen as the office comedian, while you quietly beat your targets every quarter. Light outside, serious inside, so people tend to underestimate you. One line for you: at key moments, put the jokes away and let people feel your weight.`,
`You come across as smart, friendly and quick, and deep down you hold your own ideals and want to do things differently. Two doses of air energy make you great at trading ideas. A friend complains about parking in the neighborhood, and by the end of the chat you've started an online group and written an improvement proposal. Try this: when you have lots of ideas, pick one and actually carry it out, so the change becomes visible.`,
`You seem talkative, quick and easy to get along with, yet inside you are sensitive and subtle, often living in your own imagination. People think you're rational, but most of your decisions come from feeling. In a discussion you make a perfectly logical case, then change your mind because a single image moved you. A reminder: accept that you are someone who decides with the heart; you don't need to justify everything.`
],
/* Cancer rising */
[
`Your first impression is gentle, warm, perhaps a little shy. Deep down there's a fire that wants to start things and win, and only people close to you know how driven you are. In a new place you quietly watch for a few days, and once you feel safe you suddenly propose a bold plan that startles everyone. A reminder: gentleness and courage don't conflict, so let people see your ambition sooner.`,
`When people first meet you, you seem warm, approachable and caring, and your core values stability and quality of life. Together they feel very much like home. When friends visit, you bring out pickles you made yourself and a freshly brewed pot of tea, and nobody wants to leave. You give people a strong sense of security. Try this: don't pour all your energy into looking after home and others; put some money aside for your own dreams.`,
`You seem gentle and attentive, the type who watches before coming closer. Underneath you're full of curiosity and want to learn and talk about everything. When you first join a club you barely speak, and once you're comfortable you become the one who always has a topic and loves sharing new things. Friends often say, "You're so funny once we get to know you." One line for you: you don't need to hide so much at first meeting; your fun side deserves to be found early.`,
`Your Ascendant and Sun are both in Cancer, so your outside and your nature are equally warm and feeling-driven. What people sense at first glance is the real you. When a coworker calls in sick, you're the first to offer to cover their shift and drop off some medicine on the way. That consistency earns trust quickly, though your moods are written all over your face. A reminder: set boundaries for yourself. You don't have to look after everyone.`,
`You come across as soft, kind and not one to talk over others, yet your core longs to be seen, to create and to be the lead in your own life. At a family gathering you quietly cook an entire spread, secretly hoping someone will say, "You made this? Amazing." Caring on the outside, wanting to shine on the inside. Try this: don't stay backstage forever. Step into the light now and then.`,
`When people first meet you, you seem considerate and easy to be with. Inside you're practical and careful, always wanting things more orderly. At a group dinner you check whether everyone has had enough, while quietly noting who paid what, and afterward you settle up line by line. You're good at caring and good at organizing. One line for you: don't be so hard on yourself inside; let things be a little imperfect.`,
`You seem gentle and sensitive, quick to understand how others feel, and at heart you seek harmony and fairness in relationships. Together, they make you a natural peacemaker. When your family argues, you calm the most upset person first, then find a moment for both sides to talk it out. The blind spot is putting other people's needs first. A reminder: in any relationship, your discomfort also deserves fair treatment.`,
`Your first impression is soft, kind and a little reserved. Inside you're deep and fierce, and you love and hate completely. Two doses of water energy give you sharp intuition. A new friend chats with you, and while you smile and listen, you've already sensed which sentence didn't ring true. Watching first is how you protect yourself. Try this: with people who've earned it, lower your guard and let them see how deeply you feel.`,
`You come across as warm, sentimental and devoted to home. Underneath, you long for freedom, adventure far away and a search for life's meaning. That contrast often pulls you in two directions. You're happy working in another city, yet every holiday you feel guilty, afraid your family thinks you don't want to come back. One line for you: carry home with you. You can have roots and wings at the same time.`,
`A Cancer Ascendant sits opposite a Capricorn Sun. You look gentle and approachable, yet inside you're ambitious and value achievement and responsibility. People think you're easygoing at first, and only after working with you do they see how clear your goals are. You'll warmly ask how everyone on the team is doing, and you won't move a deadline by a single day. A reminder: let people know both your warmth and your strictness are real, so no one thinks you're two-faced.`,
`When people first meet you, you seem gentle and homey. Deep down you're very independent, value ideals and freedom, and don't like being tied down by emotions. You're great at looking after friends, but once someone expects instant replies every day, you start wanting to escape. Closeness and independence live in you side by side. Try this: say early in a relationship how much space you need.`,
`Your first impression is soft and warm, and people want to come closer. Inside you're full of empathy and imagination, quick to feel what others feel. Two doses of water energy in agreement make you a born listener. On the subway you see someone crying quietly, hesitate over whether to offer a tissue, and keep thinking about them long after you get off. One line for you: sensitivity is a gift, but remember to build yourself a breakwater.`
],
/* Leo rising */
[
`You have presence the moment you walk in: generous, warm and confident. Deep down you have a drive to start things and take on challenges. Two fires make you a natural leader. At the company's year-end party you don't just perform; you invent a new game on the spot and pull everyone into it. You're great at lighting up a room, and you can also steal other people's light. A reminder: give others room to shine. Your own glow won't get any smaller.`,
`When people first meet you, you seem commanding, generous and image-conscious. Underneath you're grounded and value stability and real worth. You dress sharp when you go out, yet compare prices carefully when you shop and pick the most durable option. Shine on the outside, substance on the inside. Try this: don't rely only on appearances to prove yourself. Your reliability is your most valuable quality.`,
`Your first impression is confident and warm, with real stage presence. Deep down you're curious, love learning and enjoy exchanging ideas. You run a book club with total command, but what truly makes you happy is the last half hour, when everyone tosses ideas around and something new sparks. You make people want to hear you talk. One line for you: don't chase attention alone; go deep on one or two subjects and you'll carry more weight.`,
`You look generous, bright and full of confidence, yet inside you're soft and care most about family and the people closest to you. People think nothing scares you, but you need to belong. You speak with ease on stage, and the first thing you do when you step off is call home to ask whether they caught the livestream. A reminder: let the people close to you know that behind your confidence, you need their hugs too.`,
`Your Ascendant and Sun are both in Leo, and your outside shines as brightly as your nature; inside, you truly want to glow and create. People can tell who you are at a glance, and you never planned to hide it. For your birthday you plan the whole party yourself, from invitations to playlist, all in your style. Your energy is contagious. Try this: your warmth moves people even more than your shine, so remember to light up those around you.`,
`When people first meet you, you seem commanding, at ease and confident. Your core is cautious, always checking details and aiming for polish. You look effortless giving a presentation, when the night before you adjusted the font size on every slide three times. Effortless outside, painstaking inside. One line for you: talk about how you prepared. It will impress people even more.`,
`You come across as bright, generous and charming, and inside you value relationships, beauty and fairness. At parties you're popular, but what you care about most is that everyone has fun and nobody gets left on the sidelines. You know how to shine and how to look after the mood. A reminder: don't drop your position just to be liked by everyone. Your opinion matters too.`,
`Your first impression is like a host: warm, outgoing and commanding. Underneath you're deep and perceptive, and you don't let people see through you easily. At a party you laugh and chat, while noticing exactly how everyone is connected and what they want. People think you're easy to get close to, when your trust is actually hard to earn. Try this: around people who feel safe, let go of control, and you'll feel much lighter.`,
`You come across as enthusiastic, generous and full of energy, and deep down you long for freedom and keep wanting to explore new places and ideas. Two fires make you very contagious. A friend casually mentions camping, and you've already mapped the route and rounded up ten people. Your optimism gets people moving. One line for you: alongside the enthusiasm, watch the details and the budget, so a good plan doesn't turn into a burden.`,
`When people first meet you, you seem confident and leaderly. Your core is rigorous and patient, aiming for long-term achievement. You carry yourself with authority in meetings, then stay behind after work, revising next quarter's plan line by line until it's right. Your shine is backed by real ability. A reminder: you don't have to carry everything on your own shoulders. Trusting your team is also leadership.`,
`A Leo Ascendant sits opposite an Aquarius Sun. You look warm and confident and enjoy attention, yet inside you value independence and ideals and don't much care about conventional standards. You're eye-catching on stage, but what you really want to push forward is a community project that gets more people involved. The surface wants a stage; the inside wants meaning. Try this: let the stage serve your ideals, and the two sides stop pulling against each other.`,
`Your first impression is bright, warm and self-assured, yet inside you're sensitive and romantic, easily swayed by mood and atmosphere. On stage you're composed, but if one person in the audience frowns, you'll replay it in your head for a long time. Sturdy outside, delicate inside. One line for you: other people's reactions are not your worth. Hold both applause and criticism a little more lightly.`
],
/* Virgo rising */
[
`Your first impression is careful, polite and well organized, yet deep down you're in a hurry to start things and prove yourself. When you join a new team, you work quietly and learn the processes first; once you're comfortable, you suddenly propose a reform and act on it right away. People are often startled by the switch. A reminder: don't let over-preparation block action. Your drive deserves to get on the field sooner.`,
`When people first meet you, you seem neat, attentive and orderly. Underneath you value stability and concrete returns. Two doses of earth energy make you very good at getting things done well. You don't just track amounts in your budget; you categorize every expense, and over ten years your savings grow steadily. People feel safe with you. Try this: beyond security, treat yourself now and then, and life gets more flavor.`,
`You seem quiet, careful and observant, yet deep down you're full of curiosity and want to learn many things and talk with many people. Mercury rules both your Ascendant and your Sun, so your mind is always busy. At a book club you barely speak, but your notes are the most detailed, and at home you keep discussing online late into the night. One line for you: you don't need to wait until you're perfectly prepared to speak. Your ideas are valuable.`,
`When people first meet you, you seem courteous and efficient. Your core is deeply feeling, caring most about family and familiar people. At work your reports are flawless, and after hours you hurry home to pack lunches for your family for the next day. You show love through details. A reminder: before you look after others, let yourself rest properly. Not everything needs full marks.`,
`You come across as low-key and careful, not one to seek the limelight, yet inside you long to be seen and to have your own work and stage. You quietly make the team project polished, while really hoping your manager singles you out at the monthly meeting. Stepping back outside, wanting to stand in front inside. Try this: don't just wait to be discovered. Show your results yourself; you deserve recognition.`,
`Your Ascendant and Sun are both in Virgo, so what people see is the real you: attentive, practical and keen to get things right. Others quickly hand you the details. A coworker is about to submit a proposal, and at a glance you spot three typos and a miscalculated number. That consistency makes you dependable, and also hard on yourself. One line for you: allow yourself to stop at eighty percent sometimes. That's already very good.`,
`When people first meet you, you seem measured, low-key and polite. Deep down you value harmony and beauty in relationships. As head usher at a friend's wedding, you arrange the seating so everyone is comfortable, having considered exactly who doesn't get along with whom. You trade care for peace. A reminder: don't swallow every opinion just to avoid conflict. Say what you need, in the right measure.`,
`You seem low-key, measured and thorough, yet underneath you're deep and intense and want to see to the heart of things. At work you look like a quiet executor, but when someone tries to bury a problem, you silently lay all the data on the table. Only then do people realize how deeply you see. Try this: insight used to help people is more powerful than insight used to guard against them.`,
`When people first meet you, you seem proper and detail-focused. Your core longs for freedom, adventure and the meaning of life. Before a trip abroad you plan the itinerary to the minute, then once you arrive you often change plans on a whim and head to a small town that wasn't on the list. One line for you: let your plan be a safety net, not a cage, and you'll enjoy yourself more.`,
`Your first impression is careful, reliable and organized, and deep down you have long-term goals and a strong sense of duty. Two doses of earth energy make you extremely capable. You take over a chaotic department, smooth out its processes in three months, and within six months the results clearly improve. The blind spot is rarely letting yourself breathe. A reminder: schedule rest too. It is just as much a part of long-term success.`,
`When people first meet you, you seem rule-abiding and cautious, maybe a little conservative. Deep down your ideas are fresh, and you like breaking out of the box. At work you follow procedure and never miss a deadline, while the proposals you write on the side often make your manager say, "That's a bold idea." Step by step on the outside, unconventional within. Try this: your attention to detail is exactly what helps new ideas land, so don't worry about being called unusual.`,
`A Virgo Ascendant sits opposite a Pisces Sun. You look rational and organized, yet inside you're emotional and imaginative, often led by your feelings. By day your task list is in perfect order; at night an old song can bring back a memory and move you to tears. The two sides seem contradictory but actually complete each other. One line for you: let your carefulness build scaffolding for your dreams, and the two can work together instead of cancelling each other out.`
],
/* Libra rising */
[
`A Libra Ascendant sits opposite an Aries Sun. Your first impression is graceful, diplomatic and easy to talk to, yet underneath you want to charge ahead, win and be your own boss. In a discussion you smile and say "Anything works for me," and once everyone has spoken, your proposal turns out to be the most decisive. A reminder: you don't always need to wrap your ambition in politeness. Be a little more direct and people will trust you more.`,
`When people first meet you, you seem courteous, tasteful and easy to be with. Deep down you value stability and real, tangible pleasures. Venus rules both your Ascendant and your Sun, so you understand the beauty of everyday life. Your studio apartment is small, but every corner is so comfortable that friends never want to leave. Try this: don't hold in your complaints too long to keep the peace. Say them gently and that's enough.`,
`You come across as friendly, well-mannered and a good talker, and underneath you're curious and love exchanging fresh ideas. Two doses of air energy make you exceptionally well liked. At a networking event you chat a little with every table and connect two strangers along the way. You're great at linking people. One line for you: beyond meeting lots of people, spend time going deep with a few close friends.`,
`Your first impression is gentle, polished and attentive to the mood. Your core is deeply feeling, caring most about home and the people closest to you. At work you always greet people with a smile, while at home a casual remark from family can hurt you for a long time. Under your easy manner is a sensitive heart. A reminder: let the people close to you know you need looking after too. You don't have to be the nice one all the time.`,
`You come across as graceful, generous and charming, and deep down you long to be seen and to create work of your own. Friends often ask your opinion on outfits, so you start a style account and get better and better at it. Your outward sense of beauty and your inner urge to express fit together well. Try this: boldly turn your taste into a stage, instead of only advising others.`,
`When people first meet you, you seem friendly and agreeable. Underneath you're meticulous with high standards, always wanting things done better. At dinner you smile and say "It's delicious," then go home and mentally list three things the restaurant could improve. Smooth outside, exacting inside. One line for you: save your attention to detail for what you really care about; not everything needs to be perfect.`,
`Your Ascendant and Sun are both in Libra, so your outside and your nature equally value harmony, beauty and fairness, and your first impression is your true colors. When friends argue, you naturally step into the middle and make both sides feel understood. People love being around you, yet you often give up your own opinion to keep the peace. A reminder: when you make decisions, first ask yourself what you want, then think about others.`,
`You seem gentle, courteous and easy to get along with, yet deep down you're intense, with strong loves and hates, and it's hard for you to truly open up. At a party you chat happily with everyone, but only one or two people actually know what's on your mind. Outside is an open window; inside is a locked door. Try this: find someone you can trust and let them see all of you.`,
`When people first meet you, you seem graceful, easygoing and socially skilled. Your core longs for freedom and a bigger world. You're well liked at work, but every year you carve out a long vacation to backpack alone through an unfamiliar country. The two sides can actually help each other. One line for you: your social ease will win you good friends on the road, and what you see on the road will give you even more to talk about.`,
`Your first impression is gentle, polite and easy to communicate with. Deep down you have strong ambition and a sense of responsibility. At the negotiating table you keep smiling, yet you don't give an inch on terms, and you end up signing the deal that's best for your company. Opponents often underestimate you. A reminder: let people know your gentleness doesn't mean you're a pushover. Your firmness has principles behind it.`,
`When people first meet you, you seem friendly and easy to be with. Underneath you're independent and forward-thinking, and you put ideals ahead of social niceties. Two doses of air energy make you great at discussing ideas. At a gathering you chat pleasantly with everyone, but when you meet values you don't share, you voice disagreement gently and firmly. Try this: friendliness and independence can coexist; you don't have to give up your ideals to keep the peace.`,
`You come across as graceful, gentle and approachable, and inside you're sensitive and imaginative, easily moved by beautiful things. In a museum you can stand in front of one painting for twenty minutes, then go home and write a full page about how it made you feel. Your outward taste and inner sensitivity lift each other up. One line for you: try expressing these feelings through creative work instead of keeping them all inside.`
],
/* Scorpio rising */
[
`Your first impression is mysterious, distant, with a deep gaze. Deep down you're direct and impulsive, wanting to start things and win. In a meeting you say nothing for a long while, leaving people guessing, then make your move at just the right moment and turn things around with one sentence. Your Ascendant and Sun are both linked to Mars, so your willpower is strong. A reminder: you don't always have to hide your drive. Letting people know what you think will spare you a lot of misunderstanding.`,
`A Scorpio Ascendant sits opposite a Taurus Sun. You look mysterious, intense and hard to approach, yet deep down you want a calm, simple life. People assume you're difficult, and once they know you they find your greatest joy is simmering a pot of soup at home on the weekend and rewatching an old movie. Try this: let people know you're actually easy to be around; you just need time to build trust.`,
`When people first meet you, you seem deep, guarded and hard to get close to. Underneath, you're curious and chatty and want to know everything. In a new place you study everyone first, and once you're comfortable you become the one who always hears the news first and loves passing on fun stories. The contrast makes friends feel you have real layers. One line for you: you don't need to hide so deep at first; your fun side deserves to be seen sooner.`,
`Your first impression is a little cool and distant. Your core is soft and deeply feeling, caring most about family and the people you're close to. Two doses of water energy give you strong intuition. You're guarded with strangers, but with your family you're endlessly attentive, sensing even the needs they haven't voiced. A reminder: give others a chance to come closer. Your warmth deserves to be known by more people.`,
`You come across as intense, mysterious and magnetic, yet deep down you long to be seen and to be the lead in your own life. At a party you don't say much, but people can't help noticing you, and secretly you enjoy that attention. Reserved outside, wanting to shine inside. Try this: you don't need mystery to draw people in. Show your talent directly and you'll feel more at ease.`,
`When people first meet you, you seem deep, perceptive and hard to read. Underneath you're meticulous and practical and like to get things right. You spot the trap in a contract at a glance, then list each problem clause by clause and attach suggested changes. Seeing deep plus working carefully makes you very hard to fool. One line for you: soften your tone when you explain, and people will accept your analysis more easily.`,
`You seem mysterious, intense and guarded, yet deep down you value harmony, beauty and fairness in relationships. With strangers you're cool, but among close friends you're the best at settling disputes and keeping the mood good. Your first impression and the real you are very different. A reminder: let your gentle side show sooner, so your first impression doesn't scare off people who could become good friends.`,
`Your Ascendant and Sun are both in Scorpio, so your outside and your nature are equally deep and intense: you don't take a stance lightly, and once you commit you give it everything. Your first impression is your true colors. When you decide to learn something, you research it more thoroughly than the teacher. People find you hard to approach, and you don't plan to please everyone. Try this: lower your guard now and then, and let people you trust share some of your weight.`,
`When people first meet you, you seem cautious, deep and distant. Your core is cheerful and adventurous, longing for freedom and meaning. On first meeting you say little; once people know you, they find you love travel and light up when you talk about faraway places. Outside is a closed door; inside is open grassland. One line for you: let your enthusiasm show sooner, and people will get to know you faster.`,
`Your first impression is intense, composed and authoritative, and deep down you have long-term goals and a strong sense of responsibility. At work you don't talk much, but everyone knows anything given to you gets done, and you're already setting up the next move. You're a quiet strategist. A reminder: don't carry all the pressure alone. When the time is right, let people you trust share it.`,
`When people first meet you, you seem mysterious and guarded. Underneath you're independent and friendly, and you value ideals and community. You're cool with strangers, but in a volunteer group you're the most committed and the most willing to speak up for everyone. The distance in your first impression is just a protective layer. Try this: let people see the ideals you care about, and they'll understand what your coolness is about.`,
`Your first impression is deep, mysterious and a little hard to pin down, yet inside you're gentle and sensitive, easily touched by other people's feelings. Two doses of water energy make your intuition very accurate. Before a friend says a word, you sense something is wrong and quietly sit with them all evening. One line for you: you absorb a lot of emotion, so keep time alone to clear it out.`
],
/* Sagittarius rising */
[
`Your first impression is cheerful, warm and candid, and deep down you're driven to start things and get there first. Two fires fill you with energy. A friend suggests learning to scuba dive, and you don't just agree; you round up five people and book the course on the spot. It's hard not to get swept along by you. A reminder: alongside the enthusiasm, watch the details. Say yes to too much and something will slip.`,
`When people first meet you, you seem easygoing, optimistic and adventurous. Underneath, you value stability and practicality. You look completely spontaneous when you travel, when in fact the lodging and budget were sorted long ago. Free on the outside, grounded inside. People find you fun and reassuring at once. Try this: let people see your steadiness, and they'll feel better trusting you with important things.`,
`A Sagittarius Ascendant sits opposite a Gemini Sun. You come across as someone who loves big ideas and looks far ahead, yet deep down you love collecting bits of information and talking with everyone. At a party you discuss the philosophy of life; at home you binge shows and scroll the news until midnight. You love both the big picture and the small details. One line for you: try shaping all that information into your own point of view, and you'll be far more persuasive.`,
`You come across as cheerful, open-handed and freedom-loving, yet deep down you feel deeply and care most about family and belonging. You're always heading out and traveling, but wherever you go you buy gifts and wonder whether your family will like them. Your outside is flying; your heart is tied to home. A reminder: let your family know that leaving isn't running away. You're taking them along to see the world.`,
`When people first meet you, you seem warm, funny and full of energy. Your core longs to be seen and to create work of its own. Two fires give you a lot of charm. When you share travel photos, you always have a great story that keeps friends hooked. Try this: your stories are moving, so try writing them down or turning them into a project.`,
`You seem easygoing, optimistic and unbothered by details, yet underneath you're careful and practical, always checking for anything missed. You say "Whatever's fine," then quietly check your packing list twice before leaving. People think you're spontaneous, but you plan a lot. One line for you: let yourself truly relax once, without having everything prepared.`,
`Your first impression is cheerful, friendly and easy to be with, and deep down you value harmony, beauty and fairness in relationships. On a group tour you chat easily with strangers and often settle small disputes among the group so everyone has a good time. Wherever you go, you make friends. A reminder: you're great at looking after the mood, but don't forget to say what you really need in your relationships.`,
`You come across as cheerful, frank and approachable, yet underneath you're deep and intense, with much you rarely say. At a party you laugh the loudest, while your real worries come out only late at night with the person you trust most. Sunny outside, a deep sea within. Try this: find people you can trust and let them see your depths. You'll feel much lighter.`,
`Your Ascendant and Sun are both in Sagittarius, so your outside and your nature are equally cheerful, drawn to faraway places and concerned with living a meaningful life. Your first impression is your true colors. You say you'll do a long bike trip across the country, set off the next day and make a bunch of new friends along the way. Your optimism is contagious, but you often say yes too fast. One line for you: think before you agree. Your freedom needs a little planning.`,
`When people first meet you, you seem optimistic, easygoing and adventurous. Deep down you're rigorous and practical, with long-term goals. You always look relaxed, when in fact you mapped out the next five years of your career long ago, with every step planned. Ease is the surface; seriousness is the foundation. A reminder: let people see how serious you are, and they'll trust your judgment more.`,
`You come across as warm, cheerful and open-minded, and deep down you're independent and forward-thinking, valuing ideals and community. Your posts sharing your views are contagious, and you can rally a group of like-minded people to act together. Your outward warmth clears a path for your inner ideals. Try this: look after your energy, and don't keep burning until there's nothing left.`,
`When people first meet you, you seem cheerful, optimistic and adventurous. Your core is sensitive and romantic, easily moved by emotions and beautiful scenery. On a trip, the sight of the sea can suddenly make you go quiet and write a poem in your head. Under the lively surface is a quiet heart. One line for you: record the moments that move you. They're your treasure.`
],
/* Capricorn rising */
[
`Your first impression is steady, serious and dependable, yet deep down you're in a hurry to start something and prove yourself. In meetings you're measured, while you've long wanted to start your own business and are just waiting for the right moment. Outside, you're on the brakes; inside, you're on the gas. A reminder: your steadiness can give your drive direction, so don't wait until everything is perfect to act.`,
`When people first meet you, you seem mature, reliable and a little reserved. Underneath you value stability and quality of life. Two doses of earth energy make you exceptionally grounded. You started saving young and investing in your skills, and ten years later you're living the life you wanted. Try this: while you work hard, keep time to enjoy the present. Don't wait for "someday."`,
`You seem mature, serious and rarely smiling, yet deep down you're curious, chatty and fond of fresh ideas. At work you're seen as the serious senior colleague, and after hours you're the one in the group chat sharing the most dad jokes and interesting finds. The contrast delights people who know you. One line for you: let your coworkers see your lighter side, and they'll be more willing to come closer.`,
`A Capricorn Ascendant sits opposite a Cancer Sun. You come across as calm, capable and distant, yet deep down you're soft and deeply feeling, caring most about family. At work you're decisive and strict, but one call from family and you drop everything to rush home. A reminder: let your coworkers glimpse your tenderness now and then, and they'll trust you more.`,
`When people first meet you, you seem composed, low-key and measured. Your core longs to be seen and to create achievements of its own. You work diligently, secretly hoping that one day you'll stand on a stage and receive everyone's applause. Try this: don't just rely on hard work and wait to be discovered. Go after the stage you've earned.`,
`Your first impression is mature, careful and dependable, and deep down you're meticulous and practical, always wanting to do things as well as possible. Two doses of earth energy make you extremely capable. Reports that pass through your hands never have errors, down to the punctuation. Your manager relaxes; you're often too hard on yourself. One line for you: allow yourself the occasional mistake. It won't make you any less reliable.`,
`When people first meet you, you seem serious, measured and not easy to get close to. Underneath you value harmony and beauty and hope to get along well with everyone. In meetings you're all business, yet privately you notice who's being left out and quietly speak up for them. Beneath the distance is real thoughtfulness. A reminder: let people see your gentleness, and you'll be more popular than you think.`,
`You seem composed and authoritative, someone people respect, and deep down you're intense and want to see to the essence of things. At work you don't say much, but each time you speak you go straight to the heart of the problem, and everyone has to take it seriously. You're the kind of person who carries weight without raising your voice. Try this: put your insight into collaboration, and it will achieve more than working alone.`,
`When people first meet you, you seem mature, steady, maybe a bit conservative. Deep down you long for freedom and a bigger world to explore. You're diligent at work, while privately you keep planning to study abroad or live overseas for a while someday. One line for you: put the dream into your long-term plan. Your steadiness is exactly what can make it happen.`,
`Your Ascendant and Sun are both in Capricorn, so your outside and your nature are equally mature, practical and responsible. Your first impression is your true colors. Even as a student you knew what you wanted and moved toward it step by step, rarely straying. People trust you deeply, and they also find you too serious. A reminder: relax now and then, and really enjoy what your hard work has earned.`,
`Your first impression is mature, reliable and rule-abiding. Underneath you're independent and forward-thinking, wanting to break the mold. At work you go by the book, while the new system you push for on the side lifts your whole department's efficiency. People accept your new ideas because they trust your steadiness. Try this: put your ideas forward boldly. Your reliability is the best endorsement they could have.`,
`When people first meet you, you seem calm, rational and distant. Deep down you're sensitive, gentle and imaginative. At work you're decisive and efficient, and at home a movie can make you cry until you can't stop. Outside is a solid wall; inside is a garden. One line for you: let the people close to you see your softness. You don't have to hold it together all the time.`
],
/* Aquarius rising */
[
`Your first impression is friendly, original and a bit hard to pin down, and deep down you have a drive to start things and win. On a team you always bring the unusual idea, and you're the first to run the experiment. Cool outside, fiery in action. A reminder: your creativity and drive are both strong, so remember to bring the team with you instead of racing too far ahead alone.`,
`When people first meet you, you seem progressive, independent and unpredictable. Underneath you value stability and practicality. Your style is full of personality, yet you manage money very conservatively, spending every dollar where it counts. Unconventional outside, feet on the ground inside. Try this: let your stability be the foundation for your creativity; the two can back each other up.`,
`You seem friendly, smart and open-minded, and deep down you're curious, love exchanging ideas and enjoy anything new. Two doses of air energy make your mind especially agile. You can talk with people from every background and link knowledge across fields into combinations no one else saw. One line for you: when you have lots of ideas, pick one and go deep, and the results will follow.`,
`When people first meet you, you seem independent, cool and a little detached. Your core is deeply feeling, caring most about home and the people you're close to. Out in the world you're rational; at home you're the most caring and nostalgic one, unable to throw away even your childhood toys. A reminder: let your friends see your warmth too, and they'll be more willing to come closer.`,
`An Aquarius Ascendant sits opposite a Leo Sun. You come across as original, cool and unconcerned with what others think, yet deep down you long to be seen and appreciated. You say you don't care about likes, but every time you post you sneak several looks. Try this: admit that you want to be seen. Your uniqueness won't lose a thing.`,
`Your first impression is friendly, independent and forward-thinking, and deep down you're careful and practical, always wanting to do things as well as possible. The innovative plans you propose always come with detailed steps and timelines, which makes them hard to argue with. New ideas plus strong execution is your strength. One line for you: your attention to detail makes your creativity more credible, so don't worry about being called fussy.`,
`When people first meet you, you seem friendly, original and open-minded. Underneath you value harmony and fairness in relationships. Two doses of air energy make you great at connecting with people. At club meetings you always get people who disagree to talk properly, and everyone feels respected. A reminder: alongside looking after others, state your own position too.`,
`Your first impression is cool, independent and a little detached, yet deep down you're intense, with strong loves and hates. At a party you look like an onlooker, but once you've decided someone is your friend, you give wholeheartedly, even looking after their family. Try this: let people know there's deep feeling under your calm, and they'll treasure you more.`,
`When people first meet you, you seem friendly, progressive and freedom-loving. Your core longs for faraway places and seeks life's meaning. The two fit well. You often travel alone, then come back and write up your observations about different cultures and share them with friends late into the night. One line for you: your perspective is valuable. Share it more widely and it will spark something in a lot of people.`,
`You seem original, progressive and unconventional, yet underneath you're practical and responsible, pursuing long-term achievement. Your ideas often surprise people, and you also plan step by step to turn them into visible results. Your Ascendant and Sun are both linked to Saturn, so you can endure more hardship than you appear to. A reminder: innovation plus real ability can do big things. Don't underestimate yourself.`,
`Your Ascendant and Sun are both in Aquarius, so your outside and your nature are equally independent, forward-thinking and driven by ideals. Your first impression is your true colors. You never follow trends, always go your own way, and often lead a group of people to change with you. People think you're cool, and also a little hard to approach. Try this: let people come closer now and then. Your friendliness deserves to be seen.`,
`When people first meet you, you seem cool, independent and a little detached. Deep down you're sensitive and gentle, easily moved by emotion. In a group you look rational, but when you see someone who needs help, you're the first to quietly reach out. Calm is the coat; compassion is the heart. One line for you: let people see your empathy, and your influence will grow.`
],
/* Pisces rising */
[
`Your first impression is gentle, dreamy and agreeable, yet deep down you have a drive to start things and win. You seem easy to negotiate with, but once you decide to do something, nobody can stop you. Water outside, fire inside. A reminder: let people know your resolve sooner, so they don't mistake you for someone easily talked around.`,
`When people first meet you, you seem gentle, romantic and a little elusive. Underneath you value stability and practicality. You look like an artist, yet you're very good with money and have more savings than most people your age. Your outer softness and inner groundedness fit together well. Try this: let people see your stability, and they'll feel better leaning on you.`,
`You seem gentle, sensitive and a little mysterious, and deep down you're curious, love exchanging ideas and enjoy anything new. At a gathering you listen quietly, then go home and debate eagerly online, writing post after post. Quiet outside, buzzing mind inside. One line for you: let people see your curiosity, and you'll find more kindred spirits.`,
`When people first meet you, you seem gentle, approachable and empathetic, and deep down you feel deeply, caring most about home and the people closest to you. Two doses of water energy make you extremely considerate. The night a friend goes through a breakup, you're the first one downstairs at their place, and you remember which bakery's dessert they love most. A reminder: besides looking after others, remember to look after yourself.`,
`Your first impression is gentle, dreamy and artistic, yet your core longs to be seen and to create work of its own. You often draw or write quietly on your own, secretly hoping someone will appreciate it. Shy outside, wanting to shine inside. Try this: share your work boldly. Your talent deserves to be seen.`,
`A Pisces Ascendant sits opposite a Virgo Sun. You look gentle, easygoing and a little scatterbrained, yet deep down you're careful and practical, always wanting to get things right. People think you're spontaneous, when in fact you've thought through every detail and just haven't said so. One line for you: let people see your organization, and they'll trust you more.`,
`When people first meet you, you seem gentle, graceful and easy to be with, and deep down you value harmony, beauty and fairness. In a group you always make everyone feel looked after, and people love being around you. Your outside and inside are both mild, but you tend to shortchange yourself. A reminder: besides looking after others, say what you need too.`,
`Your first impression is gentle, mysterious and empathetic, yet underneath you're deep and intense, with strong loves and hates. Two doses of water energy make your intuition very accurate. You can read other people's worries at a glance, but you rarely voice your own. Try this: find people you can trust and let them see your depths.`,
`When people first meet you, you seem gentle, dreamy and agreeable. Your core longs for freedom and seeks life's meaning. Your Ascendant and Sun are both linked to Jupiter, so you naturally believe in the good. You look easygoing, while privately you keep planning to go somewhere far away and explore different cultures and beliefs. One line for you: put your dream into action. Your gentleness will make the journey richer.`,
`You seem gentle, easygoing and a little dreamy, yet deep down you're practical and responsible, aiming for long-term achievement. People think you're easy to persuade, but at work you're very professional, with clear goals and never a missed deadline. A reminder: let people see your ability, and they'll respect your opinions more.`,
`When people first meet you, you seem gentle, sensitive and approachable. Underneath you're independent and forward-thinking, valuing ideals. You seem easy to talk around, but when you see someone bullied or treated unfairly, you step up and hold to your principles. Try this: let people know your gentleness has limits, and they'll respect you more.`,
`Your Ascendant and Sun are both in Pisces, so your outside and your nature are equally gentle, sensitive and imaginative. Your first impression is your true colors. Music and stories move you easily, and you feel other people's emotions so well that you often notice someone's sadness before they do. People find you very approachable, and you can also get swept under by feelings. One line for you: build boundaries for yourself to protect your sensitivity.`
]
]
};
