/* Human Design story content (English): profiles, lines, type x authority, channels, centers */
globalThis.STORY_HD_EN = {
 profiles: {
  '1/3': {
   title: `The explorer who studies the map, then walks every step`,
   summary: `Your life runs on "research first, then experiment." Your 1st line wants a solid foundation and feels uneasy whenever the information is thin; your 3rd line wants you on the ground, testing with your own body whether the books were right. You are often the one who looked up the most and also fell the hardest. In the end, what you can do is something no book and no other person could have handed you.`,
   loop: `You study until you feel confident, then act, and the first try hits a hole the books never mentioned. Afterward you go back and fill in the research, and the foundation gets a little thicker. After a few rounds you become someone who knows the theory and has taken the falls, so people naturally come to you with their tricky problems.`,
   love: `When you like someone, you might scroll back three years through their social media to understand who they are. Once you are actually together, though, you find that a lot can only be learned by bumping into it, and it takes a few arguments to learn each other's limits. What you need is security, not a perfect partner. A reminder: don't decide "this relationship is broken" after one collision. That may just be you gathering real data.`,
   work: `Say you want to open a café. You read every book on running one and work out the costs, then spend six months working at someone else's café to see firsthand what it looks like when the wrong beans are ordered, the machine breaks down or customers complain. When you finally open your own, you are steadier than others starting out at the same time, because you have already stepped in every hole you could. Bosses trust people like you most: you have the evidence, and you have actually done it.`,
   tips: [`Research is your safety net, but set yourself a point where you say "that's enough information," then go and try it.`, `When an experiment fails, record it as "this path doesn't work," not as proof that "I'm not good enough."`, `Your foundation is solid. You don't need to skip the research step just because others move faster.`]
  },
  '1/4': {
   title: `The one who builds a solid house, then shares it with friends`,
   summary: `Your life rests on two things: solid knowledge and a circle of people who trust you. Your 1st line makes sure you understand the ground before you move; your 4th line brings almost all your opportunities through people you know. You don't get ahead because strangers discover you, but because everyone who knows you knows you're reliable. When your foundation is steady, your network is steady, and when your network is steady, the way opens.`,
   loop: `You study a field thoroughly and naturally become the person in your circle everyone says to ask about it. Friends introduce you to more people, opportunities follow, and every new opportunity pushes you back to deepen your knowledge. Your influence spreads outward one ring at a time.`,
   love: `Your relationships often grow out of friendship or start with an introduction from a friend. Strangers on dating apps rarely put you at ease, because you can't get a sense of who they really are. Once you are in a relationship you are loyal, but you need certainty, and a partner who runs hot and cold will unsettle you. A reminder: telling them clearly what kind of stability you need works better than silently watching whether they provide it.`,
   work: `You rarely land a good job by sending out a résumé. More often a former colleague says, "We're hiring, want to join us?" Your value on a team is that people know what you say has been checked and has a basis. When you want to change direction, put the word out in your existing network first. It works far better than firing off applications to job boards on your own. As a 4th line, find your next place to land before you leave the old one.`,
   tips: [`Building a network isn't about schmoozing. It's about letting the people who trust you know what you're doing now.`, `Before you change jobs, move house or end a relationship, arrange your next step first. You'll leave with more peace of mind.`, `When you face an unfamiliar field, research it first. Don't try to cover gaps in your knowledge with personal favors.`]
  },
  '2/4': {
   title: `The master practicing in their room until a friend knocks`,
   summary: `You have talents you don't think much about, and you're happiest behind a closed door doing your own thing. Your 2nd line needs a lot of time alone; your 4th line brings opportunities through the people you know. Your story often goes like this: you quietly do something at home, a friend sees it and says, "Wait, you're really good at this," and then you get called out to shine.`,
   loop: `You retreat into your own world to practice, until everyone in your circle knows what you can do. One day someone knocks to invite you out, you go and use your gift, and afterward you want to retreat again. The key is to leave the door open a crack so the right people can find you.`,
   love: `You need a relationship that lets you disappear for an afternoon. If your partner reads your time alone as coldness, you'll keep getting stuck there. You usually get set up by friends or noticed at a gathering of people you know, rather than chasing anyone yourself. A reminder: saying out loud "I need some time alone, it doesn't mean I don't love you" will make things much easier for your partner.`,
   work: `Say you like editing videos at home after work, just for fun. One day a friend says their shop needs a promo video and asks if you could help. After that, friends of friends start coming to you, and just like that you have a side business. Selling yourself everywhere rarely opens a market for you, but word of mouth among people you know can take you far. What really matters is letting the people around you know what you're doing.`,
   tips: [`Time alone is how you recharge. You don't need to feel guilty about it.`, `Put your work where people you know can see it, and wait for them to call you out.`, `When someone calls you out, look at who's calling. Opportunities that come through people you know usually suit you best.`]
  },
  '2/5': {
   title: `The hidden master called on stage by the crowd`,
   summary: `Inside, you just want to quietly do your own thing, but the world keeps pushing you on stage. Your 2nd line gives you natural talent and a strong need to be alone; your 5th line makes even people who barely know you project expectations onto you, as if you are obviously the one who should fix their problems. Your life swings back and forth between hiding away and being called out.`,
   loop: `You do something at home for your own enjoyment, people see it from afar, decide you're an expert and ask you to step in. You solve the problem, your reputation spreads further, and more people come knocking. If you don't learn to close the door, you will soon be emptied out.`,
   love: `At first your partner may imagine you as someone mysterious who understands them deeply. That is the projection of your 5th line. In reality you just need a lot of space of your own; you aren't trying to be mysterious. Once you are together and they see that you get tired too and sometimes just want to do nothing, they may be disappointed. A reminder: letting them see the real you early is better than letting the fantasy build until it bursts one day.`,
   work: `A project at your company gets stuck, and for some reason your manager thinks of you, even though you don't usually say much. You take it on and solve it, and people start treating you as the fire brigade. The problem is that your talent needs solitude to grow, and constant firefighting drains you dry. You can say yes, but be selective, and once the job is done, go back to your own working rhythm.`,
   tips: [`When you're called on, first ask yourself: is this person, this task, worth leaving my room for?`, `Your reputation is an asset. Don't take on something you can't deliver just to avoid disappointing people.`, `Keep regular time when no one at all can reach you.`]
  },
  '3/5': {
   title: `The crisis commander who has fallen countless times and gets called in when it counts`,
   summary: `Your life reads like a lab notebook covered in red ink. Your 3rd line won't believe anything until you've tried it yourself, and every mess you make is tuition paid toward the future; your 5th line makes it easy for people around you to pin their hopes on you, sure that you hold the answer. The more mistakes you make in private, the more you can offer, when you're pushed to the front, solutions no one else thought of that actually work.`,
   loop: `Where no one is watching, you try and fail again and again, noting down each "this doesn't work." One day the people around you are stuck on a big problem and all eyes turn to you. You bring out the judgment those mistakes bought you, and in no time things are moving again. Then you go back to your everyday trial and error and wait to be called on next time.`,
   love: `Your past relationships may have been on and off, with cold wars, misunderstandings and clashing habits. Precisely because of this, when your partner hits a setback at work or falls out with their family, what you say is especially practical. It isn't empty comfort, it's "Last time I handled it like this, and here's what happened." That makes it easy for them to see you as an ideal partner who knows everything. A reminder: let them see that you panic and make mistakes too. That is what keeps the relationship on solid ground.`,
   work: `Say you want to open a bubble tea shop. The first time you choose the wrong location; the second time the menu is too complicated and the staff can't keep up, and the books are in the red for months. Someone else might have given up long ago, but you keep adjusting until you've worked out the finer points of location, pricing and scheduling. Later, friends come to you whenever they want to open a shop, and some even pay you to come and look at theirs, because everything you say was learned by losing money. Just be aware that if your advice doesn't work one day, their disappointment will be harsher than it would be with an ordinary consultant.`,
   tips: [`Stop blaming yourself for the wrong roads you took. Those mistakes are exactly why people trust you later.`, `When someone says "Only you can handle this," slow down and work out whether you really want to take it on or just can't bear to lose face.`, `Before you agree to help, agree on the scope and the cost, and once the job is done, hand the stage back.`]
  },
  '3/6': {
   title: `The one who stumbled when young, then climbed to the roof and saw the whole picture`,
   summary: `Your life is like a film in three acts. The first act of both your 3rd and 6th lines is all trial and error, so your youth was probably especially eventful: you changed jobs, partners and homes more often than most. From around thirty, you retreat to the roof to observe and take stock. Around fifty, you turn all of that into a way of living that people find convincing.`,
   loop: `You crash hard, then climb onto the roof to calmly look back and understand what those collisions meant. But your 3rd line won't let you stay on the roof forever, and you go down to crash again. Each time, your view becomes more complete, until you are the person whose words carry weight because you've been through it all.`,
   love: `Before thirty, your relationships may come quickly and end just as fast, and in each one you learn what you want. Your 6th line secretly holds an ideal of a "soul mate," so you keep trying and keep being disappointed. A reminder: a relationship ending doesn't mean you failed; it means you are getting closer, step by step, to the person who truly suits you. In your roof phase, don't refuse to come down at all just because you're afraid of being hurt again.`,
   work: `You might have changed jobs four or five times in your twenties, and friends and family worried about you. After thirty you become calmer, look at things from one level higher than your colleagues, and can often see at a glance where the team will go wrong. From your forties and fifties on, younger people start seeking you out to talk about their careers, because your experience didn't come from a book; you crashed your way to it.`,
   tips: [`The chaos of your youth isn't failure. It's you collecting material for becoming a role model later.`, `When nothing excites you during your roof phase, you are settling and absorbing, not falling behind.`, `Share your failures. They are exactly what others most need to learn from.`]
  },
  '4/6': {
   title: `The one everyone in the circle ends up asking for advice`,
   summary: `Your opportunities and your influence both come through people you know. Your 4th line values trust and friendship, and a stable network is your foundation; your 6th line divides your life into three stages, and the further along you go, the more you become an example worth following. People don't remember you because you're loud, but because of trust built up over many years.`,
   loop: `You share your experience within your network, and friends who trust you pass opportunities your way. Later in life, you slowly shift from a participant in the circle to the person everyone looks up to. Your 6th line's high standards let you see clearly, and your 4th line's network lets what you see travel.`,
   love: `Many of your relationships start as friendships, because you need to trust before you can open up. Your 6th line gives you high expectations of a partner, and you may quietly keep score. A reminder: your partner isn't there to pass an exam. Saying your standards out loud and talking them through beats watching from the roof to see whether they slip up.`,
   work: `Your good jobs mostly come through former classmates, ex-colleagues or friends making introductions. Before thirty you may change direction a few times; after thirty you become more of an observer and can see your company's real problems. Later on, you're often the one in your circle people ask, "Do you think this is a good idea?" Lining up your next step before you resign is your 4th line's most practical protection.`,
   tips: [`Your network is built from trust you've deposited. Looking after it matters more than constantly meeting new people.`, `Don't hold everyone around you to a perfect standard, yourself included.`, `If you're willing to share in later life, your influence will go far beyond what you imagine.`]
  },
  '4/1': {
   title: `A train moving steadily along its own track`,
   summary: `4/1 is the only "juxtaposition" profile, and your life is like a fixed track. Your 4th line moves you forward through your network; your 1st line gives you a solid position that doesn't shift easily. You aren't someone who turns with the wind, and you don't need to be. As long as you stay on your own track, you'll go far and go steadily.`,
   loop: `You deal with the people around you from a position built on research, and those who trust you bring opportunities onto your track. You take them, and your position grows even firmer. When someone tries to pull you onto a different track, you instinctively resist, and that is usually the right call.`,
   love: `Once you commit to a relationship, you are steady and devoted. But you won't drastically change your way of life for your partner, which can make you seem stubborn. A reminder: you don't have to become someone else, but you can be clear about where you can adjust and what is your track. Finding someone who appreciates your steadiness is much easier than being with someone who wants to remake you.`,
   work: `You suit going deep in one professional field for many years and building clients through word of mouth, for example as an accountant, an engineer or a veteran of some industry, with one referral leading to the next. If someone urges you, "Things have changed, pivot now," and you force yourself into something you don't believe in, it usually goes badly. Your best strategy is to go deeper on the track you're already on.`,
   tips: [`Your stubbornness is your steadiness. You don't need to apologize for it.`, `When you're pushed to make a sharp turn, ask yourself: is this still on my track?`, `Opportunities come through people you know, so let those who trust you know what you're doing.`]
  },
  '5/1': {
   title: `The fire chief who shows up with a thick binder`,
   summary: `People often see you as the one who can solve the problem; that's the projection of your 5th line. The confidence to actually solve it comes from your 1st line's solid research. Your life story goes like this: a crisis hits, everyone looks at you, you open your prepared binder and pull out the plan you thought through long ago. When you're well prepared, you're the rescuer; if you go on unprepared, your reputation takes a hard fall.`,
   loop: `You quietly research and build up knowledge, the outside world starts projecting expectations onto you and handing you hard problems, and you solve them on the strength of your research. Your reputation grows, and so do the expectations. As long as you step back after putting out each fire and go back to your research, the cycle can keep going.`,
   love: `At first your partner may easily idealize you, seeing you as knowledgeable and dependable. You also want to study them thoroughly and make sure it's safe before you commit. A reminder: projections always break one day. When your partner discovers that you panic too and don't know everything, don't rush to retreat. That's when the relationship really begins.`,
   work: `Your company lands a type of project it has never done before, and everyone looks at you, because you're always the person who has "looked into everything." You take it on, research through the night and come back with a workable plan, and the client is happy. But if you get pushed into a field you haven't prepared for and it fails, people will say, "Turns out they're not that great after all." So before you take a job, check: is this a field I've researched?`,
   tips: [`Your reputation is your most important asset. In unfamiliar areas, it's better to say "Let me look into it first."`, `Once the problem is solved, step back. Don't let firefighting become your full-time job.`, `The expectations others project onto you are not your obligations.`]
  },
  '5/2': {
   title: `The mysterious expert called to put out fires who shuts the door at home`,
   summary: `To outsiders you carry real weight, and you're the person people think of when there's trouble; yet you yourself just want to stay home doing what you love. Your 5th line brings projection and being called on; your 2nd line gives you natural talent along with a strong need to be alone. Others often see your gifts before you do, and you tend to think, "That's nothing special."`,
   loop: `You shut the door and enjoy your own world, while outsiders keep projecting expectations onto you and calling you out to help. After you solve the problem, your reputation brings more people knocking. You have to learn to choose, or you'll lose your own time to one summons after another.`,
   love: `People often find you a bit mysterious and hard to read, and that is very attractive. Your partner may project a lot of imagination onto you, when really you just need space. A reminder: don't leave them to guess. Now and then, say what's on your mind, so they get to know the real you rather than the one they imagine.`,
   work: `You might be minding your own business when senior management singles you out to handle a hot potato, simply because "you seem like you could." You sort it out with your natural talent, and people trust you even more. But if you keep taking on missions like this, you'll grow more and more tired and more and more eager to vanish. Learning to say "Not this time" is what lets you step in when it truly matters.`,
   tips: [`You don't owe anyone a rescue. You can answer the call selectively.`, `Your talent needs solitude to grow. Being alone isn't running away.`, `Before you take on a task, be clear about the scope and the timing, so expectations don't tie you down.`]
  },
  '6/2': {
   title: `The natural role model watching from the roof, waiting to be invited down`,
   summary: `Your life comes in three acts: before thirty you try everything, like a 3rd line; from thirty to fifty you retreat to the roof to observe; after fifty you come down and live the kind of life others want to learn from. Your 2nd line gives you natural talent and also means you need to be called out. You don't need to rush to prove yourself; time is on your side.`,
   loop: `From the roof you watch the world with a cool eye, while honing your skills in your own space. People notice your talent and your calm and come to invite you out. When you do step in, you usually go straight to the heart of the matter, then return to the roof. The older you get, the more people ask for you.`,
   love: `You hold high ideals about a partner and are often watching and waiting for "the right one." You also need a lot of time alone, which can make you seem distant. A reminder: no one can fully match your ideal, including you. Allow your partner to be imperfect, and allow yourself to come down from the roof a little.`,
   work: `You might change jobs a few times before thirty, then grow indifferent to office politics after thirty and just want to focus on what you're good at. Yet your talent catches your manager's eye, and you get picked to mentor new hires or handle a key project. After fifty, you'll find many people come to you for advice as a respected veteran of your field.`,
   tips: [`The detachment of your roof phase is you settling and absorbing. Don't take it as a sign you've lost your passion.`, `When someone comes to invite you, it means your talent has been seen. You can try stepping out.`, `Your ideals are precious, but don't use them as a reason to turn everyone down.`]
  },
  '6/3': {
   title: `The one who stumbled all the way and became a real-life example`,
   summary: `Your life also comes in three acts, but your 3rd line means you never stop experimenting, even on the roof. You hit walls more often than other 6th lines, and your relationships and work are more likely to go through cycles of building and breaking. The role model you finally become isn't the flawless kind, but the kind that says, "I really did fall, and I really did get back up."`,
   loop: `You climb onto the roof to observe and try to see the whole picture, but your 3rd line pulls you down to crash again; then you go back up to sort it out. This back and forth gives you a very complete view of things, and a deep understanding of life's practical realities.`,
   love: `Your love life may have had plenty of beginnings and endings, and sometimes you wonder whether you're just not suited to long-term relationships. In fact, your 3rd line needs collisions to learn what works, and your 6th line keeps searching for someone worth trusting. A reminder: don't assume the next relationship will end just because a few past ones did. Each time, you know more clearly what you want.`,
   work: `You may have moved through several fields, and your résumé looks jumpy. But in mid to later career you'll find that all these experiences connect, letting you see more broadly than a specialist in a single field. For example, you've done sales and marketing and been through a startup that folded, and you end up as a very practical consultant or manager who isn't afraid to tell the truth.`,
   tips: [`Your history of falls is what makes you convincing. You don't need to hide it.`, `When a relationship or job ends, ask "What did I learn?" rather than "I failed again."`, `Once you've seen clearly from the roof, allow yourself to go down and try once more.`]
  }
 },

 lines: {
  1: {
   misread: `Others think you overthink and drag your feet; you often wonder yourself whether you just lack confidence, since you need to check everything before you dare to move.`,
   mindset: `Research is your foundation, not procrastination. Once you have enough information, your sense of security kicks in, and then you'll be steadier than anyone.`,
   examples: [`Before you buy a new phone, you make a comparison table of three models' specs, reviews and prices, and only order once you've checked everything. Otherwise you wouldn't feel easy about it.`, `In your first week at a new company, you go through the old files in the shared folder, because you want to know how things work here.`]
  },
  2: {
   misread: `Others think you're a loner who doesn't fit in, maybe even a bit lazy; you don't quite understand why people keep saying you're so talented.`,
   mindset: `Your gifts ripen when you're alone, and you don't need to sell them. Leave the door open a crack and wait for the right people to call you out.`,
   examples: [`You post a sketch you dashed off at home to your stories, and a friend messages right away: "You drew this? Could you design our wedding cards?"`, `A colleague watches you fix the printer in no time and asks in surprise how you knew how, and only then do you realize it isn't easy for everyone.`]
  },
  3: {
   misread: `People around you often worry, thinking you could easily follow the path others have already taken but insist on taking the long way round; after enough dead ends, you start to wonder whether you're clumsier than everyone else.`,
   mindset: `You aren't failing, you're experimenting. Every thing that doesn't work is a reliable record that tells you and the people around you which road to avoid. What you've tested yourself is more trustworthy than anything passed on secondhand.`,
   examples: [`A friend recommends a popular budgeting method. After two weeks you find it doesn't suit you, revise it three times, and end up with a system that's all yours and that you actually stick with.`, `When you learned to cook, you rarely followed the recipe amounts and over-salted or burned things plenty of times. Now one look at the color in the pan and one sniff tell you whether it's done.`]
  },
  4: {
   misread: `Others think you only get by on connections, or that you're too attached to the past and afraid to change; you yourself find changing environments especially painful.`,
   mindset: `Your influence comes from trust. Opportunities come through people you know, and finding your next landing spot before you leave a place is your survival wisdom.`,
   examples: [`You recommend a restaurant, and your friends book a table without a second thought, because "if you say it's good, it's good."`, `You've wanted to quit for ages but keep holding on, until a former colleague asks if you'd like to join their company, and only then do you hand in your notice with peace of mind.`]
  },
  5: {
   misread: `People meeting you for the first time often think you're more capable than you are and automatically put hard problems on your plate; if the result falls short, their backlash is especially strong, as if you'd let them down.`,
   mindset: `Part of how others see you is their own imagination. You really can offer concrete, workable solutions, but choose carefully first, be clear about how far you can go, and step back once it's done. That's how your reputation stays intact.`,
   examples: [`On a new colleague's first day, they drop a report they can't figure out on you: "Everyone says you're the person to ask." You don't really know it well either.`, `At family gatherings, the older relatives' insurance, phones and arguments all wait for you to sort out, as if you were the family's all-purpose rescuer.`]
  },
  6: {
   misread: `Others think you're aloof and above it all, always standing on the sidelines watching; you may also lose interest in everything at a certain age and think you've lost your passion.`,
   mindset: `Your life has three stages. The experimenting before thirty and the observing from thirty to fifty are both preparation for becoming a role model after fifty. Watching from the side is settling, not giving up.`,
   examples: [`In your twenties you changed jobs and partners often; after thirty, at gatherings you became the one quietly sipping a drink who sees everything most clearly.`, `When friends argue, you don't rush to take sides. You say one thing that calms both of them down, and afterward each of them comes to talk to you privately.`]
  }
 },

 typeAuth: {
  'generator|emotional': {
   story: `Your Sacral is like a fully charged battery that can keep going for a long time on things you respond to, but your real answer only becomes clear after your emotions have gone through a full wave. In the moment your body may say yes, and when you're on an emotional high, everything looks good. Give yourself a night or a few days. If your body still wants it when you're calm, then you really want it.`,
   scene: `A friend excitedly asks you to open a shop together. What doesn't work: you get swept up in the mood, slap the table and say "Yes, let's do it," and three weeks later realize you don't want to mind a shop every day. What works: say "That sounds fun, let me think about it for a few days," then, a few days later and calm, ask your friend to ask you again and listen to how your body responds.`
  },
  'generator|sacral': {
   story: `Your answer lives in your body's response in the moment. When someone asks you a yes-or-no question, you first make a sound, an "uh-huh" or an "uhn-uhn," and that is the answer; the reasons your head adds afterward mostly don't matter. You don't need to think for long. Thinking too long can actually bury your real response.`,
   scene: `A colleague asks if you'd like to go hiking this weekend. What doesn't work: your head starts calculating, "I should exercise more," "It'd be rude to say no," and you reluctantly agree and feel drained the whole way. What works: listen for your first response. If it's a flat "uhn-uhn," just say not this time; if it's an energetic "uh-huh," go.`
  },
  'mg|emotional': {
   story: `You're fast and often want to charge straight in, but your authority is emotional, so the real answer only comes once the wave settles. Let your body respond first, then give yourself some time. Once you're sure, inform the people who will be affected, then let yourself go at your own speed. Be fast in doing, not in deciding.`,
   scene: `Your manager asks if you'll take on a new cross-department project. What doesn't work: you feel thrilled in the moment, say yes on the spot and start setting up group chats; a week later the excitement fades and you realize you can't finish what's already on your plate. What works: say "I'm very interested, I'll get back to you tomorrow." If you still want it the next day when you're calm, then tell your manager and team that you're starting.`
  },
  'mg|sacral': {
   story: `You decide through your body's response and move very fast. Once the response comes, the answer is there; then inform the people involved before acting, and you'll avoid a lot of misunderstandings. You skip steps and multitask, and that isn't carelessness, it's your efficiency. Just look back now and then to check what you missed.`,
   scene: `A friend asks whether you want to sign up together for next month's marathon. What doesn't work: your head says "I should be up for a challenge," you sign up without listening to your body, and training is miserable. What works: listen for your body's first response. If it's "uh-huh," sign up, and tell your family "I'll be running on weekend mornings from now on," so they don't feel suddenly left behind.`
  },
  'manifestor|emotional': {
   story: `You have the ability to initiate, but your emotional authority asks you to wait for the wave to settle before deciding whether to initiate. Impulses you feel at an emotional high are often regretted at the low. Once you're clear, inform the people who will be affected, then act. That way there's far less anger and far less resistance.`,
   scene: `One night you suddenly want to quit your job and go abroad on a working holiday. What doesn't work: you write and send your resignation letter that very night and don't tell your family the next day either, so everyone is stunned and you start doubting yourself. What works: wait a few days and see whether the idea is still there at both your emotional highs and lows. Once you're sure, tell your manager and family about your plan first, then hand in your notice.`
  },
  'manifestor|splenic': {
   story: `Your intuition speaks once in the moment and doesn't repeat itself, and you can initiate directly, so your decisions can be very fast. The first "this is it" or "something's off" is the most accurate; thinking too long lets your head talk you out of it. Once you've decided, remember to inform the people who will be affected.`,
   scene: `You're viewing apartments, and the moment you walk into one, something feels off, even though it ticks every box. What doesn't work: the agent keeps pushing, you talk yourself into it because "the price is such a good deal," sign, and feel more and more uncomfortable living there. What works: trust that split-second feeling and say no. When the next place feels right, decide on the spot and tell your family, "I've chosen one."`
  },
  'manifestor|ego-m': {
   story: `Your answer comes from what you truly want, and you hear it the moment you say it out loud. Notice your tone when you say "I want..." or "I don't want...": that is your authority. You don't need to make excuses for what you want. Inform others, then go and do it.`,
   scene: `A friend invites you to invest in their new business. What doesn't work: out of loyalty to your friend and because it's "a rare opportunity," you agree to something you don't actually want, and then feel tied down for a long time. What works: listen to what comes out of your mouth. If you hear yourself say "Honestly, I don't want to deal with this kind of thing," just decline; if it's "I want to be part of this," tell your family and then commit.`
  },
  'projector|emotional': {
   story: `What matters most for you is waiting to be recognized and invited, and once an invitation arrives, you still need to let your emotional wave run its course before answering. When the invitation comes, you may feel delighted, finally recognized, but that isn't necessarily clarity. Wait a few days, and only say yes if it still feels right when you're calm.`,
   scene: `A headhunter calls to invite you to be a manager at a new company, with great terms. What doesn't work: you feel seen at last, accept on the spot in the excitement, and only after starting discover the team culture doesn't suit you at all. What works: thank them and say you need a few days to think. Meanwhile, notice how you feel about the job at your emotional highs and lows, and accept only if you still want it when you're calm.`
  },
  'projector|splenic': {
   story: `You wait to be invited, and the moment an invitation appears, your intuition tells you the answer right away. That very quiet, very fast "right" or "not right" speaks only once. Don't wait for your head to think it through before deciding, because your head often drowns out what your intuition said.`,
   scene: `A new friend invites you to start a studio together. What doesn't work: your intuition feels something is off in the moment, but you think "They're a nice person, chances like this are rare," reluctantly agree, and the collaboration hits snags everywhere. What works: notice your body's feeling the moment the invitation appears. If it feels wrong, politely decline; if it feels right, accept without overthinking.`
  },
  'projector|ego-p': {
   story: `You wait to be invited, and after an invitation comes, ask yourself: "What's in it for me? Do I really want this?" That isn't selfish. Your willpower only commits to things that are truly worth it. Say these things out loud and you'll hear your own answer.`,
   scene: `Your manager invites you to lead a new team. What doesn't work: you feel valued and say yes, without thinking about a raise, authority or whether you even want it, and end up exhausted with nothing to show for it. What works: talk it over with a friend you trust and listen to whether you say "I want this role" or "I just feel awkward saying no." Then decide whether to take it, and negotiate the terms clearly.`
  },
  'projector|self': {
   story: `Your answer is in the sound of your own voice. After you receive an invitation, talk it through with someone you trust, not so they can give advice, but so you can hear what you say. When the direction is right, you'll feel "Yes, this is me" as you speak.`,
   scene: `A friend invites you to move to another city together. What doesn't work: you go over the pros and cons alone in your head, get more and more muddled, and end up deciding at random. What works: meet someone you trust for coffee and talk about it. You might hear yourself say "I really want a change of scene," or "I think I just want to get away from my life right now." The answer is in that sentence.`
  },
  'projector|mental': {
   story: `You have no inner bodily authority; clarity comes from your environment and from conversation. After you receive an invitation, find a few different people to act as sounding boards and talk your ideas through in different places. The point isn't to take their advice, but to slowly understand yourself as you talk.`,
   scene: `You get an acceptance letter for a graduate program and a job offer at the same time. What doesn't work: you shut yourself in your room making lists, or decide on a single comment from your parents. What works: talk it through separately with an older schoolmate, an old friend and a family member, once in a café and once in a park, and notice which option gets clearer and more reassuring the more you talk about it.`
  },
  'reflector|lunar': {
   story: `You're like a mirror, and how you feel each day changes with your surroundings and the people around you. Major decisions need about 28 days, the time it takes the Moon to complete one cycle. During that time, take in how you feel and talk with people you trust; listen to what you think today and what you think two weeks from now, and the answer will slowly surface.`,
   scene: `Someone invites you to share a new apartment with them. What doesn't work: the viewing day has a lovely atmosphere, you sign the lease that same day, and a month later you realize living there keeps you uncomfortable. What works: tell them you need a month to think. Meanwhile, walk around that neighborhood several times, talk with a few friends and notice how you feel on different days. If it still feels good after a month, then decide.`
  }
 },

 channels: {
  '1-8': `You have a very distinctive way of expressing yourself, and just being yourself naturally makes you an example for others. You might share your outfits or lifestyle on social media without chasing trends, and people quietly follow your lead. Your creativity doesn't need everyone's approval; being seen by the right people is enough.`,
  '2-14': `You're like a keeper of keys who knows where resources and effort should go. On a team, you might naturally be the one deciding how to split the budget and which way to head, and the direction your body responds to is usually right. When you're doing something you're truly committed to, money and resources flow your way too.`,
  '3-60': `Your energy comes in pulses, like a switch: sometimes you're stuck for a long time, then suddenly break through all at once. You might be stuck on a bottleneck for months, then one day it all clicks and you change your whole approach. The stuck periods aren't stagnation; change is brewing.`,
  '4-63': `Your mind is used to doubting first, then using logic to find the answer. When someone says "This stock is definitely going up," your first reaction is "Based on what?" You're good at spotting patterns and flaws, which suits analysis and debugging. A reminder: doubt is very useful for outside matters, but exhausting when you turn it on yourself.`,
  '5-15': `You have your own rhythm, and fixed habits matter a lot to you. You might get up at the same time every day and go to the same breakfast place; others find it dull, but it keeps you steady. You're also very accepting of people with all kinds of rhythms. It's only when someone forces you to change your routine that you feel completely off.`,
  '6-59': `You easily break down the distance between people, and others open up to you quickly. At a gathering, a few words from you might get a stranger telling you their worries. This energy is also tied to intimacy and partnership, so when choosing whom to get close to, wait until your emotions have settled before you decide.`,
  '7-31': `You're a natural leader, but your influence is strongest when you're recognized and put forward. In a group presentation, you might naturally be chosen as the speaker, and people are willing to follow the direction you set. If you try to grab the lead, you'll often meet resistance; wait for others to ask, "Where do you think we should go?"`,
  '9-52': `You can focus on one thing for a long time, sitting still and paying close attention. You might spend a whole afternoon fine-tuning the format of a spreadsheet; others gave up long ago, but you enjoy it. When it's something you respond to, your focus is like a laser and you take the details as far as they can go.`,
  '10-20': `You live in the present and are completely natural about being yourself. You might say in a meeting, "I just don't like this proposal." That isn't stubbornness; you simply know very clearly who you are. Your presence alone reminds others that they don't have to live up to other people's expectations.`,
  '10-34': `You have a powerful drive to act, and you only do things your own way. When someone tells you how it would be better done, you might nod and agree, then turn around and do it your way anyway. That isn't rebellion; your power comes from being true to yourself. Just remember to wait to respond before you set off.`,
  '10-57': `You know intuitively how to live well and live beautifully. You might walk into a room and know how the furniture should be arranged, or see at a glance that someone isn't themselves today. Your intuition speaks once in the moment and doesn't repeat itself; trust it and it will often help you avoid trouble.`,
  '11-56': `Your head is full of ideas and stories, and you're great at making your experiences vivid and entertaining. When you come back from a trip, your stories keep friends spellbound and make them want to go too. Your value is in stimulating other people's thinking. You don't have to carry out every idea yourself; telling it is already doing its job.`,
  '12-22': `Your expression is very moving, but it depends on your mood. When you're in a good mood, everyone in the room is drawn in the moment you speak; when you're not, forcing you to socialize only makes things awkward. Wait until your emotions are in place to say important things, and your words will really touch people.`,
  '13-33': `You're like a witness, and people easily share their worries and secrets with you. You might hear a stranger's whole life story on a train. You keep these stories inside, come back to sort through them after a while, and turn them into wisdom to share. You need time on the sidelines to digest.`,
  '16-48': `Your talent comes from repeated practice. You might have practiced piano, coding or cooking since you were young, over and over until it looks effortless to others. You care a lot about depth, and when you feel you're not good enough yet, you hesitate to show your work. In truth, your level has been good enough for a long time.`,
  '17-62': `You're good at organizing ideas into clear structures and details. When everyone in a meeting is talking in circles, you say "Let's look at this in three parts," and the whole thing becomes clear. Your opinions are well organized, but remember to wait until you're asked, or you may come across as lecturing.`,
  '18-58': `You can see at a glance where things could be better, and you have a strong passion for fixing them. After ordering at a restaurant, you might quietly start thinking about how to rearrange the layout so things flow better. This energy is a treasure where you're invited to use it; when no one asked, it can easily make people feel criticized.`,
  '19-49': `You're very sensitive to the needs of the people around you, and you notice who hasn't eaten or who's been left out. In relationships you care a lot about fairness and principles, and when you feel badly treated, you cut ties cleanly. You're well suited to looking after a group, but remember to ask whether your own needs are being met.`,
  '20-34': `You turn energy straight into action, always busy, and charismatic in your busyness. When a friend mentions they're moving, you might already have your sleeves rolled up and be carrying boxes. Your efficiency is remarkable, but only when you're doing things your body responds to does more busyness bring more joy; busy in the wrong direction, you're just left exhausted.`,
  '20-57': `Your intuition in the moment is very sharp, and you can often blurt out the key point. While a friend is still hesitating over whether to sign a contract, you say, "Something's off here," and put your finger right on the problem. Your awareness comes and goes quickly; it's most accurate the moment you say it, and hard to explain afterward.`,
  '21-45': `You're good at managing resources and people, and naturally suited to making the material decisions. When the family is buying a car or the company is dividing the budget, people naturally let you have the final say. You need a sense of control and feel uncomfortable when everything is second-guessed; just remember that good managers look after everyone.`,
  '23-43': `You often have very original insights; once something clicks for you, it seems obvious, but others can't follow right away. You might propose a new approach in a meeting and get a room full of puzzled faces. Wait for people to ask, and explain in a way they can understand, so your genius isn't taken as strangeness.`,
  '24-61': `Your mind loves pondering life's big questions, and you often get lost in thought on your own. Answers might suddenly pop up in the shower or on a walk. You don't need to force yourself to reach a conclusion; inspiration keeps its own schedule. Don't let the questions in your head become a reason to lose sleep.`,
  '25-51': `You have the courage to rush into the unknown and like being the first to try. While your friends are still deciding whether to go skydiving, you've already signed up. You also often grow through unexpected shocks; those moments that startle you tend to help you understand yourself better, and wake up the people around you too.`,
  '26-44': `You understand what people need, and you're good at selling, persuading and passing things on. When you recommend a skincare product, your friends want to buy it once you've finished talking. You also remember past experience and know what tends to go wrong. This gift works best when you use it on things you truly believe in.`,
  '27-50': `You're a natural caregiver and take values and responsibility seriously. When a friend is sick, you're the first to show up with soup, and you quietly shoulder family matters. You're the guardian of the group, but before you look after others, make sure you're being well looked after too, or responsibility can easily crush you.`,
  '28-38': `You're willing to fight to the end for what's meaningful; when people tell you to give up, you insist on trying again. Say there's a project no one believes in, and you keep at it for two years until it finally takes off. Your struggle has real value; just remember to ask yourself whether this fight is truly worth it.`,
  '29-46': `Once you commit, you give yourself fully until the end. You might agree to help a friend with an event and end up handling everything from the venue to the schedule. You often succeed where others have given up, so wait for your body to respond before you agree, because once you say yes, it's hard to turn back.`,
  '30-41': `You carry many dreams and things you want to experience, and you hunger for new experiences. You might always be planning a certain trip or a certain way of life. This longing is full of energy, but expectations and reality often don't match, so give your feelings some time and don't rush to make every dream come true at once.`,
  '32-54': `You have the ambition to climb, and you know how to judge what's worth building over the long term. You might start at the bottom and work your way up, picking the right moment for each promotion. You care a lot about whether effort turns into real results, and if there's someone around who appreciates you, you'll climb faster and more steadily.`,
  '34-57': `You react in the moment through intuition and power, extremely fast. When something sudden happens, say a child about to fall, you've already rushed over to catch them. Your body knows exactly how to survive and doesn't need to think it through first. As long as you listen to your body's response, you rarely go wrong.`,
  '35-36': `You chase new experiences and feelings and want to try everything. You might have tried surfing, pottery and bartending, a little of everything. These ups and downs have taught you a lot, but novelty comes and goes quickly, so wait until your emotions settle before you decide whether to dive into the next adventure.`,
  '37-40': `You take agreements seriously, and giving and receiving need to balance. In your family or friend group, you're often the one organizing dinners and looking after everyone. But you also need rest and thanks, and when you feel you keep giving without anything coming back, you may suddenly want out. State your terms clearly and the relationship will be steadier.`,
  '39-55': `Your emotions swing widely: high one second, low the next, and not always for a reason. That isn't a problem with you; it's your design. Your emotions also bring a rich spirit and creativity, and a lot of good work gets written in the low moments.`,
  '42-53': `You're good at carrying things from start to finish, and you grow through one cycle after another. When you start a new habit, you want to see it through a full round. Being interrupted halfway makes you very uncomfortable. Before you begin, make sure your body responds, because once you start, you'll want to go all the way.`,
  '47-64': `Your mind often holds many images and fragments that are confusing at first and only suddenly make sense after a while. You might recall something from years ago and suddenly understand how it affected you. Don't push yourself to figure it out; the answer will piece itself together at the right time.`
 },

 centersOpen: {
  head: `With an open Head Center, your mind easily fills up with other people's questions. A friend casually asks "What's the meaning of life?" and you might think about it all night. Scrolling your phone before bed, other people's worries make you anxious too. Remind yourself: this isn't a question I need to answer.`,
  ajna: `With an open Ajna Center, you understand different points of view very well. In a meeting, A makes sense to you and so does B, yet you feel pressure to take a firm position right away. You can say "I'm still thinking about it"; that flexibility is your wisdom.`,
  throat: `With an open Throat Center, awkward silences are your worst fear. Three seconds of quiet in a meeting and you can't help filling the gap, then feel you said too much. At gatherings you may jump in to keep the conversation going. Try waiting until someone asks you; that's when what you say carries the most power and is most easily heard.`,
  g: `With an open G Center, your sense of identity shifts with your surroundings. A new job or a new city and you seem to become someone else. You often ask, "Who am I, and where am I going?" In fact, as long as you choose the right places and people, the direction will appear on its own.`,
  heart: `With an open Heart (Ego) Center, you easily feel you have to prove yourself. A colleague says "You can finish this in a week, right?" and even though you need two, you grit your teeth and say yes. A line like "You deserve it" can also talk you into a purchase. You don't need to prove your worth; just do what you can.`,
  sacral: `With an open Sacral Center, you easily get carried along by other people's energy. On a trip with friends, everyone stays up till midnight and you push to keep up, only to realize you're wiped out once you're home. You don't know when to stop, because that energy was never yours to begin with. Learning to leave before you're tired is your homework.`,
  spleen: `With an open Spleen Center, you're very sensitive to your body and to how other people are doing. You may know full well that a relationship or job isn't healthy, yet hold on because "at least it's familiar and feels safe." What feels safe isn't necessarily good for you. Try letting it go.`,
  sp: `With an open Solar Plexus Center, you amplify the emotions of the people around you. When a colleague is in a bad mood, you feel down all day too; when family members argue, you rush to play peacemaker. To avoid conflict, you often swallow what you really think. First ask yourself: is this my emotion, or someone else's?`,
  root: `With an open Root Center, pressure easily pushes you along. The moment a notification pops up, you want to reply right away, and you can't sit still until the to-do list is cleared. You rush to finish things just to get rid of that pressure. Remind yourself: not everything is that urgent, and it's fine to slow down.`
 },

 centersDefined: {
  head: `With a defined Head Center, your mind always has questions and inspiration running in a set direction. You might suddenly get an idea in the shower and then think about it all day. Your thinking stimulates the people around you, but remember: inspiration isn't something you must act on; it's just material for thought.`,
  ajna: `With a defined Ajna Center, you have a steady way of thinking. When a friend asks your opinion, you can usually put your view together quickly. You're confident in your ideas, which is a strength; but for major decisions, don't let "I've thought it through" replace your body's authority.`,
  throat: `With a defined Throat Center, you have a consistent way of expressing yourself and a steady voice. Your words and actions have a set style, and when you speak in a meeting, people listen. You don't need to fight for airtime to be seen, so you can safely wait for the right moment to say what you have to say.`,
  g: `With a defined G Center, you have a steady sense of who you are and where you're going. Whatever environment you're in, you're still you. Friends often come to you when they're lost, because you carry a sense of direction. Just remember that other people's direction may not be the same as yours.`,
  heart: `With a defined Heart (Ego) Center, you do what you say and have steady willpower. When you promise to finish something, you usually do. But willpower needs rest too. Don't take on every commitment just because you can, and don't hold others to your standards.`,
  sacral: `With a defined Sacral Center, there's a steadily running generator inside your body. When you're doing things you respond to, you can be busy from morning to night and still be happy. But if you force yourself through work you have no interest in, the same energy turns into frustration. Use up your energy before bed and you'll sleep especially well.`,
  spleen: `With a defined Spleen Center, you have steady intuition and a strong ability to protect yourself. You might walk into a shop, feel something's wrong, turn around and leave, and only later learn there had been trouble there. Your intuition speaks only once, and quietly; the sooner you trust it, the fewer detours you'll take.`,
  sp: `With a defined Solar Plexus Center, you have your own emotional wave, and highs and lows are perfectly normal. You might feel your job is amazing on Monday and want to quit by Wednesday. At the top or bottom of the wave you only see half the answer, so for important decisions, wait until your mood is steady.`,
  root: `With a defined Root Center, you handle pressure in a consistent way and aren't easily thrown off by other people rushing you. Your manager keeps pushing, and you still finish at your own pace. This steadiness is valuable, but be aware that your pressure can unconsciously push the people around you.`
 }
};
