/* Contenu narratif Human Design en français (profils, lignes, type × autorité, canaux, centres) */
globalThis.STORY_HD_FR = {
 profiles: {
  '1/3': {
   title: `L’explorateur qui étudie la carte avant de parcourir le chemin lui-même`,
   summary: `Votre vie suit le schéma « d’abord étudier, ensuite expérimenter ». La ligne 1 vous pousse à bâtir des bases solides : sans assez d’informations, vous êtes mal à l’aise. La ligne 3, elle, veut que vous alliez sur le terrain pour vérifier dans votre corps si ce que disent les livres est vrai. Vous êtes souvent celui qui s’est le plus documenté, et aussi celui qui est tombé le plus franchement. Au bout du compte, votre savoir-faire est de ceux qu’aucun livre ni personne ne peut vous donner.`,
   loop: `Vous étudiez jusqu’à vous sentir sûr de vous, puis vous agissez, et vous tombez aussitôt sur un trou que les livres ne mentionnaient pas. Ensuite vous retournez compléter vos informations, et vos fondations s’épaississent encore. Après quelques tours, vous devenez quelqu’un qui « connaît la théorie et s’est cassé la figure en pratique », et l’on vient naturellement vous voir avec les problèmes épineux.`,
   love: `Quand quelqu’un vous plaît, vous remontez peut-être ses réseaux sociaux sur trois ans pour savoir qui il est vraiment. Mais une fois en couple, vous découvrez que beaucoup de choses ne s’apprennent qu’en vivant ensemble, et qu’il faut quelques disputes pour connaître les limites de chacun. Ce dont vous avez besoin, c’est de sécurité, pas d’un partenaire parfait. Un conseil : ne concluez pas après un seul accrochage que « cette relation a un problème » ; vous êtes peut-être simplement en train de recueillir des données réelles.`,
   work: `Imaginons que vous vouliez ouvrir un café. Vous lisez d’abord tous les livres sur le sujet et calculez les coûts, puis vous allez travailler six mois dans le café de quelqu’un d’autre pour voir de vos yeux ce que sont une commande de grains ratée, une machine en panne ou un client mécontent. Quand vous ouvrez enfin le vôtre, vous êtes plus solide que les autres débutants, parce que vous êtes déjà tombé dans tous les pièges possibles. Les patrons font confiance à ce genre de personne : des bases, et une vraie expérience.`,
   tips: [`La recherche est votre sécurité, mais fixez-vous un seuil où « il y a assez d’informations », puis lancez-vous.`, `Quand un essai échoue, notez-le comme l’information « ce chemin ne mène nulle part », et non comme la preuve que « je n’y arrive pas ».`, `Vos fondations sont solides : inutile de sauter l’étape de la recherche parce que les autres vont plus vite.`]
  },
  '1/4': {
   title: `Celui qui pose de bonnes fondations, puis partage la belle maison avec ses amis`,
   summary: `Votre vie repose sur deux piliers : un savoir solide et un cercle de personnes qui vous font confiance. La ligne 1 vous oblige à bien connaître le terrain avant d’agir ; la ligne 4 fait venir presque toutes vos occasions de vos proches. Ce ne sont pas des inconnus qui vous découvrent : ce sont « les gens qui vous connaissent et savent que vous êtes fiable ». Des bases stables font un réseau stable, et un réseau stable ouvre le chemin.`,
   loop: `Vous étudiez un domaine à fond, et dans votre cercle d’amis, vous devenez naturellement « la personne à qui demander pour ça ». Vos amis vous présentent à d’autres, les occasions suivent, et chaque nouvelle occasion vous oblige à approfondir encore vos connaissances. Votre influence s’étend en cercles concentriques.`,
   love: `Vos histoires d’amour naissent souvent d’une amitié, ou d’une rencontre par l’intermédiaire d’amis. Les inconnus des applications de rencontre vous rassurent difficilement, parce que vous ne savez pas à qui vous avez affaire. En couple, vous êtes très fidèle, mais vous avez besoin de certitude, et un partenaire qui souffle le chaud et le froid vous inquiète beaucoup. Un conseil : dire clairement de quelle stabilité vous avez besoin est bien plus efficace que d’observer en silence s’il y répond.`,
   work: `Vous trouvez rarement un bon poste en envoyant des CV ; c’est plus souvent un ancien collègue qui vous dit : « On cherche quelqu’un, ça te dirait ? » Votre valeur dans une équipe, c’est que tout le monde sait que ce que vous dites est vérifié et fondé. Si vous voulez changer de voie, faites d’abord passer le mot dans votre réseau : c’est bien plus efficace que de postuler à l’aveugle sur les sites d’emploi. Avec la ligne 4, mieux vaut avoir trouvé votre prochaine destination avant de quitter l’ancienne.`,
   tips: [`Entretenir son réseau, ce n’est pas faire des mondanités : c’est tenir au courant ceux qui vous font confiance de ce que vous faites en ce moment.`, `Avant de changer de travail, de déménager ou de rompre, préparez l’étape suivante : vous partirez plus sereinement.`, `Face à un domaine que vous connaissez mal, étudiez d’abord ; ne comptez pas sur vos relations pour combler les trous de vos connaissances.`]
  },
  '2/4': {
   title: `Le virtuose qui s’entraîne dans sa chambre jusqu’à ce que ses amis frappent à la porte`,
   summary: `Vous avez des talents auxquels vous n’accordez pas grande importance, et vous êtes au mieux quand vous faites vos affaires porte fermée. La ligne 2 vous donne un grand besoin de solitude ; la ligne 4 fait venir vos occasions de votre réseau de proches. Votre histoire est souvent celle-ci : vous faites quelque chose tranquillement chez vous, un ami le voit et dit « mais c’est génial, ça ! », et l’on vous appelle à briller au-dehors.`,
   loop: `Vous vous retirez dans votre monde pour vous entraîner, jusqu’à ce que tout votre cercle sache que vous avez ce talent. Un jour, quelqu’un frappe pour vous inviter, vous sortez donner votre mesure, puis vous voulez vous replier à nouveau. L’essentiel est de laisser la porte entrouverte pour que les bonnes personnes vous trouvent.`,
   love: `Il vous faut une relation qui « vous autorise à disparaître un après-midi ». Si l’autre interprète votre besoin de solitude comme de la froideur, vous resterez bloqués là. En général, ce sont des amis qui vous présentent quelqu’un, ou l’on vous remarque lors d’une soirée entre proches ; vous allez rarement séduire de vous-même. Un conseil : dites à voix haute « j’ai besoin d’être seul, ça ne veut pas dire que je ne t’aime pas », l’autre sera bien soulagé.`,
   work: `Par exemple, le soir, vous aimez monter des vidéos chez vous, juste pour le plaisir. Un jour, un ami vous dit que sa boutique a besoin d’une vidéo promotionnelle et vous demande un coup de main ; ensuite, les amis de cet ami viennent vous voir, et voilà une activité secondaire. Vous aurez du mal à percer en vous vendant partout, mais le bouche-à-oreille de vos proches peut vous mener très loin. Le vrai secret est que votre entourage sache ce que vous faites.`,
   tips: [`La solitude est votre façon de recharger vos batteries : inutile de culpabiliser.`, `Mettez vos créations là où vos proches peuvent les voir, et attendez qu’ils viennent vous chercher.`, `Quand on vous appelle, regardez d’abord qui appelle : les occasions venues de vos proches sont généralement celles qui vous conviennent le mieux.`]
  },
  '2/5': {
   title: `Le maître reclus que la foule appelle sur scène`,
   summary: `Au fond, vous voulez seulement faire vos affaires en paix, mais le monde extérieur ne cesse de vous pousser sur le devant de la scène. La ligne 2 vous donne un talent naturel et un fort besoin de solitude ; la ligne 5 fait que même des personnes qui vous connaissent à peine placent leurs attentes en vous, comme s’il allait de soi que vous régliez leurs problèmes. Votre vie oscille entre « se cacher » et « être appelé ».`,
   loop: `Vous faites quelque chose dans votre coin, chez vous ; on vous voit de loin, on décide que vous êtes un expert et on vient vous solliciter. Vous réglez le problème, votre réputation s’étend, et plus de gens viennent frapper. Si vous ne savez pas fermer la porte, vous serez vite vidé.`,
   love: `Au début, l’autre peut vous imaginer mystérieux et capable de le comprendre : c’est la projection de la ligne 5. En réalité, vous avez seulement besoin de beaucoup d’espace, vous ne jouez pas les mystérieux. En couple, quand l’autre découvre que vous aussi êtes fatigué, que vous aussi avez envie de ne rien faire, il peut être déçu. Un conseil : montrez tôt qui vous êtes vraiment, plutôt que de laisser les illusions s’accumuler jusqu’à exploser un jour.`,
   work: `Un projet bloque dans l’entreprise, et votre responsable, sans trop savoir pourquoi, pense à vous, même si vous parlez peu d’habitude. Vous acceptez et réglez le problème, et l’on commence à vous voir comme le pompier de service. Le souci, c’est que votre talent a besoin de solitude pour grandir, et qu’éteindre des incendies en permanence vous épuise. Vous pouvez accepter, mais en choisissant, et en revenant à votre propre rythme une fois le travail fait.`,
   tips: [`Quand on vous appelle, demandez-vous d’abord : cette personne, cette affaire, valent-elles que je quitte ma chambre ?`, `Votre réputation est un capital : n’acceptez pas ce que vous ne pouvez pas faire juste pour ne pas décevoir.`, `Gardez régulièrement des moments où personne ne peut vous joindre.`]
  },
  '3/5': {
   title: `Le chef des pompiers tombé mille fois, appelé sur le terrain aux moments décisifs`,
   summary: `Votre vie ressemble à un carnet d’expériences couvert de corrections en rouge. La ligne 3 veut que vous essayiez par vous-même avant de croire quoi que ce soit, et chaque raté est une avance sur ce que vous saurez plus tard ; la ligne 5 pousse votre entourage à placer ses attentes en vous, convaincu que vous détenez la réponse. Plus vous vous trompez en privé, plus, une fois envoyé au front, vous sortez des solutions auxquelles personne n’avait pensé, et qui marchent vraiment.`,
   loop: `Là où personne ne regarde, vous multipliez les essais et notez, une à une, les expériences du type « ça ne marche pas ». Un jour, votre entourage bute sur un gros problème, tous les regards se tournent vers vous, et vous sortez ce jugement forgé par vos erreurs pour relancer la machine en un rien de temps. Puis vous retournez à vos essais quotidiens, en attendant le prochain appel.`,
   love: `Vos histoires passées ont peut-être été faites de ruptures et de retrouvailles : silences glacés, malentendus, habitudes incompatibles, vous avez tout connu. C’est justement pour cela que, lorsque votre partenaire subit un revers au travail ou se brouille avec sa famille, vos paroles sont particulièrement concrètes : pas de consolation vague, mais un « la dernière fois, j’ai fait comme ça, et voilà ce que ça a donné ». L’autre peut alors facilement vous voir comme le partenaire idéal qui sait tout. Un conseil : laissez-le voir que vous aussi paniquez et vous trompez, la relation n’en sera que plus solide.`,
   work: `Imaginons que vous vouliez ouvrir un bar à bubble tea. La première fois, vous choisissez le mauvais emplacement ; la deuxième, la carte est trop compliquée, l’équipe est débordée, et les comptes sont dans le rouge plusieurs mois de suite. D’autres auraient arrêté depuis longtemps ; vous, vous ajustez encore et encore, jusqu’à maîtriser les ficelles de l’emplacement, des prix et des plannings. Ensuite, vos amis qui veulent ouvrir une boutique viennent tous vous voir, et certains vous paient même pour inspecter leur commerce, parce que chacune de vos phrases a été payée de votre poche. Seulement, le jour où l’un de vos conseils ne fonctionne pas, la déception sera plus forte qu’envers un consultant ordinaire.`,
   tips: [`Arrêtez de vous reprocher les mauvais chemins d’autrefois : ces erreurs sont justement la raison pour laquelle on vous fera confiance.`, `Quand on vous dit « il n’y a que toi qui puisses faire ça », prenez un temps pour distinguer si vous voulez vraiment accepter ou si c’est votre fierté qui parle.`, `Avant d’accepter d’aider, fixez le périmètre et le prix, et une fois la mission accomplie, rendez la scène.`]
  },
  '3/6': {
   title: `Celui qui a trébuché dans sa jeunesse, puis est monté sur le toit pour comprendre l’ensemble`,
   summary: `Votre vie ressemble à un film en trois actes. Dans le premier acte, les lignes 3 et 6 sont toutes deux dans l’expérimentation, alors votre jeunesse a sans doute été particulièrement « mouvementée » : vous avez changé de travail, de partenaire et de logement plus souvent que les autres. Vers trente ans, vous montez sur le toit pour observer et faire le tri ; vers cinquante ans, vous incarnez toutes ces expériences d’une manière qui inspire confiance.`,
   loop: `Vous vous cognez jusqu’à saigner, puis vous montez sur le toit pour revoir tout cela à froid et comprendre le sens de ces chocs. Mais la ligne 3 ne vous laisse pas rester là-haut indéfiniment : vous redescendez vous cogner encore. À chaque fois, votre vision s’enrichit, jusqu’à faire de vous la personne qui « a tout vécu, et dont la parole a donc du poids ».`,
   love: `Avant trente ans, vos histoires naissent vite et se terminent vite, et vous apprenez de relation en relation ce que vous voulez. La ligne 6 cache en vous l’idéal de « l’âme sœur », alors vous essayez tout en étant déçu. Un conseil : la fin d’une relation ne signifie pas un échec, mais que vous vous rapprochez pas à pas de la personne qui vous convient vraiment. Une fois dans la période du toit, ne refusez pas de redescendre par peur d’être à nouveau blessé.`,
   work: `Vous avez peut-être changé de travail quatre ou cinq fois avant trente ans, au grand souci de vos proches. Après trente ans, vous devenez plus posé, vous voyez les choses d’un cran plus haut que vos collègues et repérez souvent d’un coup d’œil où l’équipe va se tromper. Passé quarante ou cinquante ans, les plus jeunes viennent vous parler de leur carrière, parce que votre expérience ne vient pas des livres : vous l’avez acquise à force de chocs.`,
   tips: [`Le chaos de la jeunesse n’est pas un échec : vous collectez la matière qui fera de vous un modèle plus tard.`, `Si, pendant la période du toit, plus rien ne vous enthousiasme, c’est que vous décantez, pas que vous régressez.`, `Racontez vos échecs : c’est exactement la référence dont les autres ont le plus besoin.`]
  },
  '4/6': {
   title: `Celui que tout le cercle d’amis finit par venir consulter`,
   summary: `Vos occasions et votre influence viennent de votre cercle de proches. La ligne 4 vous fait attacher de l’importance à la confiance et à l’amitié, et un réseau stable est votre fondation ; la ligne 6 divise votre vie en trois étapes, et plus vous avancez, plus vous devenez un exemple digne d’être suivi. Ce n’est pas le bruit que vous faites qui vous rend mémorable, mais la confiance accumulée au fil des années.`,
   loop: `Vous partagez votre expérience dans votre réseau, et vos amis, parce qu’ils vous font confiance, vous transmettent des occasions. Dans la seconde partie de votre vie, vous passez peu à peu de simple membre du cercle à modèle pour tous. Les exigences élevées de la ligne 6 vous permettent de voir clair, et le réseau de la ligne 4 permet à ce que vous voyez de circuler.`,
   love: `Beaucoup de vos histoires commencent par une amitié, parce que vous avez besoin de faire confiance avant d’ouvrir votre cœur. La ligne 6 vous donne de grandes attentes envers votre partenaire, et vous le notez peut-être en silence. Un conseil : l’autre n’est pas là pour passer un examen ; exprimez vos critères et discutez-en, c’est mieux que d’observer seul depuis le toit s’il commet une faute.`,
   work: `Vos bons postes vous viennent surtout d’anciens camarades d’études, d’ex-collègues ou d’amis. Avant trente ans, vous avez peut-être changé plusieurs fois de direction ; après trente ans, vous prenez davantage de recul et voyez les vrais problèmes de l’entreprise. Plus tard, vous êtes souvent celui à qui l’on demande dans votre milieu : « Tu penses que c’est une bonne idée ? » Trouver votre prochaine étape avant de démissionner est la protection la plus concrète de la ligne 4.`,
   tips: [`Votre réseau est fait de confiance accumulée : bien l’entretenir compte plus que rencontrer sans cesse de nouvelles personnes.`, `N’examinez pas chaque personne de votre entourage avec des critères de perfection, vous y compris.`, `Si vous acceptez de partager dans la seconde partie de votre vie, votre influence dépassera de loin ce que vous imaginez.`]
  },
  '4/1': {
   title: `Le train qui avance sûrement sur ses propres rails`,
   summary: `Le 4/1 est le seul profil de « juxtaposition » : votre vie ressemble à une voie ferrée tracée d’avance. La ligne 4 vous fait avancer grâce à votre réseau de proches ; la ligne 1 vous donne une position solide et difficile à ébranler. Vous n’êtes pas du genre à tourner selon le vent, et vous n’en avez pas besoin. Tant que vous restez sur vos propres rails, vous irez très loin, très sûrement.`,
   loop: `Vous abordez votre entourage avec une position bâtie par la recherche, et ceux qui vous font confiance amènent les occasions sur vos rails ; vous les saisissez, et votre position se renforce encore. Quand quelqu’un veut vous entraîner sur une autre voie, vous résistez par instinct, et c’est souvent la bonne réaction.`,
   love: `Une fois engagé dans une relation, vous êtes très stable et très fidèle. Mais vous changez rarement en profondeur votre mode de vie pour l’autre, ce qui peut le faire vous trouver têtu. Un conseil : inutile de devenir quelqu’un d’autre, mais vous pouvez préciser ce que vous pouvez ajuster et ce qui relève de vos rails. Trouver quelqu’un qui apprécie votre stabilité est bien plus simple que de vivre avec quelqu’un qui veut vous changer.`,
   work: `Vous êtes fait pour creuser un même domaine pendant des années et bâtir votre clientèle par le bouche-à-oreille. Comptable, ingénieur ou vétéran d’un secteur, par exemple, vos clients se recommandent les uns aux autres. Si l’on vous conseille « la tendance a changé, reconvertis-toi vite » et que vous vous forcez à faire ce en quoi vous ne croyez pas, cela se passe généralement mal. Votre meilleure stratégie est d’aller plus en profondeur sur vos rails actuels.`,
   tips: [`Votre entêtement est votre stabilité : vous n’avez pas à vous en excuser.`, `Quand on vous pousse à prendre un virage brutal, demandez-vous : est-ce que je suis encore sur mes rails ?`, `Les occasions viennent de vos proches : faites savoir à ceux qui vous font confiance ce que vous faites.`]
  },
  '5/1': {
   title: `Le chef des secours qui arrive avec un épais classeur`,
   summary: `On vous prend souvent pour quelqu’un capable de régler les problèmes : c’est la projection de la ligne 5. Et votre capacité à les régler vraiment vient des recherches solides de la ligne 1. Votre histoire, c’est : la crise arrive, tout le monde se tourne vers vous, vous ouvrez votre classeur et en sortez une solution pensée depuis longtemps. Bien préparé, vous êtes le sauveur ; sans préparation, votre réputation peut chuter lourdement.`,
   loop: `Vous étudiez en silence et accumulez du savoir ; l’extérieur commence à projeter ses attentes et à vous confier les problèmes difficiles. Vous les réglez grâce à vos recherches, votre réputation grandit, et les attentes avec elle. Tant que vous savez vous retirer après chaque intervention pour compléter vos informations, le cycle peut continuer.`,
   love: `Au début, l’autre vous idéalise facilement : vous savez tout, vous êtes fiable. Vous, de votre côté, voulez d’abord bien connaître l’autre pour être sûr avant de vous engager. Un conseil : la projection finit toujours par se briser ; quand l’autre découvre que vous aussi paniquez, que vous aussi ignorez des choses, ne vous retirez pas trop vite, c’est là que la relation commence vraiment.`,
   work: `L’entreprise décroche un projet d’un type jamais traité, et tout le monde se tourne vers vous, parce que vous êtes d’habitude celui qui « a tout vérifié ». Vous acceptez, passez la nuit à vous documenter, et présentez une solution réalisable qui ravit le client. Mais si l’on vous envoie sur un terrain que vous n’avez pas du tout préparé, en cas d’échec on dira : « Finalement, il n’est pas si fort. » Avant d’accepter, vérifiez donc : est-ce un domaine que j’ai étudié ?`,
   tips: [`Votre réputation est votre capital le plus important : sur un terrain inconnu, mieux vaut dire « laissez-moi d’abord étudier la question ».`, `Une fois le problème réglé, retirez-vous : ne laissez pas le rôle de pompier devenir votre emploi à plein temps.`, `Les attentes que les autres projettent sur vous ne sont pas des obligations.`]
  },
  '5/2': {
   title: `Le maître mystérieux appelé en renfort, qui ferme sa porte en rentrant`,
   summary: `Aux yeux des autres, vous avez du poids, et l’on pense facilement à vous quand survient un ennui ; mais au fond, vous voulez simplement rester chez vous à faire ce qui vous plaît. La ligne 5 apporte projections et appels ; la ligne 2 vous donne un talent inné et un fort besoin de solitude. Ce sont souvent les autres qui voient votre don en premier, tandis que vous pensez que « ce n’est rien ».`,
   loop: `Vous vous enfermez pour profiter de votre monde, mais l’extérieur ne cesse de projeter ses attentes et de vous appeler à la rescousse. Vous réglez le problème, et votre réputation attire plus de monde à votre porte. Vous devez apprendre à choisir, sinon vous perdrez votre temps à vous, appel après appel.`,
   love: `Vous donnez souvent une impression un peu mystérieuse, insaisissable, et cela attire. L’autre peut projeter beaucoup de choses sur vous, alors qu’en réalité vous avez seulement besoin d’espace. Un conseil : ne laissez pas l’autre deviner sans cesse ; dites de temps en temps ce que vous pensez, pour qu’il connaisse la vraie personne et non celle qu’il imagine.`,
   work: `Vous êtes peut-être occupé à vos affaires quand la direction vous désigne pour gérer une patate chaude, simplement parce qu’« on sent que tu en es capable ». Vous la gérez grâce à votre talent, et l’on croit encore plus en vous. Mais si vous continuez à accepter ce genre de missions, vous serez de plus en plus épuisé et de plus en plus tenté de disparaître. Apprendre à dire « pas cette fois » vous permet d’intervenir quand cela compte vraiment.`,
   tips: [`Vous ne devez de sauvetage à personne : vous pouvez répondre aux appels de façon sélective.`, `Votre talent a besoin de solitude pour grandir ; la solitude n’est pas une fuite.`, `Avant d’accepter une mission, fixez le périmètre et la durée pour ne pas être prisonnier des attentes.`]
  },
  '6/2': {
   title: `Le modèle né qui contemple le paysage du toit en attendant qu’on vienne le chercher`,
   summary: `Votre vie se joue en trois actes : avant trente ans, vous essayez tout, comme une ligne 3 ; de trente à cinquante ans, vous montez sur le toit pour observer ; après cinquante ans, vous redescendez et devenez quelqu’un dont les autres veulent s’inspirer. La ligne 2 vous donne un talent naturel, et le besoin d’être « appelé ». Inutile de vous presser de faire vos preuves : le temps joue pour vous.`,
   loop: `Depuis le toit, vous regardez le monde avec recul, tout en cultivant votre art dans votre espace. Les autres voient votre talent et votre calme, et viennent vous chercher. Quand vous intervenez, vous touchez souvent juste, puis vous remontez sur le toit. Plus vous avancez en âge, plus on vient vous chercher.`,
   love: `Vous avez un idéal élevé du partenaire, et vous observez souvent, en attendant « la bonne personne ». Vous avez aussi besoin de beaucoup de solitude, ce qui peut donner à l’autre une impression de distance. Un conseil : personne ne correspond parfaitement à votre idéal, pas même vous. Autorisez l’autre à être imparfait, et autorisez-vous à descendre un peu du toit.`,
   work: `Vous avez peut-être changé plusieurs fois de travail avant trente ans ; après, les luttes de pouvoir au bureau vous laissent froid, vous voulez juste vous concentrer sur ce que vous faites bien. Mais votre talent est remarqué par votre hiérarchie, et l’on vous désigne pour former les nouveaux ou gérer un projet clé. Après cinquante ans, vous constaterez que beaucoup vous consultent comme une « référence du métier ».`,
   tips: [`La froideur de la période du toit est une décantation : n’en concluez pas que vous manquez de passion.`, `Quand quelqu’un vient vous chercher, c’est que votre talent a été vu : vous pouvez essayer de sortir.`, `Votre idéal est précieux, mais ne vous en servez pas pour refuser tout le monde.`]
  },
  '6/3': {
   title: `Celui qui a trébuché tout du long et finit par devenir un modèle authentique`,
   summary: `Votre vie se joue aussi en trois actes, mais la ligne 3 fait que, même sur le toit, vous n’arrêtez jamais d’expérimenter. Vous vous heurtez aux murs plus souvent que les autres lignes 6, et vos relations comme votre travail connaissent plus facilement des débuts et des ruptures. Le modèle que vous devenez n’est pas sans défaut : c’est celui qui dit « je suis vraiment tombé, et je me suis vraiment relevé ».`,
   loop: `Vous montez sur le toit pour observer et comprendre l’ensemble, mais la ligne 3 vous fait redescendre vous cogner encore ; après chaque choc, vous remontez faire le tri. Ce va-et-vient vous donne une vision très complète et une compréhension fine des réalités de la vie.`,
   love: `Vous avez peut-être connu beaucoup de « débuts et de fins », et il vous arrive de douter d’être fait pour une relation durable. En réalité, la ligne 3 a besoin de chocs pour savoir ce qui fonctionne, et la ligne 6 cherche sans cesse quelqu’un digne de confiance. Un conseil : ne concluez pas que la prochaine relation se brisera parce que plusieurs l’ont fait. À chaque fois, vous savez plus clairement ce que vous voulez.`,
   work: `Vous avez peut-être traversé plusieurs domaines, et votre CV paraît décousu. Mais vers le milieu et la fin de votre parcours, vous découvrez que toutes ces expériences se relient et vous donnent une vision plus large que celle d’un spécialiste d’un seul domaine. Par exemple, vous avez fait de la vente, du marketing, connu la faillite d’une start-up, et vous devenez un consultant ou un manager très concret, qui ose dire la vérité.`,
   tips: [`Votre historique de chutes fait votre force de conviction : inutile de le cacher.`, `Quand une relation ou un travail se termine, la question est « qu’ai-je appris ? », et non « j’ai encore échoué ».`, `Une fois que vous y voyez clair depuis le toit, autorisez-vous à redescendre essayer encore.`]
  }
 },

 lines: {
  1: {
   misread: `Les autres vous trouvent trop réfléchi, lent à agir ; vous-même vous demandez souvent si vous manquez de confiance, puisqu’il vous faut tout vérifier avant d’oser bouger.`,
   mindset: `La recherche est votre fondation, pas de la procrastination. Quand vous avez assez d’informations, votre sentiment de sécurité apparaît, et vous devenez alors plus solide que quiconque.`,
   examples: [`Avant de changer de téléphone, vous faites un tableau comparatif des caractéristiques, des tests et des prix de trois modèles, et vous ne commandez qu’après ; sinon, même acheté, vous ne seriez pas tranquille.`, `Dans une nouvelle entreprise, vous parcourez dès la première semaine les anciens documents du dossier partagé, parce que vous voulez comprendre comment les choses fonctionnent ici.`]
  },
  2: {
   misread: `Les autres vous trouvent solitaire, peu sociable, voire un peu paresseux ; vous-même ne comprenez pas bien pourquoi on dit que vous êtes doué.`,
   mindset: `Votre talent mûrit dans la solitude, inutile de faire votre promotion. Laissez la porte entrouverte et attendez que les bonnes personnes viennent vous chercher.`,
   examples: [`Vous publiez en story une illustration faite à la maison sans y penser, et un ami vous écrit aussitôt : « C’est toi qui l’as dessinée ? Tu pourrais faire les faire-part de mon mariage ? »`, `Un collègue vous voit réparer l’imprimante en deux temps trois mouvements et vous demande, étonné, comment vous savez faire ; vous découvrez alors que ce n’est pas si simple pour tout le monde.`]
  },
  3: {
   misread: `Votre entourage s’inquiète souvent pour vous : vous pourriez suivre la voie de ceux qui vous ont précédé, mais vous tenez à faire le détour vous-même. À force de vous cogner, vous finissez aussi par vous demander si vous n’êtes pas plus maladroit que les autres.`,
   mindset: `Vous n’échouez pas, vous expérimentez. Chaque chose qui ne marche pas est une donnée fiable qui indique, à vous et à votre entourage, quel chemin éviter. Ce que vous avez vérifié vous-même est plus crédible que tout ce que l’on vous rapporte.`,
   examples: [`Un ami vous recommande une méthode de budget très à la mode ; au bout de deux semaines, vous voyez qu’elle ne vous convient pas, vous la modifiez trois fois et finissez par bricoler un système bien à vous, que vous utilisez vraiment.`, `En apprenant à cuisiner, vous respectez rarement les quantités de la recette ; vous avez trop salé, brûlé plusieurs fois, et aujourd’hui, rien qu’en regardant la couleur dans la poêle et en sentant l’odeur, vous savez si la cuisson est à point.`]
  },
  4: {
   misread: `Les autres pensent que vous ne comptez que sur vos relations, ou que vous êtes trop attaché au passé et n’osez pas changer ; vous-même trouvez les changements d’environnement particulièrement pénibles.`,
   mindset: `Votre influence vient de la confiance. Les occasions viennent de vos proches, et trouver votre prochaine destination avant de quitter un endroit est votre sagesse de survie.`,
   examples: [`Vous recommandez un restaurant, et vos amis réservent sans hésiter, parce que « si tu dis que c’est bon, c’est forcément bon ».`, `Vous voulez démissionner depuis longtemps mais restez quand même ; ce n’est que lorsqu’un ancien collègue vous propose de rejoindre son entreprise que vous remettez votre démission l’esprit tranquille.`]
  },
  5: {
   misread: `Les gens que vous rencontrez pour la première fois vous imaginent souvent plus capable que vous ne l’êtes, et vous refilent spontanément les problèmes difficiles ; si le résultat n’est pas à la hauteur, leur réaction est particulièrement vive, comme si vous les aviez trahis.`,
   mindset: `L’image que les autres ont de vous est en partie leur propre imagination. Vous savez réellement proposer des solutions concrètes, mais choisissez d’abord, précisez jusqu’où vous pouvez aller, et prenez du recul une fois le travail fait : c’est ainsi que votre réputation se préserve.`,
   examples: [`Le premier jour, un nouveau collègue vous refile le tableau qu’il n’arrive pas à faire : « Tout le monde dit qu’il faut te demander. » Alors que vous ne le maîtrisez pas vraiment non plus.`, `Aux réunions de famille, l’assurance, le téléphone et les disputes des aînés attendent tous que vous vous en occupiez, comme si vous étiez le sauveur universel de la famille.`]
  },
  6: {
   misread: `Les autres vous trouvent froid, distant, toujours à observer de côté ; et à un certain âge, il se peut que plus rien ne vous enthousiasme soudain, au point de croire que vous avez perdu votre passion.`,
   mindset: `Votre vie a trois étapes. Les essais avant trente ans et l’observation de trente à cinquante ans préparent tous à faire de vous un modèle après cinquante ans. Observer, c’est décanter, pas abandonner.`,
   examples: [`À vingt ans et quelques, vous changiez souvent de travail et de partenaire ; après trente ans, dans les soirées, vous êtes devenu celui qui sirote tranquillement son verre en voyant tout plus clairement que les autres.`, `Quand des amis se disputent, vous ne vous pressez pas de prendre parti ; vous dites une phrase qui calme tout le monde, et ensuite chacun vient vous parler en privé.`]
  }
 },

 typeAuth: {
  'generator|emotional': {
   story: `Votre centre sacral est comme une batterie bien chargée : vous tenez longtemps quand vous faites ce à quoi vous répondez. Mais votre vraie réponse n’apparaît clairement qu’après un cycle complet de votre vague émotionnelle. Sur le moment, votre corps peut dire « oui », et en haut de la vague, tout vous semble formidable. Accordez-vous une nuit, voire quelques jours : si, une fois calme, votre corps le veut toujours, alors c’est vraiment oui.`,
   scene: `Un ami enthousiaste vous propose de vous associer pour ouvrir une boutique. Mauvaise approche : porté par l’ambiance, vous tapez sur la table en disant « D’accord, on le fait », et trois semaines plus tard, vous réalisez que vous n’avez aucune envie de tenir boutique tous les jours. Bonne approche : dire « Ça a l’air intéressant, laisse-moi quelques jours », puis, quelques jours plus tard, une fois apaisé, demander à votre ami de vous reposer la question, et écouter comment votre corps répond.`
  },
  'generator|sacral': {
   story: `Votre réponse se trouve dans la réaction immédiate de votre corps. Quand on vous pose une question fermée, vous émettez d’abord un « hum-hum » ou un « hmm-mm » : c’est la réponse. Les raisons que votre tête ajoute ensuite comptent généralement peu. Inutile de réfléchir longtemps ; trop réfléchir finit même par recouvrir la vraie réponse.`,
   scene: `Un collègue vous propose une randonnée ce week-end. Mauvaise approche : votre tête se met à calculer « je devrais faire plus de sport », « refuser, ce n’est pas sympa », vous acceptez à contrecœur et êtes épuisé tout du long. Bonne approche : écouter le premier son qui sort de vous ; si c’est un « hmm-mm » étouffé, dites simplement que ce sera pour une autre fois ; si c’est un « hum-hum » plein d’entrain, alors en route.`
  },
  'mg|emotional': {
   story: `Vous allez vite et avez souvent envie de foncer ; mais votre autorité est émotionnelle, donc la vraie réponse n’arrive qu’une fois la vague apaisée. Laissez d’abord votre corps répondre, accordez-vous ensuite un peu de temps, puis, une fois sûr, informez les personnes concernées et lâchez-vous à votre vitesse. Soyez rapide dans l’exécution, pas dans la décision.`,
   scene: `Votre responsable vous propose de prendre un nouveau projet transversal. Mauvaise approche : sur le moment, vous êtes ultra-enthousiaste, vous dites oui tout de suite et créez le groupe de discussion ; une semaine plus tard, l’émotion retombée, vous découvrez que vous n’arrivez même pas à boucler ce que vous avez déjà. Bonne approche : dire « Ça m’intéresse beaucoup, je vous réponds demain », et si le lendemain, au calme, vous en avez toujours envie, annoncer à votre responsable et à l’équipe que vous vous lancez.`
  },
  'mg|sacral': {
   story: `Vous décidez par la réponse de votre corps, et vous agissez vite. Dès que la réponse apparaît, elle est là ; ensuite, informer les personnes concernées avant d’agir vous épargne beaucoup de malentendus. Vous sautez des étapes, vous faites plusieurs choses à la fois : ce n’est pas de la négligence, c’est votre efficacité. Pensez simplement à revenir de temps en temps vérifier ce qui a pu vous échapper.`,
   scene: `Un ami vous propose de vous inscrire avec lui au marathon du mois prochain. Mauvaise approche : votre tête dit « je dois avoir l’esprit de défi », vous vous inscrivez sans écouter votre corps, et l’entraînement devient une torture. Bonne approche : écouter la première réponse de votre corps ; si c’est « hum-hum », inscrivez-vous et prévenez votre famille : « Les prochains week-ends, je cours le matin », pour qu’elle ne se sente pas brusquement délaissée.`
  },
  'manifestor|emotional': {
   story: `Vous avez la capacité d’initier, mais votre autorité émotionnelle vous demande d’attendre que la vague se stabilise avant de décider d’initier ou non. Les élans du sommet de la vague sont souvent regrettés au creux. Une fois les choses claires, informez les personnes concernées, puis agissez. Vous aurez beaucoup moins de colère, et beaucoup moins de résistance.`,
   scene: `Un soir, vous avez soudain très envie de démissionner pour partir en PVT à l’étranger. Mauvaise approche : rédiger et envoyer votre lettre de démission le soir même, sans en parler à vos proches le lendemain ; tout le monde est stupéfait, et vous commencez à douter de vous. Bonne approche : attendre quelques jours, voir si l’idée tient aussi bien en haut qu’en bas de la vague ; une fois sûr, parler d’abord de votre projet à votre responsable et à votre famille, puis remettre votre démission.`
  },
  'manifestor|splenic': {
   story: `Votre intuition ne parle qu’une fois, dans l’instant, et vous avez la capacité d’initier directement : vos décisions peuvent donc être très rapides. Le « c’est ça » ou le « quelque chose cloche » du premier instant est le plus juste ; à trop réfléchir, votre tête finit par vous convaincre d’autre chose. Une fois décidé, pensez à informer les personnes concernées.`,
   scene: `En visitant un logement, dès que vous entrez dans un appartement, quelque chose vous gêne, alors que tout est parfait sur le papier. Mauvaise approche : l’agent insiste, vous vous convainquez que « le prix est vraiment intéressant » et signez, puis vous vous y sentez de plus en plus mal. Bonne approche : faire confiance à cette sensation fugace et dire non directement ; quand le suivant vous semble juste, décider sur-le-champ et annoncer à vos proches : « J’ai choisi. »`
  },
  'manifestor|ego-m': {
   story: `Votre réponse vient de ce que vous « voulez » vraiment, et vous l’entendez au moment où vous le dites à voix haute. Faites attention au ton de votre voix quand vous dites « je veux… » ou « je ne veux pas… » : c’est votre autorité. Vous n’avez pas à justifier vos envies ; informez les autres, puis agissez.`,
   scene: `Un ami vous propose d’investir dans sa nouvelle entreprise. Mauvaise approche : par amitié et parce qu’on vous dit que « c’est une occasion rare », vous acceptez quelque chose dont vous n’avez pas envie au fond, et vous vous sentez piégé ensuite. Bonne approche : écouter ce qui sort de votre bouche ; si c’est « en fait, je n’ai pas envie de m’occuper de ça », refusez directement ; si c’est « j’ai envie d’en être », informez vos proches puis engagez-vous.`
  },
  'projector|emotional': {
   story: `Le plus important pour vous est d’attendre d’être reconnu et invité, et une fois l’invitation reçue, d’attendre encore que votre vague émotionnelle soit passée avant de répondre. Sur le moment, vous êtes peut-être ravi d’être enfin reconnu, mais ce n’est pas forcément de la clarté. Attendez quelques jours : si, au calme, cela vous semble toujours juste, acceptez.`,
   scene: `Un chasseur de têtes vous appelle pour un poste de manager dans une nouvelle entreprise, avec de belles conditions. Mauvaise approche : ému d’être enfin reconnu, vous acceptez sur-le-champ, et une fois en poste vous découvrez que la culture de l’équipe ne vous convient pas du tout. Bonne approche : le remercier et dire qu’il vous faut quelques jours, observer pendant ce temps ce que vous ressentez pour ce poste en haut et en bas de la vague ; si, au calme, vous voulez toujours y aller, acceptez.`
  },
  'projector|splenic': {
   story: `Vous attendez d’être invité, et au moment où l’invitation arrive, votre intuition vous donne immédiatement la réponse. Ce « oui » ou ce « non » très discret et très rapide ne se dit qu’une fois. N’attendez pas que votre tête ait tout compris pour décider, car elle recouvre souvent ce que l’intuition a dit.`,
   scene: `Une nouvelle connaissance vous propose de monter un studio ensemble. Mauvaise approche : sur le moment, votre intuition trouve que quelque chose cloche, mais vous vous dites « il est gentil, les occasions sont rares » et acceptez à contrecœur ; ensuite, la collaboration bloque partout. Bonne approche : être attentif à la sensation de votre corps à l’instant de l’invitation ; si quelque chose cloche, déclinez poliment ; si c’est juste, acceptez, sans trop réfléchir.`
  },
  'projector|ego-p': {
   story: `Vous attendez d’être invité, et une fois l’invitation reçue, demandez-vous : « Qu’est-ce que j’y gagne ? Est-ce que je le veux vraiment ? » Ce n’est pas de l’égoïsme : votre volonté ne s’engage que pour ce qui en vaut vraiment la peine. Dites ces questions à voix haute, et vous entendrez votre propre réponse.`,
   scene: `Votre responsable vous propose de diriger une nouvelle équipe. Mauvaise approche : flatté, vous acceptez sans penser à une augmentation, à vos marges de manœuvre ni à votre véritable envie, et vous vous épuisez sans contrepartie. Bonne approche : en parler à un ami de confiance, écouter si ce qui sort de votre bouche est « je veux ce poste » ou « je n’ose juste pas refuser », puis décider si vous acceptez, en négociant clairement les conditions.`
  },
  'projector|self': {
   story: `Votre réponse se trouve dans le son de votre propre voix. Une fois l’invitation reçue, parlez-en avec une personne de confiance, non pour qu’elle vous conseille, mais pour vous entendre dire ce que vous dites. Quand la direction est juste, vous ressentez en parlant quelque chose comme « oui, c’est moi ».`,
   scene: `Un ami vous propose de partir vivre ensemble dans une autre ville. Mauvaise approche : peser seul le pour et le contre dans votre tête, de plus en plus confus, et finir par décider au hasard. Bonne approche : prendre un café avec une personne de confiance et lui raconter la chose. Vous vous entendrez peut-être dire « en fait, j’ai très envie de changer d’air », ou bien « je crois que je veux juste fuir ma situation actuelle » : la réponse est dans cette phrase.`
  },
  'projector|mental': {
   story: `Vous n’avez pas d’autorité corporelle intérieure : la clarté vous vient de l’environnement et de la conversation. Une fois l’invitation reçue, trouvez plusieurs personnes différentes pour vous servir de caisse de résonance, et exposez vos idées dans des lieux différents. L’important n’est pas leur avis, mais de vous comprendre peu à peu en parlant.`,
   scene: `Vous recevez une admission en master et, en même temps, une offre d’emploi. Mauvaise approche : vous enfermer dans votre chambre pour faire des listes, ou décider sur une phrase de vos parents. Bonne approche : en parler séparément avec un ancien de votre école, un vieil ami et un membre de votre famille, une fois dans un café, une fois dans un parc, et remarquer quelle option devient plus claire et plus rassurante à mesure que vous en parlez.`
  },
  'reflector|lunar': {
   story: `Vous êtes comme un miroir : ce que vous ressentez change chaque jour avec l’environnement et les personnes autour de vous. Une décision importante demande environ 28 jours, le temps d’un cycle lunaire complet. Pendant cette période, ressentez, parlez avec des personnes de confiance, écoutez ce que vous pensez aujourd’hui et ce que vous penserez dans deux semaines : la réponse émergera peu à peu.`,
   scene: `On vous propose une colocation dans un nouvel appartement. Mauvaise approche : l’ambiance est super le jour de la visite, vous signez le jour même, et un mois plus tard vous découvrez que vous ne vous y sentez pas bien du tout. Bonne approche : dire que vous avez besoin d’un mois pour réfléchir, aller vous promener plusieurs fois dans le quartier, en parler avec quelques amis, observer ce que vous ressentez selon les jours ; si, au bout d’un mois, cela vous semble toujours bien, décidez.`
  }
 },

 channels: {
  '1-8': `Vous avez une façon de vous exprimer très singulière, et en étant simplement vous-même, vous devenez naturellement un exemple pour les autres. Vous partagez peut-être votre style ou votre mode de vie sur les réseaux, sans suivre la mode, et certains s’en inspirent en silence. Votre créativité n’a pas besoin de l’approbation de tous : être vu par les bonnes personnes suffit.`,
  '2-14': `Vous êtes comme celui qui détient les clés : vous savez où investir les ressources et les efforts. Dans une équipe, vous décidez peut-être tout naturellement de la répartition du budget et de la direction à prendre, et la direction à laquelle votre corps répond est souvent la bonne. Quand vous faites ce qui vous engage vraiment, l’argent et les ressources suivent.`,
  '3-60': `Votre énergie fonctionne par à-coups, comme un interrupteur : parfois bloquée longtemps, puis soudain une grande percée. Vous butez peut-être sur un obstacle pendant des mois, et un jour tout s’éclaire et vous changez complètement de méthode. Les périodes de blocage ne sont pas de la stagnation : le changement s’y prépare.`,
  '4-63': `Votre esprit a l’habitude de douter, puis de chercher la réponse par la logique. Quand on vous dit « cette action va forcément monter », votre premier réflexe est : « Sur quoi tu te fondes ? » Vous savez repérer les schémas et les failles, et l’analyse ou le débogage vous conviennent bien. Un conseil : le doute est très utile pour les choses extérieures, mais l’appliquer à vous-même est épuisant.`,
  '5-15': `Vous avez votre propre rythme, et les habitudes fixes comptent beaucoup pour vous. Vous vous levez peut-être chaque jour à la même heure et prenez votre petit-déjeuner au même endroit : les autres trouvent ça monotone, vous y puisez votre stabilité. Vous acceptez aussi très bien les gens aux rythmes différents, mais quand quelqu’un bouscule votre emploi du temps, plus rien ne va.`,
  '6-59': `Vous savez facilement abolir la distance entre les personnes, et les autres s’ouvrent à vous en peu de temps. En soirée, quelques phrases vous suffisent pour qu’un inconnu vous confie ce qu’il a sur le cœur. Cette énergie touche aussi à l’intimité et à la coopération : choisissez de qui vous rapprocher une fois vos émotions apaisées.`,
  '7-31': `Vous êtes un leader né, mais votre influence est la plus forte quand on vous reconnaît et vous désigne. Lors d’un exposé de groupe, on vous choisit peut-être naturellement comme porte-parole, et l’on suit volontiers la direction que vous proposez. Si vous vous emparez de la place de leader, vous rencontrez souvent de la résistance ; attendez qu’on vous demande « par où tu penses qu’on devrait aller ? ».`,
  '9-52': `Vous savez rester concentré longtemps sur une seule chose, tenir en place et regarder les détails. Vous passez peut-être un après-midi entier à ajuster la mise en forme d’un tableau, là où d’autres auraient abandonné depuis longtemps, et vous y prenez plaisir. Dès qu’il s’agit d’une chose à laquelle vous répondez, votre concentration devient un laser qui pousse les détails à la perfection.`,
  '10-20': `Vous vivez dans l’instant, et être vous-même vous vient tout naturellement. En réunion, vous dites peut-être directement « ce projet ne me plaît pas, c’est tout » : ce n’est pas un caprice, vous savez simplement très bien qui vous êtes. Votre présence même rappelle aux autres qu’on n’est pas obligé de vivre selon les attentes des autres.`,
  '10-34': `Vous avez une grande force d’action, et vous agissez uniquement à votre manière. Quand on vous explique comment mieux faire, vous acquiescez peut-être, puis faites quand même à votre façon. Ce n’est pas de la rébellion : votre force vient justement de votre fidélité à vous-même. Pensez simplement à attendre de répondre avant de vous lancer.`,
  '10-57': `Vous savez intuitivement comment bien vivre et vivre avec beauté. En entrant dans une pièce, vous savez peut-être aussitôt comment disposer les meubles, ou voyez d’un coup d’œil que quelqu’un ne va pas bien aujourd’hui. Votre intuition ne parle qu’une fois, dans l’instant ; faites-lui confiance, elle vous évite souvent des ennuis.`,
  '11-56': `Vous avez la tête pleine d’idées et d’histoires, et vous savez raconter vos expériences de façon vivante. Au retour d’un voyage, vos récits captivent vos amis, qui ont envie de partir avec vous. Votre valeur est de stimuler la réflexion des autres : inutile de réaliser chaque idée vous-même, la partager, c’est déjà agir.`,
  '12-22': `Votre expression est très communicative, mais elle dépend de votre humeur. Quand vous êtes bien, dès que vous ouvrez la bouche, toute la salle est captivée ; quand l’humeur n’y est pas, vous forcer à être sociable ne fait que créer un malaise. Attendez que l’émotion soit juste pour dire les choses importantes : vos paroles toucheront alors vraiment.`,
  '13-33': `Vous êtes comme un témoin : les autres vous confient facilement leurs pensées et leurs secrets. Dans un train, vous écoutez peut-être toute l’histoire de la vie d’un inconnu. Vous gardez ces histoires en vous, y revenez quelque temps plus tard pour les mettre en ordre, puis les transformez en sagesse à partager. Vous avez besoin de temps en retrait pour digérer.`,
  '16-48': `Votre talent vient de la pratique répétée. Vous avez peut-être appris le piano, la programmation ou la cuisine depuis l’enfance, en vous exerçant encore et encore jusqu’à ce que cela paraisse facile aux autres. Vous tenez beaucoup à la profondeur, et quand vous vous trouvez pas encore assez bon, vous hésitez à montrer votre travail ; en réalité, votre niveau est suffisant depuis longtemps.`,
  '17-62': `Vous savez transformer les idées en structures claires et en détails. En réunion, quand tout le monde part dans tous les sens, votre « voyons cela en trois points » remet de l’ordre. Vos avis sont très organisés, mais pensez à attendre qu’on vous les demande, sinon on risque de croire que vous faites la leçon.`,
  '18-58': `Vous voyez au premier coup d’œil ce qui pourrait être mieux, avec une forte envie de le corriger. Au restaurant, à peine la commande passée, vous réfléchissez peut-être déjà à comment rendre le service plus fluide. Utilisée là où on vous y invite, cette énergie est un trésor ; quand personne ne l’a demandée, les autres se sentent facilement critiqués.`,
  '19-49': `Vous êtes très sensible aux besoins de votre entourage : qui n’a pas assez mangé, qui est laissé de côté, vous le voyez. Dans vos relations, vous tenez beaucoup à l’équité et aux principes, et quand vous vous sentez lésé, vous coupez net. Vous êtes fait pour prendre soin d’un groupe, mais pensez aussi à vérifier que vos propres besoins sont satisfaits.`,
  '20-34': `Vous transformez directement votre énergie en action : vous êtes toujours très occupé, et cela vous rend charismatique. Quand un ami parle de déménager, vous avez peut-être déjà retroussé vos manches pour porter les cartons. Votre efficacité est impressionnante, mais vous n’êtes de plus en plus heureux en étant occupé que si votre corps répond à ce que vous faites ; dans la mauvaise direction, il ne reste que la fatigue.`,
  '20-57': `Votre intuition est très vive dans l’instant, et vous dites souvent l’essentiel sans réfléchir. Un ami hésite encore à signer un contrat, et votre « il y a un truc bizarre ici » touche le problème du doigt. Votre perception arrive vite et repart vite : elle est la plus juste au moment où vous la dites, et il est difficile d’expliquer pourquoi après coup.`,
  '21-45': `Vous savez gérer les ressources et les personnes, et vous êtes fait pour prendre les décisions matérielles. Quand la famille doit acheter une voiture ou l’entreprise répartir un budget, on vous laisse naturellement trancher. Vous avez besoin de garder la main, et être contrôlé en tout vous met mal à l’aise ; mais n’oubliez pas qu’un bon gestionnaire prend soin de chacun.`,
  '23-43': `Vous avez souvent des intuitions très singulières : une fois la chose comprise, elle vous paraît évidente, mais les autres ne suivent pas tout de suite. Vous proposez peut-être une nouvelle méthode en réunion, et tout le monde a l’air perplexe. Attendez qu’on vous interroge, et expliquez-vous d’une manière que l’autre peut comprendre : votre génie ne passera pas pour de la bizarrerie.`,
  '24-61': `Votre esprit aime réfléchir aux grandes questions de la vie, et vous vous perdez souvent dans vos pensées. Sous la douche ou en marchant, la réponse peut surgir d’un coup. Inutile de vous forcer à conclure : l’inspiration a son propre calendrier, et ne laissez pas les questions qui vous trottent dans la tête devenir une raison de ne pas dormir.`,
  '25-51': `Vous avez le courage de foncer vers l’inconnu et aimez être le premier à essayer. Vos amis hésitent encore à faire du parachutisme, vous êtes déjà inscrit. Vous grandissez aussi souvent à travers des chocs inattendus : ces moments qui vous font sursauter vous aident à mieux vous connaître et réveillent aussi votre entourage.`,
  '26-44': `Vous comprenez très bien ce dont les gens ont besoin, et vous êtes doué pour vendre, convaincre et transmettre. Vous présentez un soin pour la peau, et vos amis ont aussitôt envie de l’acheter. Vous vous souvenez aussi des expériences passées et savez ce qui risque de mal tourner. Ce talent donne toute sa mesure au service de ce en quoi vous croyez sincèrement.`,
  '27-50': `Vous êtes né pour prendre soin des autres, et vous accordez beaucoup d’importance aux valeurs et aux responsabilités. Quand un ami est malade, vous êtes le premier à lui apporter une soupe, et vous portez sans bruit les affaires de famille. Vous êtes le gardien du groupe, mais avant de prendre soin des autres, vérifiez qu’on prend aussi soin de vous, sinon les responsabilités vous écraseront.`,
  '28-38': `Vous êtes prêt à vous battre jusqu’au bout pour ce qui a du sens : quand on vous dit d’abandonner, vous tenez à essayer encore. Par exemple, un projet auquel personne ne croyait, vous l’avez porté deux ans jusqu’à ce qu’il décolle. Votre lutte a sa valeur, mais pensez à vous demander : ce combat vaut-il vraiment la peine que je le mène ?`,
  '29-46': `Une fois engagé, vous vous donnez entièrement jusqu’au bout. Vous promettez peut-être d’aider un ami à organiser un événement, et finissez par tout prendre en charge, du lieu au déroulé. Vous réussissez souvent là où les autres abandonnent, alors attendez la réponse de votre corps avant de dire oui, car une fois engagé, il est difficile de faire marche arrière.`,
  '30-41': `Vous avez en vous beaucoup de rêves et d’envies d’expériences, et une soif de nouveauté. Vous planifiez peut-être depuis longtemps un certain voyage ou un certain mode de vie. Ce désir a beaucoup d’énergie, mais l’attente et la réalité sont souvent décalées : donnez du temps à vos ressentis, et ne cherchez pas à réaliser chaque rêve immédiatement.`,
  '32-54': `Vous avez l’ambition de vous élever, et vous savez juger ce qui mérite d’être cultivé dans la durée. Vous avez peut-être commencé en bas de l’échelle et gravi les échelons en choisissant bien vos moments. Vous tenez beaucoup à ce que vos efforts se transforment en résultats concrets ; entouré de personnes qui savent vous reconnaître, vous montez plus vite et plus sûrement.`,
  '34-57': `Vous réagissez dans l’instant par l’intuition et la force, à une vitesse extrême. Face à une situation soudaine, par exemple un enfant qui manque de tomber, vous êtes déjà là pour le rattraper. Votre corps sait très bien comment survivre, sans avoir besoin de réfléchir d’abord. Tant que vous écoutez sa réponse, vous vous trompez rarement.`,
  '35-36': `Vous recherchez des expériences et des sensations nouvelles, et vous avez envie de tout essayer. Vous avez peut-être pratiqué le surf, la poterie, les cocktails, un peu de tout. Ces expériences en dents de scie vous ont beaucoup appris, mais l’attrait de la nouveauté vient vite et repart vite : attendez que vos émotions se calment avant de vous lancer dans la prochaine aventure.`,
  '37-40': `Vous accordez beaucoup d’importance aux engagements, et ce que vous donnez doit être équilibré par ce que vous recevez. Dans votre famille ou votre cercle d’amis, c’est souvent vous qui organisez les repas et prenez soin de tout le monde. Mais vous avez aussi besoin de repos et de reconnaissance ; quand vous avez l’impression de donner sans retour, vous avez soudain envie de tout quitter. Exprimez clairement vos conditions, et vos relations seront plus stables.`,
  '39-55': `Vos émotions varient beaucoup : euphorique une seconde, abattu la suivante, et pas forcément pour une raison précise. Ce n’est pas un problème chez vous, c’est votre design. Vos émotions vous apportent aussi une grande richesse spirituelle et créative, et beaucoup d’œuvres naissent justement dans les moments de creux.`,
  '42-53': `Vous savez mener les choses du début à la fin, et vous grandissez de cycle en cycle. Quand vous commencez une nouvelle habitude, vous voulez la mener jusqu’au bout d’un cycle complet. Être interrompu en cours de route vous dérange beaucoup. Avant de commencer, vérifiez que votre corps répond, car une fois lancé, vous voudrez aller jusqu’au bout.`,
  '47-64': `Votre esprit est souvent rempli d’images et de fragments, confus au début, jusqu’à ce que leur sens se dégage soudain un peu plus tard. Vous vous rappelez peut-être un événement d’il y a plusieurs années et comprenez tout à coup l’effet qu’il a eu sur vous. Ne vous forcez pas à tout comprendre tout de suite : la réponse s’assemblera d’elle-même au bon moment.`
 },

 centersOpen: {
  head: `Avec un centre de la Tête ouvert, votre esprit se remplit facilement des questions des autres. Un ami vous demande en passant « quel est le sens de la vie ? », et vous y pensez peut-être toute la nuit. En faisant défiler votre téléphone avant de dormir, les soucis des autres vous rendent anxieux aussi. Rappelez-vous : ce n’est pas une question à laquelle je dois répondre.`,
  ajna: `Avec un centre Ajna ouvert, vous comprenez très bien les points de vue différents. En réunion, vous trouvez que A a raison, puis que B a raison aussi, tout en ressentant la pression de prendre tout de suite une position bien tranchée. En réalité, vous pouvez dire « j’y réfléchis encore » : cette souplesse est votre sagesse.`,
  throat: `Avec un centre de la Gorge ouvert, ce que vous craignez le plus, c’est le silence gênant. Trois secondes de silence en réunion, et vous ne pouvez pas vous empêcher de combler le vide, puis vous avez l’impression d’en avoir trop dit. En soirée aussi, vous vous précipitez peut-être pour prendre la parole. Essayez d’attendre qu’on vous interroge : c’est là que vos paroles ont le plus de force et sont le mieux entendues.`,
  g: `Avec un centre G ouvert, votre sentiment d’identité change avec l’environnement. Un nouveau travail, une nouvelle ville, et vous semblez devenir quelqu’un d’autre. Vous vous demandez souvent « qui suis-je vraiment, et où vais-je ? ». En réalité, il vous suffit de choisir les bons lieux et les bonnes personnes, et la direction apparaîtra d’elle-même.`,
  heart: `Avec un centre du Cœur ouvert, vous avez facilement envie de faire vos preuves. Un collègue vous dit « tu peux boucler ça en une semaine, non ? » : il vous faudrait deux semaines, mais vous dites oui en serrant les dents. En faisant vos achats, un simple « vous le méritez » peut aussi vous convaincre. Vous n’avez pas à prouver votre valeur : faites selon vos moyens.`,
  sacral: `Avec un centre sacral ouvert, vous vous laissez facilement entraîner par l’énergie des autres. En sortie avec des amis qui s’amusent jusqu’à minuit, vous tenez le rythme, et ce n’est qu’en rentrant que vous vous effondrez. Vous ne savez pas quand vous arrêter, parce que cette énergie n’était pas la vôtre au départ. Apprendre à partir avant d’être épuisé, voilà votre leçon.`,
  spleen: `Avec un centre de la Rate ouvert, vous êtes très sensible à l’état de votre corps et à celui des autres. Vous savez peut-être qu’une relation ou un travail n’est pas sain pour vous, mais vous ne lâchez pas, parce que « au moins, c’est familier et rassurant ». Ce qui vous rassure n’est pas forcément bon pour vous : essayez de le laisser partir.`,
  sp: `Avec un plexus solaire ouvert, vous amplifiez les émotions de votre entourage. Un collègue est de mauvaise humeur, et vous êtes morose toute la journée ; vos proches se disputent, et vous vous précipitez pour jouer les médiateurs. Pour éviter le conflit, vous ravalez souvent ce que vous pensez vraiment. Demandez-vous d’abord : est-ce mon émotion, ou celle de quelqu’un d’autre ?`,
  root: `Avec un centre racine ouvert, la pression vous pousse facilement à courir. Dès qu’une notification apparaît, vous voulez répondre tout de suite, et tant que votre liste de tâches n’est pas vide, vous ne tenez pas en place. Vous vous dépêchez de tout finir uniquement pour vous débarrasser de cette pression. Rappelez-vous : tout n’est pas si urgent, ralentir est tout à fait permis.`
 },

 centersDefined: {
  head: `Avec un centre de la Tête défini, votre esprit porte toujours des questions et des inspirations orientées dans une même direction. Une idée vous vient peut-être sous la douche, et vous y pensez ensuite toute la journée. Votre réflexion stimule votre entourage, mais rappelez-vous : une inspiration n’est pas une obligation d’agir, c’est seulement de la matière à réflexion.`,
  ajna: `Avec un centre Ajna défini, vous avez une manière de penser stable. Quand un ami vous demande votre avis, vous savez généralement organiser rapidement votre point de vue. Vous êtes très sûr de vos idées, c’est une qualité ; mais pour les décisions importantes, ne laissez pas le « j’y ai bien réfléchi » remplacer l’autorité de votre corps.`,
  throat: `Avec un centre de la Gorge défini, vous avez une manière de vous exprimer et une voix constantes. Votre façon de parler et d’agir a un style reconnaissable, et en réunion, dès que vous prenez la parole, on vous écoute. Vous n’avez pas besoin de couper la parole pour être vu, alors vous pouvez attendre sereinement le bon moment pour dire ce que vous avez à dire.`,
  g: `Avec un centre G défini, vous avez un sentiment stable de « qui je suis et où je vais ». Quel que soit l’environnement, vous restez vous-même. Vos amis viennent souvent vous voir quand ils sont perdus, parce que vous dégagez un sens de la direction. Rappelez-vous seulement que la direction des autres n’est pas forcément la vôtre.`,
  heart: `Avec un centre du Cœur défini, vous faites ce que vous dites, avec une volonté stable. Ce que vous promettez d’accomplir, vous l’accomplissez généralement. Mais la volonté a aussi besoin de repos : ne prenez pas toutes les promesses sur vous sous prétexte que vous en êtes capable, et n’imposez pas vos critères aux autres.`,
  sacral: `Avec un centre sacral défini, vous avez dans le corps un générateur qui tourne de façon stable. Quand vous faites ce à quoi vous répondez, vous pouvez être occupé du matin au soir et rester heureux. Mais si vous vous forcez à faire un travail qui ne vous intéresse pas, cette même énergie se transforme en frustration. Épuisez votre énergie avant de vous coucher, et vous dormirez particulièrement bien.`,
  spleen: `Avec un centre de la Rate défini, vous avez une intuition stable et une capacité à vous protéger. En entrant dans une boutique, vous sentez peut-être que quelque chose cloche et faites demi-tour, pour apprendre ensuite qu’il s’y était passé quelque chose. Votre intuition ne parle qu’une fois, très doucement ; plus vous lui faites confiance tôt, moins vous faites de détours inutiles.`,
  sp: `Avec un plexus solaire défini, vous avez votre propre vague émotionnelle, et ses hauts et ses bas sont tout à fait normaux. Lundi, vous trouvez peut-être votre travail génial, et mercredi vous avez très envie de partir. En haut comme en bas de la vague, vous ne voyez que la moitié de la réponse : pour les décisions importantes, attendez que votre humeur se soit stabilisée.`,
  root: `Avec un centre racine défini, vous gérez la pression de façon constante, et l’empressement des autres vous déstabilise peu. Votre responsable a beau vous relancer, vous finissez à votre rythme. Cette stabilité est précieuse, mais soyez attentif : votre pression pousse votre entourage sans que vous vous en rendiez compte.`
 }
};
