/* Starlit : contenus narratifs du thème astral (combinaisons Soleil-Lune, scènes par rôle, scènes d’aspects) — version française */
globalThis.STORY_WEST_FR={
sunMoon:[
/* Soleil en Bélier */
[
`Vous êtes comme une allumette qu’on vient de craquer : dehors comme dedans, tout pousse dans la même direction, vers l’avant. Un ami propose une randonnée pour le week-end, vous dites oui sur-le-champ et le soir même tout l’équipement est acheté. L’avantage, c’est une action nette et sans détour ; le point à surveiller, c’est que vous refusez de vous arrêter même fatigué, et vous ne découvrez souvent que vous étiez à bout qu’au moment où le corps dit stop.`,
`À l’extérieur, vous voulez arriver premier ; à l’intérieur, vous avez besoin d’une sécurité bien solide. Vous pouvez vous inscrire à une formation pour créer votre entreprise tout en calculant discrètement combien de mois votre épargne vous permettra de tenir avant d’oser démissionner. Votre élan repose sur des fondations, et vos résultats durent plus longtemps que ceux des fonceurs purs ; simplement, quand les deux côtés se disputent, vous vous sentez à la fois pressé et lent.`,
`Dehors, vous voulez lancer des choses ; dedans, vous avez besoin d’informations fraîches et de conversation. En réunion, vous êtes le premier à proposer une idée, puis une fois la séance levée vous envoyez dix messages d’affilée dans le groupe pour la compléter. Votre tête et vos jambes vont vite, vous êtes un excellent démarreur ; l’angle mort, c’est que l’enthousiasme retombe aussi vite qu’il monte, alors pensez à confier la finition à quelqu’un.`,
`Celui que l’on voit fonce droit devant ; celui de l’intérieur a en réalité très peur d’être laissé de côté. Vous pouvez parler sèchement au bureau, puis passer la soirée à vous morfondre parce qu’un proche vous a répondu froidement. Votre force sert souvent à protéger ceux qui comptent pour vous. Faites savoir à vos proches que, sous votre impatience, il y a de l’inquiétude et non de la colère.`,
`Vous voulez être le premier et vous avez besoin d’être vu : deux feux qui brûlent ensemble, c’est très communicatif. Quand vous menez une équipe vers ses objectifs, vous montrez l’exemple vous-même puis vous applaudissez chacun à voix haute. Il vous faut des applaudissements pour trouver la force de continuer, et vous vous dégonflez quand personne ne réagit ; apprenez à vous applaudir vous-même en premier.`,
`Dehors, vous voulez aller vite ; dedans, vous voulez vérifier que chaque détail est juste. Vous pouvez accepter un projet sur un coup de tête, puis passer trois nuits blanches à peaufiner le planning jusqu’à la perfection. Cela vous donne à la fois de la puissance et de la rigueur ; dans les moments de tiraillement, vous pressez les autres d’accélérer tout en leur reprochant leur manque de soin. Soyez un peu plus indulgent, avec vous aussi.`,
`Votre Soleil et votre Lune sont en opposition : dehors, vous êtes direct et franc ; dedans, vous avez besoin de relations harmonieuses. Dans une dispute, vous ouvrez le feu en premier, puis dix minutes plus tard vous envoyez vous-même un message pour apaiser les choses. Vous voulez gagner et vous voulez être aimé. Avant une décision importante, demandez-vous d’abord ce que vous voulez, puis ce que pensent les autres : vous ne perdrez pas sur les deux tableaux.`,
`Dehors, vous êtes franc et impulsif ; dedans, vous restez secret et vous gardez la trace de chaque compte. Vous pouvez dire « ce n’est rien » en souriant alors que vous avez déjà décidé de prendre vos distances. Cette combinaison donne une volonté impressionnante : une fois la cible fixée, rien ne vous arrête. Veillez seulement à ne pas laisser trop longtemps fermenter les émotions que vous ne dites pas.`,
`Dehors, vous voulez foncer ; dedans, vous voulez vous envoler : vous êtes l’aventurier type. Vous réservez un billet d’avion au dernier moment et vous ne cherchez un logement qu’une fois sur place. Votre optimisme entraîne les autres, mais vous fait aussi souvent sous-estimer les risques. Gardez un peu de budget et une porte de sortie avant de partir, et cette liberté durera longtemps.`,
`Celui que l’on voit est pressé de foncer ; celui de l’intérieur calcule froidement les résultats à long terme. Vous dites « on verra en le faisant », alors qu’en privé vous avez déjà un plan sur trois ans. Votre élan a donc une direction, et vous êtes fait pour mener ; mais vous êtes très dur avec vos propres émotions et vous n’admettez pas la fatigue. Il vous faut quelqu’un pour vous rappeler que vous avez le droit de vous reposer.`,
`Dehors, vous voulez prendre la tête ; dedans, vous avez besoin de liberté et d’espace. Vous lancez avec enthousiasme une activité d’association, puis, quand tout le monde a fait connaissance, vous avez envie d’aller déjeuner seul. Votre indépendance vous évite d’être prisonnier de vos émotions ; vos proches ont parfois du mal à vous cerner, alors confiez-leur de temps en temps ce que vous avez sur le cœur.`,
`Celui que l’on voit est un guerrier ; celui de l’intérieur est tendre et facile à blesser. Vous pouvez défendre votre point de vue avec fougue en réunion, puis rentrer chez vous et pleurer sans pouvoir vous arrêter devant un film. Votre courage sert souvent à protéger plus faible que vous. Quand vous êtes épuisé, inutile de tenir à tout prix : offrez-vous une soirée tranquille, à l’abri.`
],
/* Soleil en Taureau */
[
`Dehors, vous voulez avancer tranquillement ; dedans, vous trépignez souvent d’impatience. À la caisse, vous avez l’air très patient, mais dans votre tête vous comptez déjà les minutes qu’il reste. Ce feu caché vous permet d’accélérer brusquement au moment décisif ; le point à surveiller, c’est que les émotions contenues trop longtemps peuvent exploser d’un coup pour une broutille.`,
`Vous êtes comme une pierre au fond d’un ruisseau : dehors comme dedans, vous voulez du stable, du confortable, du prévisible. Vous pouvez prendre votre petit-déjeuner au même café tous les jours pendant dix ans. Votre fiabilité rassure votre entourage ; l’angle mort, c’est que vous résistez instinctivement au changement. Essayez, chaque saison, une petite nouveauté choisie par vous.`,
`Dehors, vous recherchez la stabilité ; dedans, il vous faut de la nouveauté. Vous restez longtemps dans la même entreprise, mais le soir vous apprenez en même temps la pâtisserie, le japonais et la photo. Vous êtes ainsi solide sans vous ennuyer ; dans les moments de tiraillement, vous vous demandez si vous voulez la sécurité ou le changement. En réalité, un travail stable et des loisirs changeants peuvent très bien cohabiter.`,
`Dehors, vous voulez de la stabilité ; dedans, vous voulez un foyer : c’est une combinaison qui sait faire vivre une maison. Votre plus grand rêve peut être une maison lumineuse et une table garnie de plats bien chauds. Vous savez prendre soin des gens et mettre de l’argent de côté ; attention seulement à ne pas tenir tellement à la sécurité que votre zone de confort rétrécit d’année en année.`,
`Celui que l’on voit est pragmatique et discret ; celui de l’intérieur a soif de reconnaissance. Vous rendez un rapport impeccable, et si votre responsable ne le remarque pas, vous ne dites rien mais vous ruminez longtemps. Votre ténacité alliée à votre fierté vous donne beaucoup de poids ; présentez vous-même vos résultats : être vu, ce n’est pas se mettre en avant.`,
`Dehors, vous êtes posé ; dedans, vous êtes minutieux : une combinaison très efficace. Quand vous préparez un voyage, l’itinéraire de chaque jour, les transports et le budget finissent dans un tableur. Vous êtes souvent celui qui rassure l’équipe ; l’angle mort, c’est de trop vous inquiéter des petits détails. Laissez un peu de blanc dans le planning pour les bonnes surprises.`,
`Dehors, vous tenez au concret ; dedans, vous avez besoin de beauté et d’harmonie. Vous épargnez avec application, mais vous êtes prêt à dépenser beaucoup pour une belle chaise ou un bon repas. Vous avez du goût et vous êtes apprécié ; dans les moments de tiraillement, vous taisez ce que vous pensez pour éviter le conflit. Entraînez-vous à dire « non » avec douceur mais clairement.`,
`Votre Soleil et votre Lune sont en opposition : dehors, vous voulez la sécurité ; dedans, vous aspirez à la profondeur et à l’absolu. En apparence, vos journées sont réglées comme du papier à musique, mais intérieurement vous vous accrochez de tout votre être à une relation. Votre persévérance est hors du commun ; surveillez la possessivité : à trop serrer, on finit par perdre. Apprenez à desserrer un peu la main.`,
`Dehors, vous voulez préserver ce que vous avez ; dedans, vous rêvez de partir loin. Vous pouvez avoir un emploi stable et, tous les quelques mois, avoir envie de découvrir un pays où vous n’êtes jamais allé. Vous conciliez ainsi réalisme et idéal ; quand vous hésitez entre épargner et dépenser pour vivre des expériences, réservez-vous une cagnotte voyage fixe.`,
`Dedans comme dehors, vous êtes pragmatique, comme une maison de pierre montée lentement. Dès votre première année de travail, vous avez commencé à planifier l’achat d’un logement, et vous suivez le plan pas à pas. Votre endurance et votre sens des responsabilités sont difficiles à égaler ; le point à surveiller, c’est que vous vous accordez trop peu de plaisir et d’expression émotionnelle. Un petit écart de temps en temps ne fait pas de mal.`,
`Dehors, vous voulez de la stabilité ; dedans, vous avez besoin d’être différent. Votre emploi du temps est très régulier, mais vos idées sont avant-gardistes et vous lancez souvent en soirée des points de vue inattendus. Vous êtes à la fois fiable et inventif ; dans les moments de tiraillement, vous défendez obstinément votre singularité. Écoutez aussi la version des autres.`,
`Celui que l’on voit a les pieds sur terre ; celui de l’intérieur est tendre et romantique. Vous travaillez sérieusement la journée, et le soir une vieille chanson peut vous tirer des larmes. Vous savez transformer lentement un rêve en quelque chose de tangible, ce qui vous prédispose à l’art et à l’artisanat ; attention à ne pas, par bonté, réparer encore et encore les dégâts financiers des autres.`
],
/* Soleil en Gémeaux */
[
`Dehors, vous voulez communiquer ; dedans, vous voulez agir : c’est l’une des combinaisons les plus rapides. Un ami a à peine fini d’exposer son souci que vous avez déjà trois solutions et que vous êtes passé à l’action. Vous êtes vif et plein d’allant ; l’angle mort, c’est le manque de patience et une parole qui part trop vite. Dans une discussion, comptez jusqu’à trois avant de répliquer.`,
`Celui que l’on voit est curieux et changeant ; celui de l’intérieur a besoin de stabilité et de confort. Vous adorez tester de nouveaux restaurants, mais les jours de cafard vous retournez toujours dans la petite cantine que vous fréquentez depuis dix ans. Votre intelligence a ainsi des racines ; donnez-vous une base fixe, puis partez explorer, et vous ne vous sentirez plus tiraillé.`,
`Dedans comme dehors, vous êtes un grand curieux, comme un navigateur avec vingt onglets ouverts en même temps. Vous pouvez écouter un podcast, répondre à vos messages et chercher quoi manger ce soir, tout à la fois. Vous apprenez vite et vous parlez de tout ; attention à traiter aussi vos émotions uniquement en « réfléchissant ». Quand vous êtes vraiment triste, arrêtez-vous pour ressentir au lieu de seulement analyser.`,
`Celui que l’on voit est bavard et léger ; celui de l’intérieur a grand besoin de sécurité. En soirée, vous enchaînez les bons mots, puis de retour chez vous vous vous demandez sans fin si telle phrase de quelqu’un vous visait. Vous savez prendre soin des gens avec les mots ; quand vous êtes fatigué, dites la vérité à vos proches au lieu de vous en tirer par une plaisanterie.`,
`Dehors, vous aimez échanger ; dedans, vous avez besoin d’être apprécié, et vous savez captiver avec une histoire. Quand vous partagez votre vie sur les réseaux, vous regardez qui a aimé et qui a commenté. Votre talent d’expression est fait pour la scène ; dans les moments de tiraillement, le regard des autres compte plus pour vous que le fond. Rappelez-vous que ce que vous dites a de la valeur en soi.`,
`Votre Soleil et votre Lune sont tous deux gouvernés par Mercure : votre pensée est fine et souple. Dans une discussion, vous saisissez à la fois l’orientation générale et la coquille dans la présentation. Vous faites un excellent éditeur ou analyste ; l’angle mort, c’est de trop réfléchir et de mal dormir. Avant de vous coucher, notez ce que vous avez en tête pour que votre cerveau quitte le bureau à l’heure.`,
`Dehors, vous aimez parler ; dedans, vous aimez l’harmonie : une combinaison très attachante. Quand des amis se brouillent, c’est souvent vous qui faites la navette entre les deux et qui sauvez l’ambiance. Vous avez le sens des relations ; dans les moments de tiraillement, vous cachez votre avis pour faire plaisir à tout le monde. Laissez parfois savoir de quel côté vous êtes.`,
`Celui que l’on voit est détendu et causant ; celui de l’intérieur est profond et perspicace. Vous pouvez avoir une conversation très joyeuse sans jamais livrer vos vrais soucis. Votre sens de l’observation est fait pour la recherche et l’enquête ; dans les moments de tiraillement, vous soupçonnez des sous-entendus. Posez la question directement au lieu de mener l’enquête seul jusqu’au milieu de la nuit.`,
`Votre Soleil et votre Lune sont en opposition : dehors, vous collectez de l’information ; dedans, vous cherchez du sens. Vous lisez une pile d’articles et vous vous demandez souvent « à quoi tout cela sert-il ? ». Vous avez à la fois de l’étendue et de la vision, et vous savez transmettre ; dans les moments de tiraillement, vous oscillez entre les détails et la vue d’ensemble. Fixez d’abord le but, puis choisissez les informations utiles.`,
`Celui que l’on voit est vif et enjoué ; celui de l’intérieur est sérieux et pragmatique. Vous plaisantez devant vos collègues, mais en privé chaque tâche a sa priorité. Votre intelligence se transforme ainsi en résultats ; l’angle mort, c’est l’habitude de garder vos émotions pour vous parce que montrer sa faiblesse vous semble compliqué. Dire de temps en temps « je suis épuisé », c’est permis.`,
`Dedans comme dehors, vous êtes un signe d’air : pensée rapide, goût des idées neuves, attachement à la liberté. Vous pouvez débattre avec un ami jusqu’à l’aube pour savoir si l’intelligence artificielle remplacera l’humain. Votre esprit a une longueur d’avance ; attention à gérer les sentiments par la raison : quand l’autre a besoin d’un câlin, vous risquez de lui donner seulement des conseils.`,
`Celui que l’on voit est souple et changeant ; celui de l’intérieur est sensible et plein d’imagination. Vous parlez de façon très rationnelle, mais votre plume sait écrire des histoires bouleversantes, ce qui vous prédispose à la création et à la traduction. Dans les moments de tiraillement, vous vous laissez emporter par les émotions des autres et vous dites des choses que vous ne pensez pas. Vérifiez d’abord ce que vous ressentez avant de parler.`
],
/* Soleil en Cancer */
[
`Celui que l’on voit est doux et casanier ; celui de l’intérieur est impatient et combatif. Quand un membre de votre famille se fait malmener, vous, d’ordinaire si doux, êtes le premier à aller demander des comptes. Votre instinct protecteur passe vite à l’action ; attention, vos émotions montent vite et vous pouvez parler trop durement à vos plus proches. Pensez ensuite à ajouter un mot d’excuse.`,
`Dehors, vous tenez à votre famille ; dedans, vous cherchez la stabilité : une combinaison qui sait faire un vrai « nid ». Votre plus grand bonheur peut être de mijoter une soupe le week-end et de voir les vôtres finir la marmite. Vous êtes fiable et attaché au passé ; l’angle mort, c’est votre réticence au changement, qui vous rend anxieux quand l’environnement bouge. Découpez le changement en petites étapes pour vous y faire en douceur.`,
`Celui que l’on voit est très affectif ; celui de l’intérieur a besoin de variété et de conversation. Vous animez le groupe familial sur la messagerie en partageant tous les jours des nouvelles et des mèmes. Vous savez relier les gens par la parole ; dans les moments de tiraillement, vous voulez tantôt vous blottir, tantôt respirer. Dites franchement à l’autre le rythme dont vous avez besoin.`,
`Dedans comme dehors, vous êtes Cancer : vos émotions sont abondantes comme une marée. Vous vous souvenez de l’anniversaire de chacun de vos amis, et aussi de chaque fois où l’on vous a ignoré. Vous savez merveilleusement prendre soin des autres ; le point à surveiller, c’est que vos émotions vous emportent facilement. Quand le moral est bas, occupez-vous d’abord de vous, puis des autres.`,
`Celui que l’on voit est doux et discret ; celui de l’intérieur a besoin de compter. Vous préparez avec soin une surprise d’anniversaire, et si la réaction est tiède, vous en êtes peiné longtemps. Votre amour est généreux et chaleureux ; dire directement « j’aimerais que tu le remarques » marche bien mieux que d’attendre en silence que l’autre s’en aperçoive.`,
`Dehors, vous prenez soin des autres ; dedans, vous êtes attentif aux détails : une combinaison très délicate. Vous vous rappelez que votre ami n’aime pas la coriandre et quels médicaments un proche doit prendre chaque jour. Vous aimez de façon très concrète ; l’angle mort, c’est de trop vous inquiéter et de répéter les choses. Rappelez une fois, puis laissez l’autre décider.`,
`Celui que l’on voit tient beaucoup à sa famille ; celui de l’intérieur a besoin d’harmonie et d’équité. Quand frères et sœurs se répartissent la prise en charge des parents, c’est souvent vous qui jouez les médiateurs. Vous savez ménager la sensibilité de chacun ; dans les moments de tiraillement, vous ravalez vos griefs pour éviter le conflit. N’oubliez pas que vous aussi faites partie de la famille.`,
`Dehors, vous êtes doux ; dedans, vous êtes passionné et fidèle : l’eau renforcée deux fois. Vous donnez tout à ceux que vous avez choisis, mais une trahison vous rend la confiance très difficile. La profondeur de vos sentiments est touchante et votre intuition juste ; ne cachez pas trop longtemps vos blessures. En parler à une personne de confiance vous aidera plus vite que de tout digérer seul.`,
`Celui que l’on voit est casanier et nostalgique ; celui de l’intérieur rêve d’ailleurs. Vous aimez profondément votre foyer, mais le week-end il vous prend souvent l’envie soudaine de prendre la voiture pour aller voir la mer. Vous avez à la fois de la chaleur et de l’optimisme ; dans les moments de tiraillement, vous culpabilisez de vouloir sortir de votre cocon. Partir à l’aventure avec votre famille est aussi une forme d’équilibre.`,
`Votre Soleil et votre Lune sont en opposition : dehors, vous êtes affectueux ; dedans, vous exigez de vous-même d’être fort. Vous êtes plein de tendresse avec les vôtres, mais quand vous allez mal, vous ne dites pas un mot. Vous êtes souvent le pilier de la famille ; dans les moments de tiraillement, montrer votre faiblesse vous semble honteux. Pourtant, vous laisser aider, c’est aussi leur donner l’occasion de vous montrer leur amour.`,
`Celui que l’on voit a besoin d’appartenance ; celui de l’intérieur a besoin d’espace. Vous aimez beaucoup votre famille, mais il vous faut chaque jour un moment enfermé dans votre chambre, sans parler à personne. Votre amour n’étouffe donc pas ; faites savoir à votre entourage que c’est votre façon de recharger les batteries, pas de la froideur.`,
`Dedans comme dehors, vous êtes un signe d’eau : sensible, doux, plein d’empathie. Un chat errant croisé dans la rue peut vous serrer le cœur pendant des jours. Vous savez réconforter et vous êtes fait pour les métiers d’aide ; veillez à vos limites, ne portez pas toutes les émotions des autres. Quand vous êtes épuisé, coupez le téléphone et dormez bien.`
],
/* Soleil en Lion */
[
`Dedans comme dehors, vous êtes un signe de feu : chaleureux, direct, avec l’étoffe d’un meneur. Quand l’équipe est bloquée, c’est vous qui dites le premier « je m’en occupe ». Vous savez galvaniser les gens ; l’angle mort, c’est un tempérament prompt qui se sent vite offensé quand on vous remet en question. Entraînez-vous à écouter jusqu’au bout avant de répondre.`,
`Celui que l’on voit veut briller ; celui de l’intérieur a besoin de stabilité et de confort. Vous aimez être remarqué, mais vous tenez encore plus à avoir un foyer sûr et de l’argent de côté. Vous avez de la stature et beaucoup d’obstination ; dans les moments de tiraillement, vous refusez de changer de méthode par fierté. Rappelez-vous qu’ajuster n’est pas capituler.`,
`Celui que l’on voit est sûr de lui et généreux ; celui de l’intérieur a besoin de conversation et de nouveauté. En soirée, vous racontez des histoires à merveille et vous faites rire tout le monde. Votre expressivité est remarquable ; dans les moments de tiraillement, vous en promettez trop pour soigner votre image, puis vous vous sentez mal à l’aise. Gardez-vous une petite marge quand vous parlez.`,
`Celui que l’on voit rayonne ; celui de l’intérieur a grand besoin qu’on prenne soin de lui. Dehors, vous jouez les grands frères ou les grandes sœurs, mais en rentrant vous aimeriez que quelqu’un vous prépare une tasse de thé. Vous tenez à votre foyer et vous êtes généreux ; dans les moments de tiraillement, vous n’osez pas montrer votre faiblesse. Dire « je suis épuisé aujourd’hui » ne vous fera pas perdre votre aura.`,
`Dedans comme dehors, vous êtes Lion : confiant, généreux, avec besoin d’une scène. Quand vous organisez une fête, vous n’êtes satisfait que si chacun s’est vraiment amusé. Vous savez mettre l’ambiance et vous êtes d’une grande loyauté ; attention à votre fierté, qui est vite blessée quand on vous ignore. Votre valeur n’a pas besoin d’être confirmée par des applaudissements à chaque fois.`,
`Celui que l’on voit veut se montrer ; celui de l’intérieur est un perfectionniste exigeant. Avant de monter sur scène, vous pouvez retravailler votre présentation jusqu’à la dixième version. Votre éclat repose ainsi sur du solide ; dans les moments de tiraillement, vous n’osez pas vous montrer tant que ce n’est pas assez bien. Essayez de faire passer « terminé » avant « parfait ».`,
`Celui que l’on voit est chaleureux et expansif ; celui de l’intérieur a besoin d’harmonie et d’être aimé. Vous savez complimenter et vous tenez beaucoup à l’image que les autres ont de vous. Vous êtes apprécié et vous avez du goût ; dans les moments de tiraillement, vous n’osez pas refuser pour préserver votre image. Le vrai charme vient pourtant du fait d’être soi-même.`,
`Celui que l’on voit est généreux et franc ; celui de l’intérieur est profond et aime avoir le contrôle. Vous êtes brillant en public, mais en privé vous ne vous ouvrez qu’à une poignée de personnes. Vous avez de l’envergure et vous êtes fait pour décider ; dans les moments de tiraillement, l’orgueil vous empêche de faire le premier pas. Dans une relation, celui qui parle en premier est souvent le plus fort des deux.`,
`Dedans comme dehors, vous êtes un signe de feu : enthousiaste, optimiste, avide d’aventure. Vous partez sur un coup de tête et vous pouvez très bien vous amuser en camping seul le temps d’un week-end. Vous savez donner de l’espoir ; l’angle mort, c’est de promettre trop vite et d’accepter trop de choses d’un coup. Tenir parole compte plus que bien parler.`,
`Celui que l’on voit veut être remarqué ; celui de l’intérieur veut des réussites concrètes. Vous voulez le premier rôle, mais vous vous assurez d’abord d’avoir un vrai savoir-faire avant d’entrer en scène. Cette combinaison est ambitieuse et endurante ; dans les moments de tiraillement, la peur d’échouer et d’avoir l’air ridicule vous fait tarder. Rappelez-vous que tous ceux qui réussissent se sont un jour couverts de ridicule.`,
`Votre Soleil et votre Lune sont en opposition : dehors, vous voulez être le héros ; dedans, vous voulez être vous-même, à part. Vous aimez qu’on vous remarque, mais vous détestez les étiquettes. Vous unissez la passion et la raison, ce qui vous rend apte à guider un groupe ; trouvez une scène qui vous permette à la fois de briller et d’aider les autres, et le tiraillement deviendra un moteur.`,
`Celui que l’on voit est confiant et éclatant ; celui de l’intérieur est tendre et sensible. Vous pouvez être magnétique sur scène, puis ressasser en coulisses la crainte d’avoir dit une bêtise. Vous avez un vrai talent créatif et un grand pouvoir de contagion ; dans les moments de tiraillement, vous accordez trop d’importance aux réactions du public. Après la représentation, commencez par vous serrer vous-même dans vos bras.`
],
/* Soleil en Vierge */
[
`Celui que l’on voit est méticuleux et prudent ; celui de l’intérieur est impatient et veut foncer. Vous rédigez un plan très complet, puis pendant l’exécution vous n’avez qu’une idée : en finir vite. Vous avez à la fois l’esprit d’analyse et le sens de l’action ; dans les moments de tiraillement, vous vous impatientez contre ceux qui avancent lentement. Rappelez-vous que tout le monde n’a pas votre rythme.`,
`Dedans comme dehors, vous êtes un signe de terre : pragmatique, stable, attentif à la qualité. Vous avez chaque semaine vos créneaux fixes de sport et de courses, et vous les bousculez rarement. Vous êtes un partenaire très fiable ; l’angle mort, c’est une telle habitude de la routine que le changement vous angoisse. Essayez chaque mois une chose non prévue.`,
`Dehors, vous soignez les détails ; dedans, vous aimez apprendre, et les deux sont gouvernés par Mercure. Vous lisez trois livres d’un trait, puis vous en faites des notes que vous partagez avec vos amis. Votre capacité d’apprentissage est remarquable ; dans les moments de tiraillement, trop réfléchir vous empêche de dormir. Avant de vous coucher, notez votre liste de choses à faire pour laisser votre tête se reposer.`,
`Celui que l’on voit est rationnel et concret ; celui de l’intérieur a grand besoin d’appartenance. Vous exprimez votre amour en « faisant » : ranger la chambre d’un proche, préparer un repas à emporter. Votre attention est très concrète ; dans les moments de tiraillement, vous vous inquiétez trop. Apprenez à formuler votre inquiétude comme de l’attention, l’autre l’accueillera plus facilement.`,
`Celui que l’on voit est discret et prudent ; celui de l’intérieur a soif de reconnaissance. Vous menez un projet à la perfection en silence, et si personne ne le remarque, vous êtes un peu déçu. Vous avez du talent ; dans les moments de tiraillement, vous n’osez pas revendiquer le mérite. Parler de votre contribution, c’est la façon de faire voir un bon travail.`,
`Dedans comme dehors, vous êtes Vierge : délicat, travailleur, en quête de perfection. Une feuille posée de travers sur un bureau vous donne envie de la redresser. Vous feriez un excellent contrôleur qualité ; le point à surveiller, c’est d’être trop dur envers vous-même, avec une petite voix critique qui ne s’arrête jamais. Chaque jour, trouvez une chose bien faite et félicitez-vous.`,
`Celui que l’on voit est pragmatique et exigeant ; celui de l’intérieur a besoin de beauté et d’harmonie. Vous pouvez passer tout un après-midi à choisir une tasse de la couleur exacte. Vous avez du goût et le sens de la médiation ; dans les moments de tiraillement, vous ravalez vos critiques pour préserver la paix. Dire doucement ce que vous pensez vaut mieux que de tout garder pour vous.`,
`Celui que l’on voit est attentif et discret ; celui de l’intérieur est profond et perspicace. Vous avez l’air très calme, alors que vous avez déjà percé les motivations de chacun. Vous êtes fait pour la recherche, l’enquête et les métiers de la psychologie ; dans les moments de tiraillement, vous ne faites confiance à personne et vous faites tout vous-même. Essayez d’en confier une partie à des gens qui le méritent.`,
`Celui que l’on voit soigne les détails ; celui de l’intérieur rêve de liberté et de grands horizons. Vous êtes minutieux au travail, mais en vacances vous voulez partir sac au dos sans rien prévoir. Vous avez à la fois le sens de l’exécution et de la vision ; dans les moments de tiraillement, vous oscillez entre « trop précis » et « trop dispersé ». Saisissez d’abord la direction générale, puis occupez-vous des détails.`,
`Dedans comme dehors, vous êtes un signe de terre : sérieux, concret, responsable. Depuis l’école, vous êtes sans doute celui qui rend ses devoirs le plus ponctuellement. Vous êtes très endurant et on peut vous faire confiance ; le point à surveiller, c’est de trop peu vous détendre et de faire du travail toute votre vie. Pensez à prévoir des moments où vous ne faites rien.`,
`Celui que l’on voit est pragmatique et méticuleux ; celui de l’intérieur a besoin d’indépendance et d’innovation. Vous gérez votre vie avec plusieurs applications, et vous avez même conçu votre propre système. Vous savez résoudre les problèmes ; dans les moments de tiraillement, vous paraissez un peu froid. En amour, partagez de temps en temps ce que vous ressentez au lieu de seulement donner des conseils.`,
`Votre Soleil et votre Lune sont en opposition : dehors, vous visez la précision ; dedans, vous êtes romantique et sensible. Vous pouvez faire vos rapprochements bancaires la journée et écrire de la poésie ou peindre le soir. Vous alliez raison et empathie, ce qui vous prédispose aux métiers d’aide ; dans les moments de tiraillement, vous voulez tantôt tout contrôler, tantôt tout fuir. Accordez-vous un coin où le désordre est permis.`
],
/* Soleil en Balance */
[
`Votre Soleil et votre Lune sont en opposition : dehors, vous recherchez l’harmonie ; dedans, vous êtes impatient et direct. En public, vous êtes très poli, alors que dans votre tête vous levez déjà les yeux au ciel. Vous avez à la fois du charme et du cran ; dans les moments de tiraillement, vous contenez votre colère jusqu’à l’explosion finale. Essayez d’exprimer votre mécontentement dès les petites choses.`,
`Dehors, vous êtes élégant ; dedans, vous cherchez la stabilité, et les deux sont gouvernés par Vénus. Vous savez profiter de la vie, et vous avez vos goûts bien à vous en vêtements, restaurants et parfums. Vous êtes apprécié et fiable ; l’angle mort, c’est votre amour du confort : vous repoussez sans cesse les explications nécessaires. Certaines choses sont plus légères à dire tôt.`,
`Dedans comme dehors, vous êtes un signe d’air : très sociable et vif. Dans un mariage, vous pouvez échanger quelques mots avec chaque table. Vous savez relier les gens ; attention à des émotions qui restent en surface : même quand vous êtes vraiment triste, vous vous en tirez par une plaisanterie. Laissez-vous parfois ressentir pleinement.`,
`Celui que l’on voit tient aux relations ; celui de l’intérieur a besoin de la chaleur d’un foyer. Vous êtes très diplomate à l’extérieur, mais en rentrant vous aimeriez que quelqu’un comprenne ce que vous avez encaissé. Vous savez soigner l’ambiance et votre famille ; dans les moments de tiraillement, la peur du conflit vous fait ravaler vos émotions. Avec vos plus proches, vous n’avez pas besoin d’autant de politesse.`,
`Celui que l’on voit est élégant et courtois ; celui de l’intérieur a besoin d’être admiré. Vous savez vous habiller et vous aimeriez que votre partenaire vous complimente souvent. Vous avez beaucoup de charme et vous êtes apprécié ; dans les moments de tiraillement, vous accordez trop d’importance au regard des autres. Rappelez-vous que votre valeur ne se mesure pas aux « j’aime » : aimez-vous d’abord, et les compliments seront un bonus.`,
`Dehors, vous tenez à l’esthétique ; dedans, vous êtes attentif aux détails. Pour une soirée, vous avez pensé jusqu’à la couleur de la nappe et au plan de table. Vous avez du goût et le souci du détail ; dans les moments de tiraillement, vous ravalez vos critiques pour ne blesser personne, puis vous vous rongez de l’intérieur. Apprenez à dire la vérité avec douceur.`,
`Dedans comme dehors, vous êtes Balance : en quête d’équité, d’harmonie et de beauté. Quand un ami vous demande d’arbitrer, vous vous mettez sérieusement à la place des deux camps. Vous êtes un excellent médiateur et vous avez du goût ; le point à surveiller, c’est votre difficulté à trancher, au point d’hésiter longuement sur le menu du dîner. Donnez-vous un délai.`,
`Celui que l’on voit est conciliant et doux ; celui de l’intérieur est profond et tenace. Vous souriez à tout le monde, mais vous ne faites vraiment confiance qu’à quelques-uns. Vous avez du flair et du charme ; dans les moments de tiraillement, vous faites mine de suivre tout en gardant rancune. Exprimez votre mécontentement plus tôt : une petite chose réglée le jour même ne devient pas une grosse dette.`,
`Celui que l’on voit tient aux relations ; celui de l’intérieur a besoin de liberté et d’aventure. Vous aimez voyager entre amis, mais il vous faut aussi chaque jour un moment seul. Vous savez rendre les gens heureux ; dans les moments de tiraillement, vous oscillez entre la compagnie et la liberté. Dites franchement à votre partenaire de combien d’espace vous avez besoin.`,
`Celui que l’on voit est aimable et facile à vivre ; celui de l’intérieur est exigeant et pragmatique. Vous avez l’air arrangeant, mais vous avez déjà vos limites et votre plan. Vous alliez popularité et compétence, ce qui vous prédispose au management ou aux relations publiques ; dans les moments de tiraillement, vous refoulez vos émotions. Pensez à poser vos responsabilités de temps en temps pour profiter un peu de la vie.`,
`Dedans comme dehors, vous êtes un signe d’air : rationnel, amical, attaché à l’équité. Vous prenez la défense des droits de vos amis et vous vous inscrivez à toutes sortes d’actions bénévoles. Vous êtes idéaliste ; attention à une certaine distance affective : quand l’autre a besoin de présence, répondez par des gestes et pas seulement par des raisonnements.`,
`Celui que l’on voit est élégant et harmonieux ; celui de l’intérieur est romantique et sensible. Une chanson ou un film vous bouleverse facilement, et vous compatissez vite aux autres. Vous avez un vrai talent artistique ; dans les moments de tiraillement, vous vous sacrifiez pour faire plaisir aux autres. Rappelez-vous que dire « non » est aussi une forme de douceur.`
],
/* Soleil en Scorpion */
[
`Celui que l’on voit est profond et réservé ; celui de l’intérieur est impulsif et direct. Vous paraissez très calme, mais quand on vous provoque, une seule phrase de vous touche en plein dans le mille. Vous avez de la force explosive et de la volonté ; dans les moments de tiraillement, vous dites facilement des choses que vous regrettez ensuite. Quand vous êtes en colère, quittez la pièce dix minutes.`,
`Votre Soleil et votre Lune sont en opposition : dehors, vous cherchez la profondeur ; dedans, vous avez besoin de sécurité. Vous vous investissez entièrement en amour et vous avez grand besoin que l’autre s’engage de façon stable. Vous êtes persévérant et loyal ; dans les moments de tiraillement, la possessivité grandit et vous avez envie de vérifier où est l’autre. La confiance retient mieux les gens que le contrôle.`,
`Celui que l’on voit est profond et mystérieux ; celui de l’intérieur est curieux et bavard. Vous savez poser des questions, mais vous répondez rarement à celles qui vous concernent. Vous êtes fait pour l’enquête, la recherche et l’écriture ; dans les moments de tiraillement, vous voulez tantôt creuser, tantôt passer à autre chose. Donnez-vous une soupape régulière, comme un journal intime.`,
`Dedans comme dehors, vous êtes un signe d’eau : sentiments profonds, intuition juste. Au ton de la voix de quelqu’un, vous entendez qu’il n’est pas dans un bon jour. Vous savez prendre soin des gens et vous êtes très loyal ; attention, vos émotions s’accumulent et vous avez du mal à lâcher prise quand on vous blesse. Confiez-vous à une personne sûre.`,
`Celui que l’on voit est discret et mystérieux ; celui de l’intérieur a besoin d’être vu. Au travail, vous maîtrisez la situation en silence, mais vous aimeriez qu’on reconnaisse vos efforts. Vous avez beaucoup d’influence ; dans les moments de tiraillement, la fierté vous empêche de faire le premier geste. Celui qui parle en premier n’a pas perdu : c’est lui qui tient la relation en main.`,
`Dehors, vous êtes profond ; dedans, vous êtes minutieux : une combinaison très perspicace. Vous trouvez souvent la cause d’un problème avant même que les autres ne le remarquent. Vous êtes fait pour la recherche et l’analyse ; l’angle mort, c’est la tendance à douter et à vous inquiéter. Notez vos inquiétudes, puis jugez lesquelles demandent vraiment à être traitées.`,
`Celui que l’on voit est intense et tenace ; celui de l’intérieur a besoin d’harmonie. Vous voulez aller au fond des choses, tout en craignant d’abîmer la bonne entente. Vous avez du charme et vous savez juger les gens ; dans les moments de tiraillement, vous faites mine de suivre tout en étant mécontent. Dites ce que vous pensez vraiment, avec douceur : la relation n’en sera que plus solide.`,
`Dedans comme dehors, vous êtes Scorpion : passionné, tenace, d’une volonté extrême. Quand vous aimez, c’est corps et âme, et quand on vous déçoit, vous vous en souvenez longtemps. Vous avez le don de renaître de vos cendres ; attention, des émotions trop profondes vous font facilement tourner en rond. Offrez-vous un rituel pour lâcher prise, comme écrire une lettre que vous n’enverrez pas.`,
`Celui que l’on voit est profond ; celui de l’intérieur est optimiste et épris de liberté. D’habitude concentré sur votre travail, vous organisez soudain un long voyage dès que viennent les vacances. Vous avez de la profondeur et de l’étendue ; dans les moments de tiraillement, vous oscillez entre « creuser une chose à fond » et « aller voir plus loin ». En réalité, vous avez besoin des deux.`,
`Dehors, vous êtes profond ; dedans, vous êtes pragmatique : une combinaison très ambitieuse. Vous accumulez vos forces en silence et n’agissez que lorsque le moment est mûr. Vous savez maîtriser une situation ; attention, vos émotions sont enfouies si loin que vous paraissez très froid. Laissez parfois vos proches voir votre côté vulnérable.`,
`Celui que l’on voit s’investit intensément ; celui de l’intérieur a besoin de prendre du recul. Vous pouvez tout donner pour un idéal, mais vous n’aimez pas que quiconque se mêle de votre vie privée. Vous avez une vraie force de transformation ; dans les moments de tiraillement, vous êtes tantôt collant, tantôt distant. Faites savoir à votre entourage que vous avez besoin d’espace.`,
`Dedans comme dehors, vous êtes un signe d’eau : sensible, passionné, très intuitif. Vous faites souvent des rêves très réalistes, ou vous avez des intuitions inexplicables à propos d’inconnus. Vous avez un talent pour la guérison et la création ; attention à ne pas vous laisser submerger par vos émotions. Trouvez des moyens de revenir au réel, comme le sport ou les tâches ménagères.`
],
/* Soleil en Sagittaire */
[
`Dedans comme dehors, vous êtes un signe de feu : enthousiaste, direct, avide d’aventure. Un ami parle d’apprendre la plongée, et vous êtes le premier inscrit. Votre énergie est contagieuse ; l’angle mort, c’est l’impulsivité : vous vous rendez souvent compte après coup que vous n’avez pas le temps. Avant de dire « oui », jetez un œil à votre agenda et gardez du temps pour ceux à qui vous avez déjà promis quelque chose.`,
`Celui que l’on voit aime la liberté ; celui de l’intérieur a besoin de sécurité. Vous rêvez de faire le tour du monde, mais avant de partir vous devez avoir mis assez d’argent de côté. Vos rêves ont ainsi plus de chances de se réaliser ; dans les moments de tiraillement, vous hésitez entre aventure et sécurité. Fixez-vous d’abord un budget aventure, et vous aurez les deux.`,
`Votre Soleil et votre Lune sont en opposition : dehors, vous cherchez les grandes vérités ; dedans, vous avez besoin de toutes sortes de petites informations. Vous pouvez passer d’un livre de philosophie à un mème Internet dans la même conversation. Vous savez enseigner et raconter ; dans les moments de tiraillement, vous voulez tout apprendre et ne finissez rien. Choisissez d’abord une chose et menez-la au bout.`,
`Celui que l’on voit aime explorer ; celui de l’intérieur a besoin de la chaleur du foyer. Vous adorez partir à l’étranger, mais dès le cinquième jour la cuisine de la maison vous manque. Vous alliez optimisme et chaleur ; la maison sera toujours là, vous pouvez partir vous promener, il suffit de rapporter quelques histoires à vos proches.`,
`Dedans comme dehors, vous êtes un signe de feu : confiant, optimiste, aimant être sur le devant de la scène. Quand vous racontez vos voyages en soirée, tout le monde est suspendu à vos lèvres. Vous avez un charisme de meneur ; attention à trop en dire et trop promettre, comme proposer une sortie à tout le monde puis ne pas trouver le temps. Faire convainc plus que dire.`,
`Celui que l’on voit vise la vue d’ensemble ; celui de l’intérieur soigne les détails. Vous voulez partir en Amérique du Sud, et en même temps vous vérifiez chaque étape et chaque poste du budget. Vous alliez vision et sens de l’exécution ; dans les moments de tiraillement, trop d’inquiétude vous empêche de partir. Un plan prêt à soixante-dix pour cent suffit pour se mettre en route.`,
`Celui que l’on voit aime la liberté ; celui de l’intérieur a besoin d’harmonie et de compagnie. Vous aimez voyager seul, mais au retour vous aimeriez beaucoup que quelqu’un écoute vos récits. Vous vous faites facilement des amis ; dans les moments de tiraillement, vous oscillez entre indépendance et compagnie. Dites franchement à votre entourage l’équilibre dont vous avez besoin.`,
`Celui que l’on voit est optimiste et ouvert ; celui de l’intérieur est profond et tenace. Vous semblez indifférent à tout, alors que vous vous souvenez de chaque déception. Vous avez du flair et des idéaux ; dans les moments de tiraillement, vous êtes désinvolte en apparence et tourmenté au fond. Trouvez une personne de confiance à qui dire la vérité.`,
`Dedans comme dehors, vous êtes Sagittaire : optimiste, épris de liberté, en quête de sens. Vous pouvez décider sur un coup de tête d’aller vivre un mois dans une ville dont vous n’aviez jamais entendu parler. Vous savez donner de l’espoir ; attention, vous détestez être lié et vous avez tendance à fuir quand vient l’engagement. La liberté n’est pas l’irresponsabilité.`,
`Celui que l’on voit est optimiste et exubérant ; celui de l’intérieur est sérieux et pragmatique. Vous dites « la vie, c’est l’aventure », alors qu’en privé votre retraite est déjà provisionnée. Vos idéaux ont ainsi les moyens de se réaliser ; dans les moments de tiraillement, vous êtes trop dur avec vous-même. Accordez-vous de temps en temps un week-end de vraie détente.`,
`Celui que l’on voit aime explorer ; celui de l’intérieur a besoin d’indépendance et d’innovation. Vous participez à toutes sortes de clubs de lecture et d’associations, et vous lancez souvent vous-même de nouvelles activités. Vous avez des idéaux et vous tenez à vos amis ; attention à une certaine distance affective : quand l’autre a besoin de présence, posez votre téléphone et écoutez vraiment.`,
`Celui que l’on voit est optimiste ; celui de l’intérieur est sensible et romantique, et les deux signes sont traditionnellement gouvernés par Jupiter. Un idéal ou une histoire peut vous toucher au point de changer le cours de votre vie. Vous avez de la foi et de l’empathie ; dans les moments de tiraillement, vous êtes trop idéaliste. Passez vos rêves au filtre d’un peu de réalisme.`
],
/* Soleil en Capricorne */
[
`Celui que l’on voit est posé ; celui de l’intérieur est impatient et combatif. Vous avancez méthodiquement en apparence, alors qu’au fond vous voudriez être promu dès demain. Vous avez de l’ambition et du dynamisme ; dans les moments de tiraillement, vous êtes trop exigeant envers vous et les autres. Le repos fait aussi partie du plan : inscrivez le sommeil et le sport dans votre agenda.`,
`Dedans comme dehors, vous êtes un signe de terre : pragmatique, stable, très endurant. Depuis l’enfance, vous savez qu’il faut épargner, et vous suivez toujours votre plan. On peut vous faire entière confiance ; le point à surveiller, c’est un excès de prudence qui vous fait rater de bonnes occasions. Essayez parfois quelque chose de nouveau, comme un autre trajet pour aller au travail ou un plat jamais goûté.`,
`Celui que l’on voit est sérieux et appliqué ; celui de l’intérieur est curieux et bavard. En réunion, vous êtes très professionnel, mais après le travail vous pouvez discuter d’anecdotes insolites avec vos amis jusqu’au milieu de la nuit. Vous alliez compétence et souplesse ; dans les moments de tiraillement, vous trouvez que vous manquez de concentration. En réalité, la variété de vos intérêts rend votre expertise plus créative.`,
`Votre Soleil et votre Lune sont en opposition : dehors, vous visez la réussite ; dedans, vous avez besoin de la chaleur du foyer. Vous faites des heures supplémentaires pour votre famille, et du coup vous dînez rarement avec elle. Vous avez un grand sens des responsabilités ; dans les moments de tiraillement, vous culpabilisez entre travail et famille. Bloquer des moments fixes en famille vaut mieux que de compenser après coup.`,
`Celui que l’on voit est discret et pragmatique ; celui de l’intérieur a soif de reconnaissance. Vous obtenez des résultats en silence, et vous aimeriez beaucoup que votre patron et votre famille les voient. Vous avez l’étoffe d’un dirigeant ; dans les moments de tiraillement, vous tenez trop aux titres et aux apparences. Une vraie réussite n’a pas besoin de l’approbation des autres pour exister.`,
`Dedans comme dehors, vous êtes un signe de terre : sérieux, minutieux, très endurant à l’effort. Vous êtes sans doute le premier arrivé et le dernier parti au bureau. On peut vous faire confiance ; le point à surveiller, c’est une exigence excessive envers vous-même, qui vous fait refuser le repos tant que ce n’est pas assez bien. Offrez-vous chaque jour une petite récompense : un bon café ou une promenade, ça compte.`,
`Celui que l’on voit est sérieux et a des principes ; celui de l’intérieur a besoin d’harmonie et de beauté. Au travail, vous êtes très carré, mais chez vous l’éclairage et la décoration comptent beaucoup. Vous alliez compétence et popularité ; dans les moments de tiraillement, vous refoulez vos vrais griefs pour préserver la paix. Exprimez-les avec douceur, la relation n’en durera que plus longtemps.`,
`Dehors, vous êtes posé ; dedans, vous êtes profond : une combinaison très puissante. Vous prenez rarement position, mais quand vous agissez, c’est efficace. Vous savez maîtriser une situation ; le point à surveiller, c’est une méfiance excessive qui vous rend difficile d’accès. Laissez parfois voir votre douceur : inviter un ami à dîner est un très bon début.`,
`Celui que l’on voit est pragmatique ; celui de l’intérieur rêve de liberté et d’aventure. Vous travaillez avec régularité, et vous mettez de côté vos congés toute l’année pour un grand voyage annuel. Vous alliez ambition et idéal ; dans les moments de tiraillement, vous vous sentez prisonnier de vos responsabilités. Gardez-vous des espaces où vous pouvez choisir librement.`,
`Dedans comme dehors, vous êtes Capricorne : objectifs clairs, grand sens des responsabilités. À vingt ans, vous avez peut-être déjà écrit ce que vous voulez avoir accompli à quarante. Vous êtes capable de grandes choses ; attention, vous enfouissez vos émotions si profondément que vous paraissez froid, et vous allez travailler même malade. Vous aussi avez le droit d’être pris en charge.`,
`Celui que l’on voit respecte les règles ; celui de l’intérieur a besoin d’indépendance et d’innovation, et les deux signes sont traditionnellement gouvernés par Saturne. Dans une entreprise très classique, c’est vous qui imaginez les méthodes les plus modernes. Vous avez une vraie capacité de réforme ; trouvez une place qui vous permette à la fois de préserver la structure et d’innover.`,
`Celui que l’on voit est pragmatique et sérieux ; celui de l’intérieur est tendre et romantique. Le jour, vous êtes un responsable exigeant ; le soir, un film peut vous faire pleurer. Vous alliez compétence et empathie ; dans les moments de tiraillement, vous voyez la sensibilité comme une faiblesse. En réalité, votre douceur est votre meilleur atout de leader.`
],
/* Soleil en Verseau */
[
`Celui que l’on voit est rationnel et indépendant ; celui de l’intérieur est impulsif et passionné. En réunion, vous pointez calmement les failles du système, et dès la fin de la séance vous rédigez une nouvelle procédure. Vous avez une vraie force de réforme ; dans les moments de tiraillement, la lenteur des autres vous agace. Tout le monde n’est pas aussi rapide que vous.`,
`Celui que l’on voit cherche l’innovation ; celui de l’intérieur a besoin de stabilité. Vos idées sont avant-gardistes, mais votre emploi du temps est très régulier : le même café, à la même heure, tous les jours. Vos idées ont ainsi plus de chances de se concrétiser ; dans les moments de tiraillement, vous hésitez entre changement et sécurité. Le changement peut se faire pas à pas.`,
`Dedans comme dehors, vous êtes un signe d’air : intelligent, curieux, ami de tout le monde. Vous pouvez discuter extraterrestres et urbanisme avec une bande d’amis jusqu’au lever du jour. Vous êtes très créatif ; attention à des émotions qui restent dans la tête : en amour, ce dont on a besoin, c’est de présence, pas seulement de conversations intéressantes.`,
`Celui que l’on voit est indépendant et rationnel ; celui de l’intérieur a besoin d’appartenance et d’attention. Vous avez l’air très cool, mais en réalité il compte beaucoup pour vous que vos amis vous considèrent comme l’un des leurs. Vous alliez idéal et chaleur ; dans les moments de tiraillement, vous n’osez pas exprimer vos besoins. Les dire ne vous rendra pas moins indépendant.`,
`Votre Soleil et votre Lune sont en opposition : dehors, vous voulez vous fondre dans le groupe ; dedans, vous avez besoin d’être vu. Vous vous dévouez pour votre association, et vous aimeriez aussi qu’on se souvienne de votre nom. Vous avez l’étoffe d’un meneur ; trouvez une place qui vous permette à la fois de briller et d’aider tout le monde, et le tiraillement deviendra un moteur.`,
`Celui que l’on voit est rationnel et innovant ; celui de l’intérieur tient aux détails et à l’ordre. Vous avez une nouvelle idée, et le soir même elle est transformée en étapes réalisables. Vous savez résoudre les problèmes ; dans les moments de tiraillement, vous êtes trop rationnel. Quand votre partenaire se plaint, réconfortez d’abord, proposez des solutions ensuite : souvent, il suffit de dire « tu en as fait beaucoup ».`,
`Dedans comme dehors, vous êtes un signe d’air : rationnel, amical, attaché à l’équité. Quand des amis se disputent, vous exposez calmement les arguments des deux côtés. Vous êtes très apprécié ; attention à une certaine distance affective : quand l’autre a besoin d’un câlin, répondez par un geste. Une étreinte vaut mieux que dix raisonnements.`,
`Celui que l’on voit est rationnel et calme ; celui de l’intérieur est profond et tenace. Vous semblez ne vous soucier de rien, alors que vous éprouvez des sentiments très forts. Vous avez du flair et une force de transformation ; dans les moments de tiraillement, vous refoulez vos émotions : serein en surface, en pleine tempête au fond. Trouvez une personne de confiance à qui en parler.`,
`Celui que l’on voit cherche l’innovation ; celui de l’intérieur rêve de liberté et d’aventure. Vous pourriez démissionner pour rejoindre un programme de volontariat à l’étranger. Vous avez des idéaux et du courage ; attention, votre amour de la liberté vous fait facilement fuir quand vient l’engagement. La liberté a besoin de racines : avec un endroit où revenir, vous volerez plus loin.`,
`Celui que l’on voit est indépendant et innovant ; celui de l’intérieur est pragmatique et sérieux. Vous avez des idées très avant-gardistes, mais vous les concrétisez pas à pas à l’aide d’un tableur. Vous avez le pouvoir de réaliser ; dans les moments de tiraillement, vous refoulez vos émotions et vous en oubliez de manger. Vous aussi avez le droit de vous reposer et d’être pris en charge.`,
`Dedans comme dehors, vous êtes Verseau : indépendant, rationnel, singulier. Depuis l’enfance, vous ne pensez pas comme vos camarades et vous n’avez pas peur de passer pour un original. Vous avez de la créativité et des idéaux ; attention à trop de distance affective. Laissez parfois vos proches entrer dans votre monde intérieur et racontez-leur ce qui vous occupe vraiment en ce moment.`,
`Celui que l’on voit est rationnel et indépendant ; celui de l’intérieur est sensible et romantique. Vous paraissez très calme, mais la souffrance des gens aux informations peut vous attrister pendant des jours. Vous alliez idéal et empathie ; dans les moments de tiraillement, vous ne savez pas s’il faut décider avec la tête ou avec le cœur. Écoutez les deux.`
],
/* Soleil en Poissons */
[
`Celui que l’on voit est doux et accommodant ; celui de l’intérieur est impatient et direct. D’ordinaire très conciliant, vous pouvez exploser quand on vous pousse à bout, au point d’effrayer votre entourage. Vous alliez empathie et courage ; dans les moments de tiraillement, vous refoulez votre colère. Exprimez votre mécontentement dès les petites choses, et vous éviterez la grande explosion.`,
`Celui que l’on voit est romantique et spontané ; celui de l’intérieur a besoin de stabilité et de confort. Vous aimez rêver, mais il vous faut un foyer sûr pour bien dormir. Vos rêves ont ainsi des racines ; dans les moments de tiraillement, vous voulez tantôt vous envoler, tantôt vous cacher. Offrez-vous un petit rituel fixe, comme une tasse de tisane avant de dormir.`,
`Celui que l’on voit est sensible et doux ; celui de l’intérieur est curieux et bavard. Les histoires vous touchent facilement, et vous adorez partager toutes sortes de choses amusantes avec vos amis. Vous êtes fait pour l’écriture et l’enseignement ; dans les moments de tiraillement, vous êtes submergé d’informations. Gardez chaque jour un moment sans téléphone pour laisser votre esprit s’apaiser.`,
`Dedans comme dehors, vous êtes un signe d’eau : doux, sensible, plein d’empathie. Quand vous voyez quelqu’un triste, vous avez vous aussi les larmes aux yeux. Vous savez prendre soin des autres ; veillez à vos limites, ne portez pas toutes les émotions des autres. Si un ami vient pleurer tard le soir, vous pouvez l’écouter une heure, puis aller bien dormir.`,
`Celui que l’on voit est doux et discret ; celui de l’intérieur a besoin d’être vu. Vous avez un vrai talent artistique, mais vous n’osez souvent pas montrer vos œuvres. Vous avez un grand pouvoir de contagion ; dans les moments de tiraillement, la peur de la critique vous fait vous cacher. Montrez d’abord votre travail à un ou deux amis de confiance, puis, encouragé, avancez peu à peu vers une scène plus grande.`,
`Votre Soleil et votre Lune sont en opposition : dehors, vous êtes romantique et sensible ; dedans, vous tenez aux détails et à l’ordre. Vous pouvez rêvasser tout en vous inquiétant de ne pas avoir bien fait les choses. Vous alliez empathie et sens de l’exécution ; dans les moments de tiraillement, vous êtes trop dur avec vous-même. Rappelez-vous que le désordre fait aussi partie de la création.`,
`Celui que l’on voit est doux et romantique ; celui de l’intérieur a besoin d’harmonie et de beauté. Vous adorez décorer votre intérieur et vous tenez beaucoup à ce que votre entourage soit heureux. Vous avez un vrai talent artistique et vous êtes apprécié ; dans les moments de tiraillement, vous vous sacrifiez pour l’harmonie. Rappelez-vous que dire « non » est aussi une forme de douceur.`,
`Dedans comme dehors, vous êtes un signe d’eau : sensible, passionné, très intuitif. Vous faites souvent des rêves très réalistes, ou vous sentez au premier regard que quelque chose cloche chez quelqu’un. Vous avez un talent pour la guérison et la création ; attention à ne pas vous laisser submerger par vos émotions. Trouvez des moyens de revenir au réel.`,
`Celui que l’on voit est sensible et doux ; celui de l’intérieur est optimiste et épris de liberté, et les deux signes sont traditionnellement gouvernés par Jupiter. Pour un idéal, vous pourriez partir enseigner dans une région reculée. Vous avez de la foi et de l’empathie ; dans les moments de tiraillement, vous êtes trop idéaliste. Passez vos rêves au filtre d’un peu de réalisme.`,
`Celui que l’on voit est romantique et spontané ; celui de l’intérieur est pragmatique et sérieux. Vous avez l’air arrangeant, mais vous avez déjà votre plan et vos limites. Vous alliez le rêve et la capacité de le réaliser ; dans les moments de tiraillement, vous voyez la sensibilité comme une faiblesse. En réalité, votre douceur est votre plus grande force : elle adoucit même les situations les plus tendues.`,
`Celui que l’on voit est sensible et doux ; celui de l’intérieur a besoin d’indépendance et d’espace. Vous compatissez facilement aux autres, mais il vous faut aussi du temps seul. Vous alliez empathie et idéal ; dans les moments de tiraillement, vous vous rapprochez puis vous vous éloignez. Faites savoir à votre entourage que c’est votre façon de recharger les batteries.`,
`Dedans comme dehors, vous êtes Poissons : doux, romantique, plein d’imagination. Vous avez souvent l’air dans la lune, alors qu’un film entier se déroule dans votre tête. Vous avez un talent pour l’art et la guérison ; attention à des limites floues qui vous rendent perméable aux émotions des autres. Pensez à protéger votre énergie.`
]
],
scenes:{
ASC:[
`Par exemple, le premier jour dans une nouvelle entreprise, à peine assis, vous demandez à votre responsable « par quoi puis-je commencer ? », et la première impression de vos collègues est : quelle énergie !`,
`Par exemple, un ami vous emmène à une soirée ; vous restez tranquillement dans un coin à grignoter, et pourtant tout le monde se souvient de « cette personne qui avait l’air si posée, si solide », et quelqu’un vous demande même quel parfum vous portez.`,
`Par exemple, en trois minutes de queue pour un café, vous discutez déjà avec l’inconnu devant vous des grains de la maison, et en partant il vous dit « c’était vraiment sympa de parler avec vous ».`,
`Par exemple, dans un atelier où vous ne connaissez personne, vous choisissez d’abord une place contre le mur pour observer ; quand quelqu’un vient vous parler, vous vous déridez peu à peu, et avant la fin vous distribuez déjà des en-cas à tout le monde.`,
`Par exemple, vous entrez dans une fête et, avant même que vous ayez dit un mot, des têtes se tournent ; vous saluez chacun avec naturel, et tout le monde vous voit comme l’une des vedettes de la soirée.`,
`Par exemple, à un entretien d’embauche, vous arrivez dix minutes en avance, votre CV est impeccable et vos réponses structurées ; le recruteur dira ensuite : « on peut lui confier quelque chose sans s’inquiéter ».`,
`Par exemple, au mariage d’un ami, face à une table d’inconnus, votre sourire est juste et vous savez relancer la conversation ; à la fin, tout le monde dit : « quelle classe, et si agréable à qui parler ».`,
`Par exemple, un nouveau collègue se présente longuement ; vous ne répondez que brièvement, mais vous retenez chaque détail de ce qu’il a dit, et il a l’impression que vous êtes difficile à cerner.`,
`Par exemple, inscrit à une randonnée d’une journée, vous plaisantez déjà avec le guide au point de rendez-vous, et le groupe fait très vite de vous son boute-en-train.`,
`Par exemple, la première fois que vous rencontrez les parents de votre partenaire, votre tenue est soignée, vous parlez peu mais chaque mot porte, et ils se disent en privé : « cette personne a l’air très sérieuse, on peut être tranquilles ».`,
`Par exemple, en vous présentant dans un club de lecture, vous avancez un point de vue totalement différent des autres ; la salle reste interdite deux secondes, puis plusieurs personnes viennent vous parler après la séance.`,
`Par exemple, au restaurant, face à l’ami d’un ami que vous voyez pour la première fois, vous l’écoutez avec douceur en hochant la tête et en souriant, et en rentrant il se dit : « je me suis senti compris ».`
],
Sun:[
`Par exemple, face à deux offres d’emploi, vous choisissez la plus difficile, celle qui vous permet de piloter quelque chose de nouveau, parce que rien que d’y penser vous enflamme.`,
`Par exemple, pour changer de téléphone, vous utilisez l’ancien jusqu’au bout, puis vous en choisissez un aux avis solides qui tiendra encore cinq ans : quand on dépense, autant que ce soit utile.`,
`Par exemple, au moment de choisir vos études, vous avez finalement opté pour un cursus touchant à plusieurs domaines à la fois, de peur d’être enfermé dans une seule réponse.`,
`Par exemple, quand on vous propose une mutation dans une autre région, votre première pensée va à votre famille, et vous n’acceptez qu’une fois tout bien organisé à la maison.`,
`Par exemple, quand l’équipe décide qui présentera le projet, vous levez la main, parce que vous savez que c’est sur scène que vous êtes le plus vivant et que vous mettrez le mieux en valeur le travail de tous.`,
`Par exemple, quand vous hésitez entre deux options, vous dressez une liste des pour et des contre, et vous ne décidez sereinement qu’une fois le dernier détail vérifié.`,
`Par exemple, pour le programme du week-end, vous demandez d’abord l’avis de votre partenaire et de vos amis, vous trouvez ce qui plaît à tout le monde, et vous découvrez finalement que vous aussi vous vous amusez bien.`,
`Par exemple, avant d’accepter un projet important, vous vous renseignez discrètement sur tous les tenants et aboutissants, et quand vous êtes sûr de pouvoir vous y donner entièrement, vous dites un oui sans retour.`,
`Par exemple, en fin d’année, en réfléchissant à une formation à l’étranger, ce qui compte le plus pour vous, c’est « est-ce que ma vie en sera plus vaste ? » ; le salaire passe après.`,
`Par exemple, face à une opportunité de reconversion, vous calculez d’abord votre position et votre courbe de revenus à trois ans, et vous ne démissionnez qu’une fois sûr que c’est un pas vers le haut.`,
`Par exemple, quand tout le monde se jette sur le même produit à la mode, vous allez plutôt étudier celui qui est moins connu mais plus intéressant, parce que suivre le mouvement ne vous attire pas.`,
`Par exemple, quand un ami vous propose d’ouvrir une boutique ensemble, vous acceptez ou refusez sur une impression difficile à expliquer, et avec le recul cette intuition s’avère souvent juste.`
],
Moon:[
`Par exemple, quand un collègue s’attribue votre travail, votre visage se ferme aussitôt et vous dites directement « c’est moi qui l’ai fait » ; une fois dit, la colère est presque retombée.`,
`Par exemple, un soir de mauvaise humeur, vous allez manger un bon repas que vous aimez ou vous vous blottissez sous la couette devant une série ; bien nourri et bien reposé, vous allez déjà beaucoup mieux le lendemain.`,
`Par exemple, quand vous êtes triste, vous appelez trois amis et vous racontez l’histoire à chacun ; à la troisième fois, vous avez déjà en grande partie compris ce qui se passait.`,
`Par exemple, quand votre partenaire vous a ignoré toute la journée, vous ne dites rien, mais le dîner est particulièrement silencieux, et vous attendez qu’il remarque votre peine.`,
`Par exemple, quand vos amis oublient votre anniversaire, vous dites que ce n’est pas grave, mais vous ruminez jusqu’au soir, et ce n’est que lorsque quelqu’un vous souhaite enfin un « bon anniversaire » que vous retrouvez le sourire.`,
`Par exemple, quand l’anxiété monte, vous vous mettez à faire le ménage et à ranger vos tiroirs ; une fois les choses bien alignées, votre esprit se calme peu à peu.`,
`Par exemple, après un petit froissement avec un ami, vous vous demandez sans cesse « est-ce que j’ai dit quelque chose de travers ? », et vous ne dormez bien qu’une fois les choses éclaircies entre vous.`,
`Par exemple, quand une personne de confiance vous a menti une fois, vous restez calme en apparence, mais vous la sortez discrètement de votre cercle intime, et pendant très longtemps vous ne vous confierez plus à elle.`,
`Par exemple, quand le moral est en berne, vous réservez soudain un billet de train pour une ville inconnue ; voir d’autres paysages suffit à vous ouvrir le cœur.`,
`Par exemple, quand on vous a fait du tort, vous terminez d’abord votre travail, et ce n’est que tard le soir, au calme, que vous vous autorisez un peu de tristesse ; le lendemain, vous partez à l’heure comme d’habitude.`,
`Par exemple, quand un ami vient pleurer auprès de vous, vous analysez d’abord calmement toute l’histoire, et ce n’est qu’une fois qu’il est apaisé que vous réalisez que vous aussi avez été touché.`,
`Par exemple, après un film émouvant, vous pleurez en silence à la sortie de la salle, et pendant plusieurs jours vous restez plongé dans cette histoire sans pouvoir en sortir.`
],
Venus:[
`Par exemple, quand quelqu’un vous plaît, vous lui envoyez directement un message pour l’inviter au cinéma ce week-end ; si c’est non, vous souriez simplement et vous dites « une autre fois, alors ».`,
`Par exemple, pour un rendez-vous, vous choisissez un restaurant fiable avec des sièges confortables ; pour vous, un dîner savouré lentement est le comble du romantisme.`,
`Par exemple, au premier rendez-vous, vous passez du cinéma aux voyages puis à l’enfance, et en rentrant ce qui compte le plus pour vous, c’est : « est-ce qu’on s’entend bien quand on parle ? ».`,
`Par exemple, une fois en couple, vous retenez ce que l’autre ne mange pas et sa boisson préférée, et les jours de pluie vous apportez un parapluie de plus pour venir le chercher à la gare.`,
`Par exemple, pour l’anniversaire de l’autre, vous organisez avec soin une journée entière de surprises, et vous espérez aussi qu’il réponde à cette attention avec le même enthousiasme.`,
`Par exemple, au début d’une relation, vous observez discrètement si l’autre est ponctuel ou s’il jette ses déchets n’importe où ; une fois les détails validés, vous osez vous attacher.`,
`Par exemple, avant un rendez-vous, vous passez beaucoup de temps à choisir votre tenue et un restaurant qui a du charme ; pour vous, les belles images font partie de l’amour.`,
`Par exemple, quand quelqu’un vous plaît, vous ne le dites pas, mais vous retenez en silence chaque phrase qu’il prononce ; une fois sûr de vous, vous vous donnez entièrement.`,
`Par exemple, en rendez-vous, vous proposez une randonnée ou l’apprentissage de quelque chose de nouveau ensemble ; pour vous, partager une aventure est plus romantique que de rester assis au restaurant.`,
`Par exemple, avant de vous engager, vous observez d’abord l’attitude de l’autre au travail et son milieu familial ; une fois sûr que cette personne vaut une relation durable, vous vous ouvrez peu à peu.`,
`Par exemple, avec quelqu’un qui vous plaît, vous discutez d’abord comme de simples amis, et ce n’est que bien plus tard que vous vous rendez compte que vous vous aimez ; c’est la façon de faire où vous êtes le plus à l’aise.`,
`Par exemple, une phrase tendre de l’autre peut vous émouvoir pendant des jours, et vous êtes prêt à changer beaucoup de vos habitudes pour lui.`
],
Mars:[
`Par exemple, quand quelqu’un vous double dans une file, vous allez directement lui dire « excusez-moi, la queue est derrière », puis vous passez à autre chose sans y repenser.`,
`Par exemple, pour obtenir une certification, vous révisez deux heures par jour sans interruption pendant un mois, deux mois, et le jour de l’examen vous réussissez du premier coup, sans trembler.`,
`Par exemple, dans un débat, vous enchaînez questions et exemples jusqu’à laisser l’autre sans voix, mais une fois la dispute finie vous pouvez très vite aller déjeuner ensemble.`,
`Par exemple, quand on critique votre famille, vous vous retenez d’abord, mais si quelqu’un franchit la ligne, vous devenez redoutable pour la protéger, et rien ne vous arrête.`,
`Par exemple, en compétition ou en présentation, vous donnez tout, en espérant prouver votre valeur par de beaux résultats et remonter au passage le moral de toute l’équipe.`,
`Par exemple, quand un projet déraille, vous ne vous disputez avec personne : vous repérez et corrigez les erreurs une à une en silence, et vous laissez les résultats parler.`,
`Par exemple, quand un collègue vous traite injustement, vous prenez le temps de lui parler en privé et vous défendez vos droits par le raisonnement plutôt que par une grosse dispute.`,
`Par exemple, quand on vous trahit, vous ne faites pas d’esclandre sur le moment, mais vous notez tout calmement, et le moment venu vous coupez les ponts de façon nette et définitive.`,
`Par exemple, pour perdre du poids, vous vous inscrivez d’un coup à un marathon comme objectif, et vous trouvez du plaisir en courant, en entretenant votre feu tout du long.`,
`Par exemple, pour obtenir une promotion, vous rédigez un plan sur trois ans, vous vérifiez vos progrès chaque trimestre et vous montez marche après marche, sans compter sur la chance ni prendre de raccourci.`,
`Par exemple, face à une règle absurde, vous ne protestez pas sur-le-champ : vous allez trouver des gens qui pensent comme vous pour proposer ensemble une meilleure solution.`,
`Par exemple, face à un conflit, vous choisissez souvent de reculer d’un pas et de contourner l’obstacle en douceur, puis, une fois les émotions retombées, de traiter le problème tranquillement.`
],
Mercury:[
`Par exemple, en réunion, vous proposez souvent une solution avant même que votre responsable ait fini de parler ; c’est parfois trop rapide, mais vous êtes souvent le premier à trouver la direction.`,
`Par exemple, pour apprendre une nouvelle compétence, vous partez patiemment des bases ; vous n’allez pas vite, mais une fois acquis, c’est gravé et vous vous trompez rarement.`,
`Par exemple, pendant une réunion, vous suivez trois sujets à la fois tout en résumant en direct l’essentiel dans le groupe de discussion pour les collègues absents.`,
`Par exemple, ce que vous retenez le plus facilement, c’est « ce que les gens ressentaient à ce moment-là », et vous entendez souvent au ton de la voix qui n’est pas content en réalité.`,
`Par exemple, quand vous présentez un exposé, vous transformez les données en une histoire avec des rebondissements, et l’auditoire est captivé et retient l’essentiel.`,
`Par exemple, en lisant un contrat ou un rapport, vous repérez d’un coup d’œil les coquilles et les chiffres qui ne collent pas ; vous êtes souvent le dernier filet de sécurité de l’équipe.`,
`Par exemple, quand une réunion est dans l’impasse, vous dites « écoutons d’abord les raisons des deux côtés », et vous transformez des avis opposés en une proposition acceptable pour tous.`,
`Par exemple, en découvrant un nouveau domaine, vous ne vous contentez pas de la surface : vous voulez creuser jusqu’au bout, au point de lire souvent jusqu’à deux ou trois heures du matin sans pouvoir vous arrêter.`,
`Par exemple, en cours, ce que vous préférez, ce sont les moments où le professeur parle des grandes idées et de la vie ; les détails, eux, entrent par une oreille et ressortent par l’autre.`,
`Par exemple, en rédigeant un projet, vous posez d’abord les objectifs, les étapes, le calendrier et le budget, avec une structure si claire que votre responsable approuve d’un coup d’œil.`,
`Par exemple, en séance de remue-méninges, vous proposez souvent des idées auxquelles personne n’avait pensé ; jugées bizarres au début, elles finissent souvent par être retenues.`,
`Par exemple, quand vous étudiez, vous avez du mal à apprendre par cœur, mais avec des images ou des histoires vous retenez tout du premier coup, et pour très longtemps.`
]
},
aspects:{
'Sun-Moon':[
`Ce que vous voulez et ce dont vous avez besoin vont presque toujours dans le même sens, et vos décisions vous coûtent rarement. Si vous voulez changer de travail, il suffit que votre cœur dise oui pour que vous envoyiez des CV dès le lendemain. Simplement, il ne vous est pas toujours facile de voir les choses du point de vue des autres.`,
`Votre volonté et vos émotions se soutiennent, et il suffit de prendre soin de vous activement pour retrouver l’équilibre. Quand la pression monte, vous savez qu’une promenade ou un repas entre amis vous remettra vite d’aplomb.`,
`Vous avez souvent l’impression que « ce que veut la tête » et « ce dont le cœur a besoin » se disputent. Vous voulez une promotion, mais vous ne voulez pas renoncer à vos soirées de détente ; vous ne lâchez ni l’un ni l’autre, et ce tiraillement vous pousse aussi à mieux vous connaître.`,
`Vos objectifs extérieurs et vos ressentis intérieurs sont en accord, ce qui donne une impression d’aisance et de stabilité. Le travail et le mode de vie que vous choisissez vous rendent souvent heureux par la même occasion, sans que vous ayez besoin de vous forcer.`,
`Vous oscillez souvent entre « ce que je veux » et « ce dont j’ai besoin ». Très indépendant à l’extérieur, vous avez très envie qu’on s’occupe de vous à la maison ; la relation de couple est souvent le lieu où vous voyez ces deux faces et apprenez à les équilibrer.`
],
'Sun-Mercury':[
`Vos idées sont liées à votre identité, et vous parlez avec beaucoup d’assurance. En réunion, une fois votre avis donné, vous avez du mal à revenir dessus, parce qu’il vous représente. Apprenez à distinguer « mon idée » de « moi », et les discussions seront plus fluides.`,
``,``,``,``
],
'Sun-Venus':[
`Vous avez un charme naturel et vous savez vous faire aimer. En soirée, vous complimentez spontanément et vous soignez l’ambiance, et tout le monde adore être avec vous ; attention aussi à vouloir tellement plaire que vous n’osez plus dire la vérité.`,
``,
``,``,``
],
'Sun-Mars':[
`Votre volonté et votre énergie d’action sont liées, et vous agissez avec beaucoup d’élan. Une fois décidé à perdre du poids, vous commencez à courir tous les jours dès le lendemain ; attention à un tempérament prompt qui vous fait parler trop durement dans les disputes.`,
`Votre énergie d’action a un bon sens de l’orientation : il suffit d’un peu d’initiative pour transformer vos idées en résultats. Si vous voulez apprendre un sport, une fois inscrit vous vous entraînez avec régularité et vous progressez vite.`,
`Vous avez souvent l’impression que votre élan se grippe, ou vous entrez facilement en conflit. Vous voulez bien faire, et vous vous retrouvez à vous disputer avec un collègue sur la méthode ; apprendre à transformer la colère en action, c’est là votre plus grande force.`,
`Vos actions sont naturelles et efficaces, sans que vous ayez à vous forcer. Face à un défi, vous trouvez vite comment le relever, et vous donnez une impression de fiabilité et d’énergie.`,
`Vous rencontrez souvent des « adversaires » chez les autres, comme ce collègue qui veut toujours se mesurer à vous. Cela vous apprend à remplacer la compétition par la coopération, et à voir aussi votre propre goût de la victoire.`
],
'Sun-Jupiter':[
`Vous êtes naturellement optimiste et généreux, et vous croyez que les choses vont tourner du bon côté. Quand vous préparez un séjour à l’étranger, vous voyez souvent grand, et vous rencontrez vraiment des personnes providentielles ; attention à trop promettre et trop dépenser.`,
`Votre chance se manifeste souvent dès que vous prenez un peu d’initiative. Une question de plus, une formation de plus, et voilà une occasion inattendue ; l’apprentissage et les voyages vous ouvrent particulièrement des portes.`,
`Vous voyez souvent trop grand et en faites trop, par exemple en acceptant plusieurs projets à la fois jusqu’à être débordé. Apprenez à mesurer vos forces, et votre enthousiasme deviendra de vrais résultats.`,
`Vous donnez une impression de générosité et de confiance, et la chance vous vient souvent naturellement. Dans vos études ou votre travail, des aînés ou des professeurs sont souvent prêts à vous épauler, ce qui vous évite bien des détours.`,
`Vous êtes souvent tiraillé entre « votre propre chemin » et « les attentes des autres ». Votre famille voudrait vous voir prendre une certaine voie, alors que vous voulez aller plus loin ; trouver une direction acceptable pour tous, c’est là votre croissance.`
],
'Sun-Saturn':[
`Vous avez été raisonnable très jeune et vous avez pris des responsabilités très tôt. Vous avez peut-être été le premier enfant de la famille à travailler, habitué à régler vos problèmes seul ; attention à être trop dur avec vous-même au point d’oublier de profiter.`,
`Vos efforts sont facilement récompensés : il suffit de persévérer pour obtenir des résultats. En pratiquant une compétence un peu chaque jour, vous devenez quelques années plus tard un expert de votre domaine, et vous inspirez confiance.`,
`Vous avez souvent l’impression de « ne pas être à la hauteur », et vous avez très peur de vous tromper. Les examens et les entretiens vous rendent particulièrement nerveux, mais cette pression vous rend aussi plus solide que les autres, et vous gagnez en assurance avec la maturité.`,
`Votre discipline et votre endurance sont naturelles, vous tenez sans avoir à vous forcer. Vous savez planifier votre épargne mensuelle et accumuler petit à petit, ce qui vous rend apte aux projets qui demandent du temps.`,
`Vous sentez souvent le poids d’une autorité ou de règles extérieures, par exemple dans une relation tendue avec un supérieur ou vos parents. En apprenant à établir vos propres règles, vous passez de celui qu’on encadre à celui qui encadre.`
],
'Moon-Mercury':[
`Vos émotions et votre pensée sont liées, et vous savez dire ce que vous ressentez. Quand le moral est bas, écrire un journal ou parler à quelqu’un vous fait du bien ; attention à ce que l’humeur ne biaise pas votre jugement : quand l’émotion monte, ne tirez pas de conclusion trop vite.`,
`Vous savez mettre vos ressentis en mots, et il suffit d’exprimer les choses pour qu’on vous comprenne. Un message attentionné de votre part suffit souvent à débloquer une relation coincée depuis longtemps.`,
`Vous avez souvent l’impression que la tête et le cœur se disputent, que ce que vous pensez n’est pas ce que vous ressentez. Vous savez qu’il faudrait lâcher prise, mais le cœur n’y arrive pas ; cela vous rend très compréhensif envers les contradictions des autres et vous prédispose à l’écriture.`,
`Vous parlez avec douceur et clarté, et vous savez réconforter. Quand un ami est triste, vous trouvez toujours les mots justes pour qu’il se sente compris, ce qui vous prédispose à l’enseignement ou à l’accompagnement.`,
`Vous oscillez souvent entre raison et sensibilité : au moment de décider, vous voulez tantôt écouter les chiffres, tantôt l’intuition. En discuter avec une personne de confiance vous aide à voir ce que vous pensez vraiment.`
],
'Moon-Venus':[
`Vous êtes naturellement doux et chaleureux, et vous savez prendre soin des autres. Quand des amis viennent chez vous, vous préparez des petites douceurs et du thé chaud, et on s’y sent bien ; attention à vouloir tellement être aimé que vous vous oubliez.`,
`Votre douceur et votre sens du beau vous valent souvent une belle popularité. Un petit cadeau ou un geste attentionné de votre part reste longtemps dans la mémoire de votre entourage, et vous rend très apprécié dans un groupe.`,
`Vous êtes souvent tiraillé entre « vouloir être aimé » et « ce dont vous avez vraiment besoin ». Vous savez que l’autre ne vous convient pas, mais vous tardez à partir parce que vous tenez à sa tendresse ; cela vous apprend aussi à voir clairement votre propre valeur.`,
`Vos émotions et votre façon d’aimer sont en accord, ce qui met les gens à l’aise. Vos relations avec votre famille et votre partenaire sont généralement harmonieuses, avec peu de conflits violents, et votre foyer est souvent l’endroit où tout le monde a le plus envie de revenir.`,
`Vous oscillez souvent entre « prendre soin des autres » et « vous faire plaisir ». Vous voulez donner à votre famille et en même temps dépenser pour ce que vous aimez ; en trouvant l’équilibre entre les deux, vous serez plus heureux.`
],
'Moon-Mars':[
`Vos émotions montent vite et retombent vite, et vous êtes très direct. Quand on vous offense, vous réagissez sur-le-champ, puis c’est oublié ; le point à surveiller, c’est que vous parlez facilement trop durement à vos proches. Pensez à vous excuser ensuite.`,
`Vos émotions se transforment souvent en énergie d’action, et un peu d’initiative suffit à régler les problèmes. Quand le moral est bas, vous allez faire du sport ou ranger votre chambre, et vous retrouvez vite votre énergie.`,
`Vous avez souvent l’impression que vos émotions et vos actes se contredisent, et vous vous agacez facilement. Quand quelque chose ne va pas, vous ne pouvez vous empêcher de vous emporter contre vos proches ; trouvez d’abord un exutoire, comme la course à pied, et tout ira beaucoup mieux.`,
`Vos émotions et vos actes sont en accord, et vous donnez une impression de vitalité et d’audace. Face à une injustice, vous osez vous lever, et vous savez aussi vous protéger.`,
`Vous oscillez souvent entre « vous protéger » et « foncer ». Dans une dispute de couple, vous voulez tantôt vous cacher, tantôt aller jusqu’au bout ; apprenez à dire ce que vous ressentez vraiment, et les conflits diminueront.`
],
'Moon-Jupiter':[
`Vous êtes naturellement optimiste et généreux, et vos émotions s’amplifient facilement. Heureux, vous invitez tout le monde au restaurant ; triste, vous l’êtes longtemps. Attention aux achats ou aux excès alimentaires dictés par l’humeur.`,
`Votre optimisme vous aide souvent à traverser les creux, et un peu d’initiative suffit pour trouver du soutien. Quand le moral est bas, vous partez en voyage ou suivez un cours, et vous retrouvez vite de l’espoir.`,
`Vous êtes souvent tiraillé entre « vouloir plus » et « en avoir déjà assez ». Votre placard est plein, et pourtant vous ne pouvez pas vous empêcher d’acheter encore ; apprenez à distinguer vos vrais besoins, et vous serez plus comblé.`,
`Vous donnez une impression de chaleur et de générosité, et les gens sont souvent prêts à vous aider. Dans les moments difficiles, il y a toujours un ami ou un proche pour vous tendre la main, et vous vous sentez soutenu.`,
`Vous oscillez souvent entre « prendre soin de votre famille » et « poursuivre vos propres idéaux ». Vous voulez partir étudier à l’étranger sans pouvoir laisser les vôtres ; trouver une façon de tenir les deux, c’est là votre croissance.`
],
'Moon-Saturn':[
`Vos émotions sont souvent tenues en bride par la raison, et vous avez appris très tôt à être fort. Enfant, vous pleuriez peut-être rarement et vous aviez l’habitude de tout digérer seul ; attention à trop refouler, et pensez à confier à quelqu’un ce que vous avez sur le cœur.`,
`Vos émotions sont très stables, et un peu d’initiative suffit pour que vous deveniez un appui pour les autres. Quand un ami est en difficulté, vous l’aidez calmement à trouver une solution, et vous inspirez une grande confiance.`,
`Vous avez souvent l’impression que vos ressentis ne sont pas permis, et vous vous sentez facilement seul. Même fatigué, vous n’osez pas le dire, de peur de paraître faible ; apprenez à exprimer vos besoins, et vous découvrirez que des gens sont prêts à vous accompagner.`,
`Vos émotions et vos responsabilités sont en accord, et vous donnez une impression de maturité et de solidité. Vous savez prendre soin de votre famille et organiser parfaitement les petites et grandes affaires de la maison ; vous êtes le soutien sur lequel tout le monde se repose.`,
`Vous oscillez souvent entre « vouloir être pris en charge » et « devoir tout porter seul ». Vous avez envie d’être câliné, tout en pensant que vous ne devriez pas ; trouvez une personne sur qui vous appuyer en toute confiance, et vous serez beaucoup plus léger.`
],
'Mercury-Venus':[
`Vous parlez avec douceur et goût, et vous savez mettre les gens à l’aise. Vos messages et vos cartes paraissent toujours très attentionnés, ce qui vous prédispose aux métiers qui demandent communication et sens esthétique.`,
`Votre éloquence et votre goût vous donnent souvent un coup de pouce, et un peu d’initiative suffit pour que les occasions se présentent. Un compliment sincère de votre part rend souvent une négociation ou une collaboration beaucoup plus facile.`,
``,``,``
],
'Mercury-Mars':[
`Votre pensée et votre action sont liées, et vous parlez de façon directe et rapide. En réunion, vous prenez souvent la parole en premier, et vous allez droit au but ; attention à être trop cash, au point que les autres se sentent attaqués.`,
`Votre parole est très convaincante, et un peu d’initiative suffit pour transformer vos idées en actes. Vos propositions sont souvent retenues parce que vous les présentez avec clarté et force.`,
`Vous entrez souvent en conflit par les mots, et un désaccord peut vite tourner à la dispute. Quand vous voyez un avis contraire en ligne, vous ne pouvez vous empêcher d’écrire une longue réponse ; apprenez à vous calmer avant de répondre.`,
`Votre pensée et votre action sont en accord, et vous travaillez avec efficacité. Quand on vous confie une mission, vous voyez vite les étapes et passez aussitôt à l’action, ce qui donne une impression de vivacité et de compétence.`,
`Vous rencontrez souvent de redoutables contradicteurs, comme cette personne qui, en réunion, est toujours de l’avis opposé. Cela vous apprend à écouter, et rend vos arguments de plus en plus solides.`
],
'Mercury-Jupiter':[
`Votre pensée voit loin, et vous aimez parler des grandes vérités. En discutant, vous passez souvent d’un petit fait à la philosophie de la vie ; attention à voir trop grand et à négliger les détails.`,
`Votre capacité d’apprentissage et d’expression vous donne souvent un coup de pouce, et un peu d’initiative suffit pour que les occasions se présentent. Un cours de plus, et vous rencontrez un futur partenaire.`,
`Vous pensez souvent trop et parlez trop, par exemple en promettant plusieurs choses à la fois jusqu’à être débordé. Apprenez à vous concentrer sur une seule chose à la fois, et vos bonnes idées se réaliseront vraiment.`,
`Vous parlez avec optimisme et conviction, ce qui vous prédispose à l’enseignement et à l’écriture. Quand vous partagez votre expérience, ceux qui vous écoutent se sentent souvent pleins d’espoir et ont très envie d’essayer avec vous.`,
`Vous oscillez souvent entre « les détails » et « la vue d’ensemble » : en rédigeant un projet, vous êtes tantôt trop pointilleux, tantôt trop vague. Trouvez un partenaire complémentaire, et vos idées seront plus complètes.`
],
'Mercury-Saturn':[
`Votre pensée est rigoureuse et structurée. Avant d’écrire un rapport, vous vérifiez toujours vos sources, et vous vous trompez rarement ; attention au pessimisme qui vous fait imaginer le pire.`,
`Votre pensée est solide, et un peu d’initiative suffit pour que vous deveniez un vrai professionnel. En continuant à apprendre une compétence, vous devenez quelques années plus tard la personne que tout le monde consulte.`,
`Vous avez souvent peur de dire une bêtise, ou vous avez l’impression de ne pas être assez intelligent. En réunion, vous avez une idée mais vous n’osez pas la dire ; apprenez à vous faire confiance, votre avis a réellement de la valeur.`,
`Votre pensée est posée et bien structurée, ce qui vous prédispose aux travaux de concentration au long cours. Vous savez organiser clairement des données très complexes, de sorte qu’on comprend tout d’un coup d’œil.`,
`Vous êtes souvent tiraillé entre « vos propres idées » et « l’avis de l’autorité », par exemple en désaccord avec un professeur ou un supérieur. Apprenez à vous appuyer sur des preuves, et vous gagnerez le respect.`
],
'Venus-Mars':[
`Vous avez un charme naturel et beaucoup de passion en amour. Quand quelqu’un vous plaît, vous faites le premier pas et vous savez créer du romantisme ; attention, les sentiments viennent vite et l’impulsivité aussi.`,
`En amour comme en création, les bonnes occasions sont fréquentes, et un peu d’initiative suffit pour faire jaillir l’étincelle. En participant à un événement, vous pouvez rencontrer quelqu’un qui vous fait battre le cœur et qui s’intéresse aussi à vous.`,
`Vous êtes souvent tiraillé entre « vouloir être aimé » et « vouloir conquérir », et vos relations connaissent des hauts et des bas. Vous vous disputez souvent avec votre partenaire avant de vous réconcilier ; cette tension donne aussi beaucoup de chaleur à vos histoires.`,
`Votre amour et votre désir sont en accord, et vous dégagez un charme décontracté. En couple, vous savez exprimer vos sentiments et profiter de la vie à deux ; rendez-vous ou quotidien, tout est doux.`,
`Vous rencontrez souvent en amour des personnes « complémentaires » : si vous êtes doux, l’autre est autoritaire. Cela vous apprend à équilibrer donner et recevoir dans la relation, et à apprécier davantage ceux qui sont différents de vous.`
],
'Venus-Jupiter':[
`Vous êtes naturellement généreux et charmant, et vous savez profiter de la vie. Vous adorez inviter vos amis et faire des cadeaux ; attention à trop dépenser, ou à idéaliser l’amour.`,
`Votre popularité et votre chance vous donnent souvent un coup de pouce, et un peu d’initiative suffit pour que les occasions se présentent. Une soirée peut vous faire rencontrer une personne providentielle ou un bon partenaire ; les bonnes choses arrivent souvent en s’amusant.`,
`Vous voulez souvent plus, et vous achetez beaucoup sans être satisfait. Apprenez à distinguer vos vrais besoins, et vous découvrirez que le bonheur est simple : un bon repas et un bon ami suffisent.`,
`Vous donnez une impression de chaleur et de générosité, et vous êtes très apprécié. Au travail comme en amour, des gens sont souvent prêts à vous aider, et vous vous sentez béni ; vous aimez aussi partager cette chance.`,
`Vous oscillez souvent entre « votre propre plaisir » et « les attentes des autres » : vous voulez acheter ce qui vous plaît tout en craignant qu’on vous trouve dépensier. Trouvez vos propres valeurs, et vous serez plus à l’aise.`
],
'Venus-Saturn':[
`En amour, vous êtes sérieux et prudent, et vous ne vous engagez pas à la légère. Il vous faut parfois observer longtemps avant d’accepter une relation, mais une fois décidé vous êtes très fidèle ; attention à trop vous retenir.`,
`Vos sentiments sont très stables, et un peu d’initiative suffit pour construire une relation durable. Avec votre partenaire, vous planifiez l’avenir et réalisez pas à pas vos objectifs communs.`,
`Vous avez souvent l’impression de ne pas mériter d’être aimé, ou vous êtes très inquiet en amour. Si l’autre tarde à répondre à un message, vous vous demandez ce qui ne va pas chez vous ; apprenez à croire en votre valeur, et vous serez plus serein.`,
`Votre amour et votre sens des responsabilités sont en accord, et vous donnez une impression de fiabilité et de maturité. En couple, vous tenez vos engagements et vous savez faire vivre une relation dans la durée ; votre amour se bonifie avec le temps comme un bon vin.`,
`Vous oscillez souvent entre « vouloir aimer » et « avoir peur d’être blessé » : vous avez très envie de vous rapprocher sans oser le faire. Trouvez une personne qui vous donne un sentiment de sécurité, et vous pourrez vous ouvrir peu à peu.`
],
'Mars-Jupiter':[
`Vous avez naturellement de l’élan et le goût du risque, et vous agissez avec ambition. Vous pouvez vous inscrire à plusieurs compétitions d’un coup ; attention à un excès de confiance qui vous fait négliger les risques.`,
`Votre énergie d’action vous porte souvent chance, et un peu d’initiative suffit pour que les occasions se présentent. Un événement de plus, un CV de plus, et voilà une occasion inattendue : bouger, c’est votre porte-bonheur.`,
`Vous en faites souvent trop et allez trop vite, par exemple en acceptant plusieurs projets à la fois jusqu’à l’épuisement. Apprenez à mesurer vos forces et à fixer des priorités, et votre élan deviendra de vrais résultats.`,
`Vos actions ont un cap, et vous donnez une impression d’énergie et d’espoir. Quand vous menez une équipe, vous savez toujours lui donner de l’entrain pour avancer ensemble vers le but ; même fatigués, tout le monde arrive encore à rire.`,
`Vous êtes souvent tiraillé entre « votre propre élan » et « les règles des autres », par exemple quand votre responsable bloque ce que vous voulez faire. Apprenez d’abord à convaincre, et vos actions avanceront plus facilement.`
],
'Mars-Saturn':[
`Vos actions sont très disciplinées, mais vous vous sentez aussi souvent entravé. Vous êtes très endurant à l’effort et prêt à passer des années à maîtriser une compétence ; attention à une colère refoulée trop longtemps qui pourrait exploser d’un coup.`,
`Vos actions ont beaucoup d’endurance, et un peu d’initiative suffit pour accomplir des choses très difficiles. Après quelques années de musculation régulière, votre corps et votre volonté sont devenus si forts que vous vous impressionnez vous-même.`,
`Vous avez souvent l’impression que votre élan est bloqué, comme si ce que vous voulez faire rencontrait toujours des obstacles. Cette frustration vous oblige aussi à apprendre la patience ; avec la maturité, vous franchissez de plus en plus les difficultés, et réussir un peu plus tard, c’est quand même réussir.`,
`Vos actions et votre discipline sont en accord, et vous travaillez avec constance et efficacité. Vous savez découper un plan à long terme en étapes quotidiennes et le mener à bien petit à petit, ce qui vous prédispose aux tâches qui demandent de l’endurance.`,
`Vous oscillez souvent entre « foncer » et « vous protéger », par exemple quand vous voulez créer votre entreprise tout en craignant l’échec. Apprenez à bien vous préparer avant d’agir, et vous unirez élan et prudence en une vraie force.`
],
'Jupiter-Saturn':[
`Vous savez trouver l’équilibre entre idéal et réalité. Vous préparez d’abord une solution de repli, puis vous poursuivez votre rêve ; votre croissance est ainsi stable et solide, sans grands hauts et bas soudains.`,
`Vos idéaux et la réalité se soutiennent souvent, et un peu d’initiative suffit pour obtenir de bons résultats. Dans un emploi stable, vous trouvez la place de développer peu à peu vos passions.`,
`Vous êtes souvent tiraillé entre « vouloir vous développer » et « vouloir rester prudent », par exemple quand vous voulez investir en vous-même tout en craignant de trop dépenser. Cette tension vous apprend à porter des jugements plus mûrs.`,
`Vos idéaux et vos responsabilités sont en accord, et vous donnez une impression de vision et de fiabilité. Vous savez découper un grand rêve en un plan réalisable et l’accomplir pas à pas, si bien qu’on vous suit en toute confiance.`,
`Vous oscillez souvent entre « optimisme » et « pessimisme » : tantôt vous avez l’impression de pouvoir tout faire, tantôt que rien n’est possible. En trouvant le juste milieu, vous gagnerez en force.`
]
}
};
