/* Starlit : contenu narratif du thème astral (français) : Ascendant (première impression, manière d’agir) × Soleil (moi profond) */
globalThis.STORY_WEST_ASC_FR={
ascSun:[
/* Ascendant Bélier */
[
'Votre façade et votre nature sont un seul et même feu, avec un écart rare entre dedans et dehors : vous avez l’air pressé, et vous l’êtes vraiment ; vous avez l’air audacieux, et vous l’êtes jusqu’à l’os. Au restaurant, si les plats tardent, vous vous levez pour aller demander au comptoir, et ce que vous dites est exactement ce que vous pensez. On vous lit facilement, c’est votre franchise. Un conseil : comptez jusqu’à trois avant de parler, pour laisser aux autres le temps de suivre.',
'À la première rencontre, on vous trouve vif, impatient, comme si vous vouliez tout régler sur-le-champ ; ce qui compte vraiment pour vous, pourtant, c’est d’accumuler pas à pas et de mener une vie solide. Un collègue vous pique au vif, vous lancez « je m’en charge », puis vous avancez lentement, en soignant chaque étape. La réaction est rapide, la détermination est lente. À essayer : annoncez d’emblée le temps qu’il vous faut, pour qu’on ne croie pas que vous démarrez fort et finissez mou.',
'Aux yeux d’un inconnu, vous débordez d’élan et passez à l’acte dès que l’idée vous vient ; au fond, vous avez surtout envie de tout goûter et de discuter du monde entier. Les deux côtés vont vite, et ensemble ils font un accélérateur. Une amie mentionne une nouvelle expo, vous réservez les billets sur place et repérez en chemin trois cafés dans le quartier. Vous vous ennuyez rarement, mais vous vous dispersez facilement. Une phrase pour vous : chaque trimestre, choisissez une chose à mener jusqu’au bout, pour que votre curiosité laisse des traces.',
'Vous entrez en scène avec un élan franc, la parole directe et le geste rapide, et l’on vous croit dur ; en réalité, votre cœur est tendre, et ce qui vous préoccupe le plus, ce sont votre famille et vos proches. Dehors, vous défendez un ami face à un commerçant avec fermeté ; de retour chez vous, une seule phrase de votre mère, « on ne te voit plus beaucoup », vous laisse coupable toute la soirée. Cette armure sert à protéger les autres. Un conseil : devant les personnes de confiance, vous pouvez la poser.',
'Dès que vous arrivez, il y a de la chaleur : vous êtes direct et vous avez de la prestance ; au fond, vous voulez créer une œuvre bien à vous et être vu. Deux feux brûlent dans la même direction, et vous êtes fait pour vous tenir devant. Quand votre association organise un événement, vous levez la main pour animer, puis vous remaniez tout le déroulé à votre façon. L’angle mort : quand vous êtes pressé de briller, vous n’écoutez plus les autres. À essayer : laissez un peu de scène à vos coéquipiers, les applaudissements n’en seront que plus forts.',
'Au premier regard, on vous trouve franc, réactif, un peu fonceur ; mais la vraie direction de votre vie, c’est de bien faire les choses et de les rendre utiles. Les deux tirent souvent en sens inverse : la bouche dit oui d’abord, puis la tête se met aussitôt à chercher les failles. Votre responsable vous pose une question, vous répondez « aucun problème », puis de retour à votre bureau vous dressez une liste de vingt points à vérifier et veillez tard pour tout boucler. Un conseil : avant d’accepter, ajoutez « je vérifie les détails et je reviens vers vous ».',
'L’Ascendant Bélier et le Soleil Balance se font face : vous donnez une impression directe et franche, mais au fond vous tenez beaucoup à l’harmonie et à l’équité. Quand on prépare un voyage, vous êtes le premier à trancher « on part en Bretagne », puis vous craignez aussitôt d’avoir froissé quelqu’un et ajoutez vite « qu’est-ce que vous en pensez ? ». Vous savez prendre l’initiative comme accorder les points de vue. Une phrase pour vous : donner votre avis d’abord n’a rien d’égoïste, il suffit ensuite de bien écouter les autres.',
'Vous avez l’air de quelqu’un qui fonce, qui dit ce qu’il pense et qui part au combat ; en vérité, vous êtes très secret, vous voulez aller au fond des choses et garder la vue d’ensemble. On croit vous avoir compris, on n’a vu que la surface. En réunion, vous lancez une objection comme en passant, et l’on découvre plus tard que vous aviez déjà épluché la proposition de l’autre. À essayer : laissez vos proches voir vos calculs, la confiance n’en sera que plus solide.',
'La première impression et la nature profonde portent toutes deux le feu : vous avez l’air prêt à foncer, et vous voulez aller plus loin. La différence : l’extérieur est pressé pour le moment présent, l’intérieur cherche le sens et la liberté. L’entreprise cherche quelqu’un pour ouvrir un marché à l’étranger, vous levez la main sur-le-champ et le soir même vous commencez à lire l’histoire et la langue du pays. Votre enthousiasme entraîne les autres, mais vous promettez souvent trop. Un conseil : avant de dire oui, faites le compte du temps et du budget.',
'À la première rencontre, on voit votre impatience et votre élan ; au fond, vous êtes très patient et tenez à la réussite durable et aux responsabilités. Ensemble, cela donne un départ rapide suivi d’une course tenue jusqu’au bout. Vous êtes le premier à prendre un nouveau projet, puis vous établissez un calendrier limpide sur trois ans. Les autres ne voient souvent que votre impulsivité. Une phrase pour vous : parlez de vos plans à long terme, pour qu’on voie aussi votre constance.',
'Vous donnez l’image de quelqu’un d’indépendant, de direct, prêt à tirer le premier ; au fond, vous voulez faire quelque chose d’original et d’utile au groupe. Ni l’un ni l’autre n’aime être encadré, alors vous avancez souvent en avance sur les règles. L’entreprise débat encore de l’adoption d’un nouveau logiciel, vous l’avez déjà testé une semaine et posté votre bilan dans le groupe. À essayer : quand vous êtes devant, retournez-vous pour voir si quelqu’un suit.',
'Vous arrivez net et décidé, comme si rien ne vous faisait peur ; à l’intérieur, vous êtes sensible, plein d’imagination et facilement touché par les émotions des autres. Ce contraste fait souvent croire que vous êtes dur. Une amie vit une rupture, vous lui dites « arrête de pleurer, viens, on va manger un morceau », puis vous rentrez chez vous si triste pour elle que vous n’arrivez pas à dormir. Un conseil : inutile de toujours couvrir votre tendresse par l’action, dire ce que vous ressentez est aussi une forme de courage.'
],
/* Ascendant Taureau */
[
'À la première rencontre, on vous trouve doux, posé, facile à vivre ; en vérité, vous êtes pressé d’entreprendre et de faire vos preuves. Dehors, une pente douce ; dedans, un moteur. En réunion, vous hochez la tête en silence, attendez que tout le monde ait fini de se disputer, puis une seule phrase de vous fixe la direction, et le lendemain vous passez à l’action. À essayer : ne retenez pas votre élan trop longtemps, laissez les autres savoir plus tôt que vous avez une idée.',
'Votre façade et votre cœur sont tous deux Taureau : ce que l’on voit, c’est ce que vous êtes, stable, posé, fiable, et doué pour profiter de la vie. Cette cohérence rassure, et vous avez rarement besoin de jouer un rôle. Vos amis savent qu’avec vous, pas besoin de chercher un restaurant : ce sera ce petit bistrot où vous allez depuis cinq ans sans jamais être déçu. L’angle mort : quand le changement arrive, rien en vous ne veut bouger. Un conseil : prévoyez-vous de petites aventures, pour que la vie ne se rétrécisse pas.',
'Au premier abord, vous paraissez calme, sans hâte, du genre à ne pas changer d’avis ; au fond, vous adorez apprendre et discuter, et votre tête ne s’arrête jamais. Au dîner entre amis, vous parlez peu et finissez tranquillement votre assiette, puis une fois rentré vous envoyez dix liens et discutez jusqu’à minuit. Plus on vous connaît, plus vous êtes intéressant. Une phrase pour vous : montrez votre curiosité plus tôt, inutile d’attendre d’être en confiance pour parler.',
'Vous paraissez doux et posé, on se détend dès qu’on vous voit ; au fond, la famille et les sentiments passent avant tout, et vous savez prendre soin des autres. Les deux s’accordent bien, comme une vieille maison où le poêle brûle en hiver. Quand un ami déménage, vous ne portez pas seulement les cartons : vous arrivez discrètement avec une marmite de soupe et une petite plante. Vous êtes souvent le refuge de tout le monde ; l’angle mort, c’est de vous sacrifier par égard pour les autres. À essayer : inscrivez aussi vos propres besoins dans l’agenda.',
'Aux yeux d’un inconnu, vous êtes discret, posé, peu enclin à vous mettre en avant ; mais votre cœur veut être vu et avoir sa propre scène. Dehors, le calme ; dedans, un projecteur qui attend d’être allumé. Vous avez soigné chaque coin de votre intérieur, vous dites « oh, j’ai fait ça vite fait », alors que vous espérez que vos amis remarquent chaque détail. Un conseil : dites franchement le soin que vous y avez mis, donnez aux autres l’occasion de vous complimenter.',
'La première impression est solide, fiable, sans précipitation ; ce qui compte pour vous, c’est l’utile et le travail bien fini, vous voulez toujours améliorer encore un peu. Deux énergies de terre superposées : vous êtes un faiseur né. Un collègue vous refile un dossier en désordre, vous le remettez en ordre sans un mot et y joignez une page de mode d’emploi. Vous vous trompez rarement, mais on considère souvent votre travail comme allant de soi. Une phrase pour vous : faites voir ce que vous avez accompli, et demandez la reconnaissance qui va avec.',
'Vous donnez une impression de douceur, de goût et de manières agréables ; au fond, vous tenez à l’équité et à la beauté dans les relations. Ascendant et Soleil sont tous deux gouvernés par Vénus : vous savez mettre les gens à l’aise. Quand des amis sont en froid, vous les invitez dans un restaurant à l’ambiance chaleureuse et, entre deux plats, vous aidez chacun à vider son sac. L’angle mort : vous ravalez souvent votre propre mécontentement. À essayer : rester aimable ne veut pas dire se taire, dites de temps en temps ce que vous voulez vraiment.',
'L’Ascendant Taureau et le Soleil Scorpion se font face : dehors, vous êtes doux, lent à vous ouvrir, arrangeant ; dedans, intense, profond, entier dans l’amour comme dans la rancune. On vous croit facile à convaincre, et l’on ne découvre votre fermeté qu’en touchant vos limites. Un partenaire repousse sans cesse un paiement, vous lui dites poliment « ce n’est pas grave », alors que vous avez déjà rassemblé tous vos échanges. Un conseil : énoncer vos limites tôt coûte bien moins d’énergie que de tenir les comptes en silence.',
'On vous trouve stable, lent, attaché à ce que vous connaissez ; au fond, vous rêvez de lointain et voulez voir un monde plus vaste. Ce contraste vous fait souvent hésiter entre sécurité et liberté. Vous rêvez de partir en Amérique du Sud sac au dos, vous préparez ce voyage depuis trois ans, et vous préférez encore stabiliser votre crédit immobilier d’abord. Une phrase pour vous : inutile de tout quitter d’un coup, offrez-vous d’abord un petit voyage de trois jours pour laisser respirer l’explorateur en vous.',
'Votre apparence et votre nature sont toutes deux concrètes : vous avez l’air posé, et vous voulez construire vos résultats pas à pas. Dès la première rencontre, on vous trouve fiable, et vous n’abandonnez pas facilement. Le jour de votre premier salaire, vous ouvrez un compte réservé à l’achat d’un logement, et dix ans plus tard vous recevez vraiment les clés. L’angle mort : trop de sérieux, trop peu de jeu. À essayer : sur le chemin de vos objectifs, gardez du temps pour vous amuser, sans rien produire.',
'Au premier abord, vous êtes doux, respectueux des règles, voire un peu conservateur ; pourtant votre tête est pleine d’idées neuves, souvent à contre-courant. Au repas de famille, vous mangez en silence, puis quand les aînés abordent un sujet de société, une phrase de vous laisse toute la table interloquée. Votre allure rassure, vos opinions surprennent. Un conseil : avancez vos idées nouvelles pas à pas, avec des exemples concrets, elles passeront mieux.',
'Vous donnez une impression de douceur, de stabilité et de proximité ; à l’intérieur, vous êtes délicat et plein d’empathie, facilement touché par la musique, les histoires et ce que vivent les autres. Vous êtes comme un canapé dans lequel on s’enfonce. Quand un ami vient pleurer chez vous, vous ne vous pressez pas de donner des conseils : vous lui tendez un thé chaud et restez avec lui tard dans la nuit. Une phrase pour vous : vous absorbez beaucoup d’émotions, pensez à faire le vide régulièrement.'
],
/* Ascendant Gémeaux */
[
'Votre première impression : vif, bavard, réactif ; au fond, un élan qui veut être le premier et ouvrir la voie. Ensemble, cela vous permet de discuter tout en fonçant. En réunion de projet, vous détendez l’atmosphère avec quelques blagues, puis la seconde d’après vous posez votre proposition sur la table en ajoutant « je m’en occupe ». Un conseil : au-delà de la parole rapide, gardez un moment de réflexion avant de dire oui.',
'À la première rencontre, on vous trouve vif et bavard, capable de rebondir sur n’importe quel sujet ; en vérité, vous tenez à la stabilité et au concret, et vous ne changez pas facilement d’avis. Un ami vous propose d’investir dans une nouveauté à la mode, vous en parlez avec entrain pendant une heure, puis vous concluez « je vais attendre de voir ». La parole est souple, l’avis est arrêté. À essayer : faites savoir que discuter avec enthousiasme ne veut pas dire accepter, cela vous évitera bien des malentendus.',
'Ascendant et Soleil en Gémeaux : une cohérence rare entre dehors et dedans. Vous avez l’air curieux et bavard, et vous voulez vraiment tout savoir. On se met vite sur votre longueur d’onde. À l’arrêt de bus, vous discutez avec un inconnu de son métier, puis une fois chez vous vous vous renseignez sur ce secteur. Vous apprenez vite, et vos centres d’intérêt changent vite aussi. Une phrase pour vous : gardez une œuvre au long cours, pour prouver que vous n’êtes pas qu’un coup de vent.',
'Vous avez l’air léger, drôle, facile à aborder ; au fond, vous êtes très sentimental, et ce qui vous importe le plus, c’est que vos proches se sentent en sécurité. Beaucoup croient que rien ne vous touche, alors que vous vous souvenez des difficultés de chacun. Dans le groupe de discussion, vous lancez les blagues pour mettre de l’ambiance, et en privé vous écrivez à l’ami qui se fait silencieux depuis quelque temps. Un conseil : laissez voir de temps en temps que vous tenez aux gens, sans tout envelopper dans l’humour.',
'La première impression : intelligent, drôle, abordable ; votre cœur, lui, désire être vu et avoir sa propre scène. L’éloquence est l’outil, briller est le but. À une soirée, vous racontez une anecdote en passant, et bientôt toute la table vous écoute en silence, ce que vous savourez en secret. À essayer : mettez votre talent de parole au service d’une œuvre qui vous tient vraiment à cœur, pas seulement pour divertir.',
'À la première rencontre, on vous trouve agile, l’esprit vif ; au fond, vous visez la précision et l’utilité, et vous aimez tirer les choses au clair. Ascendant et Soleil sont tous deux gouvernés par Mercure : vous êtes un analyste né. Un ami vous demande quel aspirateur choisir, vous en parlez cinq minutes, et le lendemain vous lui envoyez un tableau comparatif. Un conseil : quand votre tête ne s’arrête plus, l’anxiété guette, accordez-vous des moments sans aucune information.',
'Vous donnez une impression légère, amicale, et vous savez faire la conversation ; au fond, vous tenez aux relations, à l’équité et à la beauté. Deux énergies d’air vous rendent très apprécié. Au pot d’accueil d’un nouveau collègue, vous mettez vite tout le monde à l’aise, et vous remarquez qui reste à l’écart pour orienter la conversation vers lui. L’angle mort : dire des choses que vous ne pensez pas pour préserver l’ambiance. Une phrase pour vous : sur les sujets importants, commencez par dire votre position.',
'Vous avez l’air bavard, comme si vous étiez prêt à tout partager ; en vérité, vous êtes profond et très attaché à votre intimité, avec beaucoup de choses que vous ne dites pas. Les autres croient bien vous connaître, ils n’ont parlé qu’en surface. À une soirée, vous racontez plein d’anecdotes, et en rentrant vous réalisez que vous n’avez pas dit une seule chose sincère. À essayer : trouvez une ou deux personnes de confiance et laissez-les voir vos profondeurs.',
'L’Ascendant Gémeaux et le Soleil Sagittaire se font face : vous donnez l’image de quelqu’un qui pose mille questions et déborde d’informations, mais au fond vous cherchez un sens plus large et des horizons lointains. Au déjeuner, vous pouvez commenter l’actualité avec vos collègues pendant tout le repas, mais ce que vous voulez vraiment, c’est partir étudier à l’étranger pour comprendre comment le monde fonctionne. Vous saisissez les détails comme la vue d’ensemble. Un conseil : ne laissez pas les informations éparses noyer votre cap.',
'À la première rencontre, on vous trouve jeune, vif, un brin espiègle ; au fond, vous êtes très pragmatique, avec des plans à long terme et le sens des responsabilités. Au bureau, on vous voit comme le boute-en-train, et chaque trimestre vous dépassez discrètement vos objectifs. Léger dehors, sérieux dedans : on vous sous-estime facilement. Une phrase pour vous : dans les moments décisifs, rangez les blagues et montrez votre poids.',
'Vous donnez l’image de quelqu’un d’intelligent, d’amical, de réactif ; au fond, vous portez des idées bien à vous et voulez faire autrement que les autres. Deux énergies d’air vous rendent doué pour brasser des idées. Un ami se plaint du stationnement dans le quartier, et au fil de la discussion vous créez un groupe en ligne et rédigez une proposition d’amélioration. À essayer : quand les idées abondent, choisissez-en une et menez-la à bien, c’est là que le changement se voit.',
'Vous avez l’air bavard, vif, facile à vivre ; à l’intérieur, vous êtes sensible et délicat, souvent plongé dans votre imaginaire. On vous croit très rationnel, alors que la plupart de vos décisions se prennent au ressenti. En discussion, vos arguments sont impeccables, puis vous changez d’avis parce qu’une image vous a touché. Un conseil : acceptez d’être quelqu’un qui ressent avec le cœur, inutile de justifier chaque choix.'
],
/* Ascendant Cancer */
[
'La première impression est douce, chaleureuse, un peu timide même ; au fond brûle un feu qui veut entreprendre et gagner, et seuls vos proches savent à quel point vous êtes combatif. Dans un nouvel environnement, vous observez en silence quelques jours, et une fois rassuré, vous proposez soudain un plan audacieux qui surprend tout le monde. Un conseil : douceur et courage ne s’opposent pas, laissez voir plus tôt votre ambition.',
'À la première rencontre, on vous trouve chaleureux, accessible, attentionné ; votre cœur tient à la stabilité et à la qualité de vie. Ensemble, cela sent bon la maison. Quand des amis passent, vous sortez vos conserves maison et un thé tout juste infusé, et personne ne veut plus partir. Vous inspirez un fort sentiment de sécurité. À essayer : ne mettez pas toute votre énergie à veiller sur la maison et les autres, mettez aussi de côté pour vos propres rêves.',
'Vous paraissez doux et attentif, vous avez l’habitude d’observer avant d’approcher ; au fond, vous êtes plein de curiosité, vous voulez apprendre et discuter partout. En arrivant dans une association, vous parlez peu, puis une fois à l’aise, vous devenez celui qui trouve toujours un sujet et partage le plus de découvertes. Vos amis disent souvent : « Il faut te connaître pour savoir à quel point tu es drôle. » Une phrase pour vous : inutile de vous cacher autant au premier contact, votre côté amusant mérite d’être découvert plus tôt.',
'Ascendant et Soleil en Cancer : votre apparence et votre nature sont aussi chaleureuses et sentimentales l’une que l’autre, et ce que l’on ressent au premier regard, c’est le vrai vous. Quand un collègue tombe malade, vous êtes le premier à proposer de le remplacer et à lui apporter des médicaments au passage. Cette cohérence inspire vite la confiance, mais vos humeurs se lisent aussi sur votre visage. Un conseil : fixez-vous des limites, vous n’avez pas à prendre soin de tout le monde.',
'Vous donnez une impression douce, aimable, sans chercher à monopoliser la parole ; mais votre cœur veut être vu, exprimer sa créativité et être le héros de sa propre vie. Au repas de famille, vous préparez une table entière sans rien dire, en espérant secrètement que quelqu’un s’exclame : « C’est toi qui as fait ça ? Bravo ! » Dehors, vous prenez soin des autres ; dedans, vous voulez briller. À essayer : ne restez pas toujours en coulisses, placez-vous parfois sous la lumière.',
'À la première rencontre, on vous trouve prévenant et facile à vivre ; au fond, vous êtes pragmatique et minutieux, toujours à vouloir mettre de l’ordre. Au dîner entre amis, vous demandez à chacun s’il a assez mangé tout en notant discrètement qui a payé quoi, puis vous faites les comptes au centime près. Vous savez prendre soin comme gérer. Une phrase pour vous : ne soyez pas trop dur avec vous-même, acceptez un peu d’imperfection.',
'Vous paraissez doux et sensible, capable de comprendre ce que ressentent les autres ; au fond, vous recherchez l’harmonie et l’équité dans les relations. Les deux font de vous un excellent médiateur. Quand la famille se dispute, vous calmez d’abord le plus agité, puis vous trouvez le moment pour que chacun puisse s’expliquer. L’angle mort : vous faites souvent passer les besoins des autres avant les vôtres. Un conseil : dans une relation, votre inconfort mérite aussi d’être traité équitablement.',
'La première impression est tendre, aimable, un peu réservée ; à l’intérieur, vous êtes profond et ardent, entier dans l’amour comme dans la rancune. Deux énergies d’eau vous donnent une intuition très juste. Un nouvel ami vous parle, vous l’écoutez en souriant, et vous avez déjà senti quelle phrase sonnait faux. Votre façon de vous protéger, c’est d’observer d’abord. À essayer : baissez la garde devant ceux qui le méritent, laissez-les voir la profondeur de vos sentiments.',
'Vous donnez une impression chaleureuse, nostalgique, très attachée au foyer ; au fond, vous rêvez de liberté, d’aventure au loin et de sens à donner à votre vie. Ce contraste vous tiraille souvent. Vous êtes heureux dans votre travail loin de chez vous, mais à chaque fête de famille vous culpabilisez, de peur que les vôtres croient que vous ne voulez pas revenir. Une phrase pour vous : emportez la maison avec vous, vous pouvez avoir des racines et des ailes.',
'L’Ascendant Cancer et le Soleil Capricorne se font face : vous paraissez doux et accessible, mais vous êtes très ambitieux et tenez à la réussite et aux responsabilités. Au premier abord, on vous croit arrangeant ; en travaillant avec vous, on découvre des objectifs très clairs. Vous prenez des nouvelles de chacun dans l’équipe avec le sourire, mais à l’échéance vous ne lâchez pas un seul jour. Un conseil : faites savoir que votre douceur et votre exigence sont toutes deux sincères, on ne vous prendra pas pour quelqu’un à double visage.',
'À la première rencontre, on vous trouve doux, avec un parfum de foyer ; au fond, vous êtes très indépendant, attaché à vos idées et à votre liberté, et vous n’aimez pas être lié par les sentiments. Vous prenez très bien soin de vos amis, mais dès qu’on exige que vous répondiez aux messages à la seconde, vous avez envie de fuir. L’intimité et l’indépendance coexistent en vous. À essayer : dès le début d’une relation, dites clairement de combien d’espace vous avez besoin.',
'Votre première impression est douce et chaleureuse, on a envie de s’approcher ; au fond, vous débordez d’empathie et d’imagination, et vous ressentez facilement ce que vivent les autres. Deux énergies d’eau en accord : vous êtes une oreille attentive née. Dans le métro, vous voyez quelqu’un pleurer en silence, vous hésitez à lui tendre un mouchoir, et une fois descendu vous pensez encore à cette personne. Une phrase pour vous : la sensibilité est un cadeau, mais pensez à construire une digue pour vous protéger.'
],
/* Ascendant Lion */
[
'Dès que vous entrez, on vous remarque : généreux, chaleureux, sûr de vous ; au fond, un élan qui veut entreprendre et relever des défis. Deux feux font de vous un meneur né. À la soirée de fin d’année de l’entreprise, vous ne faites pas que monter sur scène : vous inventez sur le moment un nouveau jeu et entraînez tout le monde. Vous savez enflammer l’ambiance, et aussi voler la lumière aux autres. Un conseil : laissez de la place aux autres, votre éclat n’en sera pas diminué.',
'À la première rencontre, on vous trouve charismatique, généreux, soucieux de votre image ; au fond, vous êtes terre à terre et tenez à la stabilité et à la vraie valeur des choses. Vous sortez toujours bien habillé, mais en faisant vos achats vous comparez les prix avec soin pour choisir le modèle le plus durable. Dehors, de l’éclat ; dedans, du fond. À essayer : ne vous prouvez pas seulement par l’apparence, ce que vous avez de plus précieux, c’est votre fiabilité.',
'La première impression : confiant, chaleureux, à l’aise sur scène ; au fond, curieux, avide d’apprendre et d’échanger. Vous animez votre club de lecture avec une belle prestance, mais ce qui vous rend vraiment heureux, c’est la fin de séance où chacun lance ses idées et où naissent des pistes nouvelles. Vous donnez envie qu’on vous écoute. Une phrase pour vous : ne cherchez pas seulement l’attention, creusez un ou deux sujets, vous gagnerez en poids.',
'Vous paraissez généreux, rayonnant, plein d’assurance ; à l’intérieur, vous êtes tendre, et ce qui compte le plus, ce sont votre famille et vos proches. On vous croit sans peur, alors que vous avez grand besoin d’appartenance. Sur scène, vous parlez avec aisance, et en descendant votre premier geste est d’appeler les vôtres pour savoir s’ils ont vu la retransmission. Un conseil : faites savoir à vos proches que votre assurance a aussi besoin de leurs bras.',
'Ascendant et Soleil en Lion : dehors et dedans rayonnent pareil, et vous voulez vraiment briller et créer. On voit tout de suite qui vous êtes, et vous n’avez jamais eu l’intention de le cacher. Pour votre anniversaire, vous organisez toute la fête vous-même, des invitations à la musique, tout porte votre style. Votre charisme est contagieux. À essayer : votre chaleur touche plus que votre éclat, pensez à éclairer aussi ceux qui vous entourent.',
'À la première rencontre, on vous trouve imposant, serein, sûr de vous ; mais votre cœur est prudent, toujours à vérifier les détails et à chercher la perfection. Votre présentation paraît détendue, alors que la veille vous avez ajusté trois fois la taille de police de chaque diapositive. Dehors, aucun effort apparent ; dedans, un soin minutieux. Une phrase pour vous : racontez comment vous vous êtes préparé, on vous en admirera davantage.',
'Vous donnez une impression lumineuse, généreuse, pleine de charme ; au fond, vous tenez aux relations, à la beauté et à l’équité. En soirée, vous êtes très apprécié, mais ce qui compte le plus pour vous, c’est que tout le monde s’amuse et que personne ne reste dans son coin. Vous savez briller et soigner l’ambiance. Un conseil : ne sacrifiez pas votre position pour plaire à tous, votre avis compte aussi.',
'La première impression : celle d’un hôte, chaleureux, expansif, plein de prestance ; au fond, vous êtes profond et perspicace, difficile à percer. À une fête, vous riez et bavardez, tout en lisant clairement les liens et les motivations de chacun. On vous trouve très abordable, mais votre confiance se gagne difficilement. À essayer : devant les personnes sûres, lâchez le contrôle, vous vous sentirez bien plus léger.',
'Vous donnez une impression enthousiaste, généreuse, pleine d’énergie ; au fond, vous rêvez de liberté et voulez explorer sans cesse de nouveaux lieux et de nouvelles idées. Deux feux vous rendent très communicatif. Un ami évoque vaguement l’envie de camper, et vous avez déjà tracé l’itinéraire et rassemblé dix personnes. Votre optimisme entraîne les autres. Une phrase pour vous : au-delà de l’enthousiasme, surveillez détails et budget, pour qu’une bonne idée ne devienne pas un fardeau.',
'À la première rencontre, on vous trouve sûr de vous, avec une allure de chef ; votre cœur est rigoureux, patient, tourné vers la réussite durable. En réunion, vous avez de la prestance, et après le travail vous restez seul à reprendre ligne par ligne le plan du trimestre suivant jusqu’à ce qu’il vous satisfasse. Votre éclat repose sur une vraie compétence. Un conseil : inutile de tout porter sur vos épaules, faire confiance à l’équipe est aussi une forme de leadership.',
'L’Ascendant Lion et le Soleil Verseau se font face : vous paraissez chaleureux, confiant, vous aimez qu’on vous remarque, mais au fond vous tenez à l’indépendance et à vos idéaux, et les normes sociales vous importent peu. Sur scène, vous attirez tous les regards, mais ce que vous voulez vraiment faire avancer, c’est un projet solidaire qui implique le plus de monde possible. Dehors, la scène ; dedans, le sens. À essayer : mettez la scène au service de vos idéaux, et les deux cesseront de se tirailler.',
'Votre première impression est lumineuse, chaleureuse, assurée ; à l’intérieur, vous êtes sensible et romantique, facilement influencé par les émotions et l’ambiance. Sur scène, vous êtes solide, mais il suffit qu’une personne dans le public fronce les sourcils pour que vous y repensiez longtemps. Dehors, vous tenez bon ; dedans, tout est délicat. Une phrase pour vous : la réaction des autres ne fait pas votre valeur, prenez les applaudissements comme les critiques avec plus de légèreté.'
],
/* Ascendant Vierge */
[
'La première impression est prudente, polie, méthodique ; au fond, vous êtes pressé d’entreprendre et de faire vos preuves. En arrivant dans une nouvelle équipe, vous travaillez d’abord en silence pour maîtriser les procédures, puis une fois à l’aise, vous proposez soudain une réforme et passez aussitôt à l’acte. Votre changement surprend souvent. Un conseil : ne laissez pas la préparation excessive bloquer l’action, votre élan mérite d’entrer en jeu plus tôt.',
'À la première rencontre, on vous trouve soigné, attentif, organisé ; au fond, vous tenez à la stabilité et aux résultats concrets. Deux énergies de terre vous rendent très efficace. Vous ne notez pas seulement le montant de vos dépenses, vous les classez par catégorie, et en dix ans votre épargne grandit sûrement. Vous rassurez. À essayer : en dehors de la sécurité, faites-vous plaisir de temps en temps, la vie aura plus de saveur.',
'Vous paraissez calme, prudent, observateur ; au fond, vous débordez de curiosité et voulez apprendre beaucoup et échanger avec beaucoup de gens. Ascendant et Soleil sont tous deux gouvernés par Mercure : votre tête est toujours occupée. Au club de lecture, vous parlez peu, mais vos notes sont les plus détaillées, et une fois chez vous vous discutez en ligne jusque tard dans la nuit. Une phrase pour vous : inutile d’attendre d’être parfaitement prêt pour parler, vos idées ont de la valeur.',
'À la première rencontre, on vous trouve courtois et efficace ; votre cœur, lui, est très sentimental, et ce qui compte le plus, ce sont votre famille et les gens que vous connaissez bien. Au bureau, vos tableaux sont irréprochables, et après le travail vous rentrez vite préparer la gamelle du lendemain pour les vôtres. Vous exprimez votre amour par les détails. Un conseil : avant de prendre soin des autres, reposez-vous bien, inutile d’avoir vingt sur vingt partout.',
'Vous donnez une impression discrète, prudente, sans goût pour la vedette ; au fond, vous désirez être vu et avoir votre propre œuvre, votre propre scène. Vous peaufinez le projet de l’équipe sans bruit, en espérant secrètement que votre responsable vous cite à la réunion mensuelle. Dehors, vous reculez ; dedans, vous voulez être devant. À essayer : n’attendez pas seulement qu’on vous découvre, montrez vous-même vos résultats, vous méritez d’être reconnu.',
'Ascendant et Soleil en Vierge : ce que l’on voit, c’est le vrai vous, attentif, concret, soucieux de bien faire. On vous confie vite les détails. Dans le dossier qu’un collègue doit rendre, vous repérez du premier coup d’œil trois coquilles et un chiffre mal calculé. Cette cohérence vous rend très fiable, mais aussi sévère envers vous-même. Une phrase pour vous : autorisez-vous parfois à ne faire que du quatre-vingts pour cent, c’est déjà très bien.',
'À la première rencontre, on vous trouve mesuré, discret, poli ; au fond, vous tenez à l’harmonie et à la beauté dans les relations. Au mariage d’un ami, vous êtes chargé de l’accueil et vous établissez un plan de table où chacun est à l’aise, en ayant tenu compte de qui ne s’entend pas avec qui. Votre minutie vous vaut la paix. Un conseil : ne ravalez pas tous vos avis par peur du conflit, exprimez vos besoins avec mesure.',
'Vous paraissez discret, mesuré, soigneux ; au fond, vous êtes profond et intense, vous voulez percer la nature des choses. Au travail, vous êtes un exécutant tranquille, mais quand quelqu’un tente de cacher un problème, vous posez sans un mot toutes les données sur la table. C’est alors que l’on découvre à quel point vous voyez loin. À essayer : mise au service des autres plutôt que de votre défense, votre perspicacité a bien plus de force.',
'À la première rencontre, on vous trouve réglo, attaché aux détails ; votre cœur aspire à la liberté, à l’aventure et au sens de la vie. Avant de partir à l’étranger, vous planifiez tout à la minute près, et une fois sur place vous changez souvent de programme pour filer vers un petit village qui n’était pas prévu. Une phrase pour vous : faites de votre plan un filet de sécurité, pas une cage, vous en profiterez bien mieux.',
'La première impression : attentif, fiable, méthodique ; au fond, des objectifs à long terme et un sens aigu des responsabilités. Deux énergies de terre vous rendent extrêmement compétent. On vous confie un service en désordre, en trois mois vous remettez les procédures d’aplomb, et six mois plus tard les résultats s’améliorent nettement. L’angle mort : vous vous accordez rarement une pause. Un conseil : inscrivez aussi le repos à votre agenda, il fait partie de la réussite à long terme.',
'À la première rencontre, on vous trouve respectueux des règles, prudent, voire un peu conservateur ; au fond, vos idées sont neuves et vous aimez sortir des cadres. Au travail, vous suivez les procédures et ne rendez jamais rien en retard, mais les propositions que vous rédigez de votre côté font souvent dire à votre responsable : « C’est audacieux. » Dehors, pas à pas ; dedans, hors des sentiers battus. À essayer : votre minutie est justement ce qui permet à l’innovation de prendre pied, n’ayez pas peur de paraître trop original.',
'L’Ascendant Vierge et le Soleil Poissons se font face : vous paraissez rationnel et organisé, mais au fond vous êtes sensible, plein d’imagination, souvent mené par vos émotions. Le jour, votre liste de tâches est impeccablement ordonnée ; le soir, une vieille chanson vous rappelle le passé et les larmes viennent. Les deux semblent se contredire, en réalité ils se complètent. Une phrase pour vous : laissez votre minutie construire l’échafaudage de vos rêves, les deux pourront travailler ensemble sans se renier.'
],
/* Ascendant Balance */
[
'L’Ascendant Balance et le Soleil Bélier se font face : votre première impression est élégante, diplomate, arrangeante ; au fond, vous voulez foncer, gagner et décider vous-même. En discussion, vous commencez par dire en souriant « tout me va », puis, quand chacun a parlé, c’est votre proposition qui a le plus de caractère. Un conseil : inutile de toujours envelopper votre ambition dans l’amabilité, soyez plus direct, on vous fera davantage confiance.',
'À la première rencontre, on vous trouve courtois, plein de goût, facile à vivre ; au fond, vous tenez à la stabilité et aux plaisirs bien réels. Ascendant et Soleil sont tous deux gouvernés par Vénus : vous savez ce qui fait la beauté de la vie. Votre studio n’est pas grand, mais chaque recoin est si agréable que vos amis ne veulent plus repartir. À essayer : ne supportez pas trop longtemps ce qui vous déplaît pour préserver la paix, dites-le simplement avec douceur.',
'Vous donnez une impression aimable, élégante, et vous savez faire la conversation ; au fond, vous êtes curieux, vous aimez échanger et les idées neuves. Deux énergies d’air vous rendent extrêmement apprécié. Dans une soirée de réseautage, vous échangez quelques mots à chaque table et, au passage, vous mettez en contact deux inconnus. Vous savez relier les gens. Une phrase pour vous : en plus de connaître beaucoup de monde, prenez le temps de lier quelques amitiés profondes.',
'La première impression : doux, élégant, attentif à l’ambiance ; votre cœur, lui, est très sentimental, et ce qui compte le plus, c’est le foyer et vos proches. Au travail, vous accueillez tout le monde avec le sourire, et chez vous une remarque anodine d’un proche peut vous peiner longtemps. Sous votre amabilité bat un cœur sensible. Un conseil : faites savoir à vos proches que vous aussi avez besoin qu’on prenne soin de vous, inutile de jouer toujours le gentil de service.',
'Vous donnez une impression élégante, généreuse, pleine de charme ; au fond, vous désirez être vu et créer une œuvre bien à vous. Vos amis vous demandent souvent conseil pour s’habiller, et vous finissez par lancer votre propre compte consacré au style, où vous progressez de plus en plus. Votre sens esthétique et votre envie de vous exprimer vont de pair. À essayer : faites hardiment de votre goût une scène, inutile de rester le conseiller des autres.',
'À la première rencontre, on vous trouve aimable, arrangeant ; au fond, vous êtes minutieux et exigeant, toujours à vouloir faire mieux. Au restaurant, vous dites en souriant « c’est délicieux », puis une fois rentré, vous dressez mentalement la liste de trois choses que l’établissement pourrait améliorer. Dehors, tout en rondeur ; dedans, pointilleux. Une phrase pour vous : réservez votre minutie à ce qui compte vraiment, inutile d’exiger la perfection en tout.',
'Ascendant et Soleil en Balance : votre apparence comme votre nature tiennent à l’harmonie, à la beauté et à l’équité, et la première impression est votre vrai visage. Quand des amis se disputent, vous vous placez naturellement entre eux, et chacun se sent compris. On aime être avec vous, mais vous sacrifiez souvent votre avis pour préserver la paix. Un conseil : pour décider, demandez-vous d’abord ce que vous voulez, puis pensez aux autres.',
'Vous paraissez doux, courtois, facile à vivre ; au fond, vous êtes profond et intense, entier dans l’amour comme dans la rancune, et il vous est difficile de vraiment vous ouvrir. À une fête, vous discutez agréablement avec chacun, mais seules une ou deux personnes connaissent vos vraies pensées. Dehors, une fenêtre ouverte ; dedans, une porte verrouillée. À essayer : trouvez quelqu’un de confiance et laissez-le voir qui vous êtes en entier.',
'À la première rencontre, on vous trouve élégant, facile, à l’aise en société ; votre cœur aspire à la liberté et à un monde plus vaste. Au travail, vous êtes très apprécié, mais chaque année vous bloquez de longues vacances pour partir seul, sac au dos, dans un pays inconnu. Les deux peuvent se nourrir. Une phrase pour vous : votre aisance sociale vous fera de bons amis en voyage, et ce que vous y verrez vous donnera encore plus de choses à raconter.',
'La première impression : doux, courtois, facile à aborder ; au fond, une forte ambition et un sens des responsabilités. À la table des négociations, vous gardez le sourire du début à la fin, sans céder un pouce sur les conditions, et vous signez le contrat le plus avantageux pour votre entreprise. Vos adversaires vous sous-estiment souvent. Un conseil : faites savoir que votre douceur ne veut pas dire que vous cédez facilement, votre fermeté a des principes.',
'À la première rencontre, on vous trouve aimable, facile à vivre ; au fond, vous êtes indépendant, avant-gardiste, et vous placez vos idées avant les liens personnels. Deux énergies d’air vous rendent très doué pour débattre. En soirée, vous discutez agréablement avec chacun, mais face à des valeurs que vous ne partagez pas, vous exprimez votre désaccord avec douceur et fermeté. À essayer : la cordialité et l’indépendance peuvent coexister, inutile de renoncer à vos idées pour garder la paix.',
'Vous donnez une impression élégante, douce, accessible ; à l’intérieur, vous êtes sensible et plein d’imagination, facilement ému par ce qui est beau. Au musée, vous pouvez rester vingt minutes devant un tableau, et une fois rentré vous écrivez une page entière sur ce que vous avez ressenti. Votre goût extérieur et votre sensibilité intérieure se renforcent l’un l’autre. Une phrase pour vous : essayez d’exprimer ces émotions par la création, inutile de les garder pour vous.'
],
/* Ascendant Scorpion */
[
'La première impression : mystérieux, distant, le regard profond ; au fond, vous êtes direct et impulsif, vous voulez entreprendre et gagner. En réunion, vous restez silencieux, impossible à deviner, puis au bon moment vous intervenez, et une phrase suffit à renverser la situation. Ascendant et Soleil sont tous deux liés à Mars : votre volonté est très forte. Un conseil : inutile de toujours cacher votre élan, laissez voir vos idées avec mesure, cela évitera bien des malentendus.',
'L’Ascendant Scorpion et le Soleil Taureau se font face : vous paraissez mystérieux, intense, difficile d’accès, mais au fond vous aspirez à une vie stable et simple. On vous croit compliqué, et une fois qu’on vous connaît, on découvre que votre plus grand bonheur, c’est un week-end à la maison à faire mijoter une soupe et revoir un vieux film. À essayer : faites savoir que vous êtes en fait facile à vivre, vous avez seulement besoin de temps pour faire confiance.',
'À la première rencontre, on vous trouve profond, sur la défensive, peu abordable ; au fond, vous êtes curieux et bavard, vous voulez tout savoir. Dans un nouvel environnement, vous commencez par observer chacun, et une fois à l’aise, vous devenez celui qui a toujours les dernières nouvelles et les anecdotes les plus drôles. Ce contraste donne à vos amis l’impression que vous avez plusieurs facettes. Une phrase pour vous : inutile de vous cacher aussi profondément au début, votre côté amusant mérite d’être vu plus tôt.',
'La première impression est un peu froide, distante ; votre cœur est tendre, sentimental, et ce qui vous préoccupe le plus, ce sont votre famille et vos proches. Deux énergies d’eau vous donnent une intuition très forte. Vous êtes méfiant envers les inconnus, mais aux petits soins avec votre famille, au point de deviner les besoins qu’elle n’exprime pas. Un conseil : laissez aux autres l’occasion de s’approcher, votre chaleur mérite d’être connue de plus de monde.',
'Vous donnez une impression intense, mystérieuse, magnétique ; au fond, vous désirez être vu et être le héros de votre vie. En soirée, vous parlez peu, mais on ne peut s’empêcher de vous remarquer, et vous savourez ces regards en secret. Dehors, la retenue ; dedans, l’envie de briller. À essayer : inutile d’attirer par le mystère, montrez directement votre talent, vous serez plus à l’aise.',
'À la première rencontre, on vous trouve profond, perspicace, difficile à cerner ; au fond, vous êtes minutieux et concret, vous aimez bien faire les choses. Vous repérez du premier coup d’œil le piège dans un contrat, puis vous le détaillez point par point en y joignant des propositions de modification. Voir loin et travailler finement : il est difficile de vous tromper. Une phrase pour vous : adoucissez un peu le ton, on acceptera plus facilement votre analyse.',
'Vous paraissez mystérieux, intense, sur la défensive ; au fond, vous tenez à l’harmonie, à la beauté et à l’équité dans les relations. Face aux inconnus, vous êtes froid, mais entre amis proches, c’est vous qui apaisez les conflits et soignez l’ambiance. La première impression et le vrai vous sont très différents. Un conseil : laissez paraître votre douceur plus tôt, pour que la première impression ne fasse pas fuir de futurs bons amis.',
'Ascendant et Soleil en Scorpion : votre apparence et votre nature sont aussi profondes et intenses l’une que l’autre. Vous ne prenez pas position facilement, mais une fois engagé, c’est corps et âme, et la première impression est votre vrai visage. Quand vous décidez d’apprendre quelque chose, vous creusez au point d’en savoir plus que le professeur. On vous trouve difficile d’accès, et vous n’avez pas l’intention de plaire à tout le monde. À essayer : baissez parfois la garde, laissez ceux en qui vous avez confiance partager votre fardeau.',
'On vous trouve d’abord prudent, profond, distant ; votre cœur est joyeux, aventurier, assoiffé de liberté et de sens. La première fois, vous parlez peu, et ce n’est qu’en vous connaissant qu’on découvre votre passion pour les voyages et l’éclat de vos yeux quand vous racontez vos périples. Dehors, une porte fermée ; dedans, une prairie. Une phrase pour vous : laissez paraître votre enthousiasme plus tôt, on vous connaîtra plus vite.',
'La première impression : intense, posé, imposant ; au fond, des objectifs à long terme et un grand sens des responsabilités. Au travail, vous parlez peu, mais tout le monde sait que ce qu’on vous confie sera bien fait, et vous préparez déjà le coup suivant. Vous êtes un stratège silencieux. Un conseil : ne portez pas toute la pression seul, laissez à temps des personnes de confiance la partager.',
'À la première rencontre, on vous trouve mystérieux, sur la défensive ; au fond, vous êtes indépendant, amical, attaché à vos idéaux et au collectif. Vous êtes distant avec les inconnus, mais dans votre association bénévole, vous êtes le plus engagé et le premier à prendre la parole pour les autres. Cette distance de premier abord n’est qu’une couche de protection. À essayer : laissez voir les idéaux qui vous tiennent à cœur, on comprendra d’où vient votre froideur.',
'Votre première impression est profonde, mystérieuse, un peu insaisissable ; à l’intérieur, vous êtes doux et sensible, facilement touché par les émotions des autres. Deux énergies d’eau vous donnent une intuition très juste. Un ami n’a encore rien dit que vous sentez déjà que quelque chose ne va pas, et vous restez à ses côtés toute la soirée sans un mot. Une phrase pour vous : vous absorbez beaucoup d’émotions, gardez des moments de solitude pour faire le ménage en vous.'
],
/* Ascendant Sagittaire */
[
'Votre première impression est joyeuse, enthousiaste, franche ; au fond, un élan qui veut entreprendre et arriver le premier. Deux feux vous donnent une énergie débordante. Un ami propose d’apprendre la plongée ensemble, vous ne faites pas qu’accepter : vous rassemblez cinq personnes et réservez les cours sur-le-champ. Difficile de ne pas se laisser entraîner. Un conseil : au-delà de l’enthousiasme, surveillez les détails, à trop promettre on finit par tout négliger.',
'À la première rencontre, on vous trouve décontracté, optimiste, aventurier ; au fond, vous tenez à la stabilité et au concret. En voyage, vous avez l’air d’improviser, alors que l’hébergement et le budget sont réglés depuis longtemps. Dehors, la liberté ; dedans, des fondations. Avec vous, on s’amuse et on se sent en sécurité. À essayer : laissez voir votre côté posé, on vous confiera plus volontiers les choses importantes.',
'L’Ascendant Sagittaire et le Soleil Gémeaux se font face : vous donnez l’image de quelqu’un qui aime les grandes idées et voit loin, mais au fond vous aimez collectionner toutes sortes de petites informations et échanger avec tout le monde. En soirée, vous parlez philosophie de la vie, et une fois rentré vous enchaînez séries et actualités jusqu’à minuit. Vous aimez la grande vue comme les petits détails. Une phrase pour vous : essayez de transformer ces informations en points de vue personnels, vous serez plus convaincant.',
'Vous donnez une impression joyeuse, généreuse, éprise de liberté ; au fond, vous êtes sentimental, et ce qui compte le plus, c’est votre famille et le sentiment d’appartenance. Vous partez souvent, voyagez partout, mais dans chaque ville vous achetez des souvenirs en vous demandant si les vôtres les aimeront. Dehors, vous volez ; dedans, vous pensez à la maison. Un conseil : faites savoir aux vôtres que vos départs ne sont pas une fuite, mais une façon de leur faire voir le monde avec vous.',
'À la première rencontre, on vous trouve enthousiaste, drôle, plein de vie ; votre cœur désire être vu et créer une œuvre bien à vous. Deux feux vous donnent beaucoup de charme. Quand vous montrez vos photos de voyage, vous avez toujours une histoire captivante à raconter, et vos amis sont suspendus à vos lèvres. À essayer : vos histoires touchent les gens, essayez de les écrire ou d’en faire une œuvre.',
'Vous paraissez décontracté, optimiste, peu regardant sur les détails ; au fond, vous êtes minutieux et pragmatique, toujours à vérifier que rien n’a été oublié. Vous dites « peu importe », et avant de sortir vous avez discrètement vérifié deux fois votre liste de bagages. On vous croit très spontané, alors que vous planifiez beaucoup. Une phrase pour vous : autorisez-vous une vraie détente, une fois, sans avoir tout préparé.',
'La première impression : joyeux, amical, facile à vivre ; au fond, vous tenez à l’harmonie, à la beauté et à l’équité dans les relations. Dans un voyage de groupe, vous sympathisez avec des inconnus et apaisez souvent les petites tensions entre participants, pour que tout le monde s’amuse. Partout où vous allez, vous vous faites des amis. Un conseil : vous savez soigner l’ambiance, n’oubliez pas de dire vos vrais besoins dans vos relations.',
'Vous donnez une impression joyeuse, franche, abordable ; au fond, vous êtes profond et intense, avec beaucoup de choses que vous ne dites pas facilement. En soirée, c’est vous qui riez le plus fort, mais vos vraies pensées, vous ne les confiez que tard dans la nuit à la personne en qui vous avez le plus confiance. Dehors, le beau temps ; dedans, l’océan profond. À essayer : trouvez des personnes de confiance et laissez-les voir vos profondeurs, vous vous sentirez bien plus léger.',
'Ascendant et Soleil en Sagittaire : votre apparence et votre nature sont aussi joyeuses l’une que l’autre, tournées vers le lointain et soucieuses de donner un sens à la vie, et la première impression est votre vrai visage. Vous annoncez que vous allez faire le tour de France à vélo, et le lendemain vous partez vraiment, en vous faisant toute une bande de nouveaux amis en chemin. Votre optimisme est contagieux, mais vous dites souvent oui trop vite. Une phrase pour vous : réfléchissez avant d’accepter, votre liberté a besoin d’un peu de planification.',
'À la première rencontre, on vous trouve optimiste, décontracté, aventurier ; au fond, vous êtes rigoureux et pragmatique, avec des objectifs à long terme. Vous avez toujours l’air détendu, alors que vos cinq prochaines années de carrière sont déjà tracées, chaque étape prévue. La décontraction est en surface, le sérieux en profondeur. Un conseil : laissez voir votre sérieux, on fera davantage confiance à votre jugement.',
'Vous donnez une impression enthousiaste, joyeuse, ouverte d’esprit ; au fond, vous êtes indépendant et avant-gardiste, attaché à vos idées et au collectif. Les points de vue que vous partagez sur les réseaux sont contagieux, et vous savez rassembler des personnes qui partagent vos convictions pour agir ensemble. Votre chaleur extérieure ouvre la voie à vos idéaux intérieurs. À essayer : ménagez vos forces, ne brûlez pas jusqu’à l’épuisement.',
'À la première rencontre, on vous trouve joyeux, optimiste, aventurier ; votre cœur est sensible et romantique, facilement ému par les émotions et les beaux paysages. En voyage, devant la mer, vous devenez soudain silencieux et composez un poème dans votre tête. Sous l’apparence animée se cache un cœur tranquille. Une phrase pour vous : notez ces instants qui vous touchent, ils sont votre trésor.'
],
/* Ascendant Capricorne */
[
'Votre première impression est posée, sérieuse, fiable ; au fond, vous êtes pressé d’entreprendre et de faire vos preuves. En réunion, vous êtes mesuré, alors que vous pensez depuis longtemps à créer votre entreprise et attendez simplement le meilleur moment. Dehors, on freine ; dedans, on accélère. Un conseil : votre sérieux peut donner une direction à votre élan, n’attendez pas que tout soit parfait pour agir.',
'À la première rencontre, on vous trouve mûr, fiable, un peu réservé ; au fond, vous tenez à la stabilité et à la qualité de vie. Deux énergies de terre vous rendent très solide. Très jeune, vous avez commencé à épargner et à investir dans vos compétences, et dix ans plus tard vous vivez la vie que vous vouliez. À essayer : tout en travaillant dur, prenez le temps de profiter du présent, inutile d’attendre « plus tard ».',
'Vous paraissez mûr, sérieux, peu souriant ; au fond, vous êtes curieux et bavard, vous aimez les idées neuves. Au travail, on vous voit comme l’aîné sérieux, et après le travail c’est vous qui partagez le plus de blagues absurdes et de découvertes dans le groupe de discussion. Ce contraste surprend agréablement ceux qui vous connaissent. Une phrase pour vous : laissez vos collègues voir votre côté détendu, ils oseront davantage s’approcher.',
'L’Ascendant Capricorne et le Soleil Cancer se font face : vous donnez l’image de quelqu’un de calme, compétent, distant ; au fond, vous êtes tendre et sentimental, et ce qui compte le plus, c’est votre famille. Au travail, vous êtes décidé et exigeant, mais il suffit d’un appel des vôtres pour que vous laissiez tout en plan et rentriez. Un conseil : laissez parfois vos collègues voir votre douceur, on vous fera encore plus confiance.',
'À la première rencontre, on vous trouve posé, discret, mesuré ; votre cœur désire être vu et bâtir une réussite bien à vous. Vous travaillez avec application, en espérant secrètement monter un jour sur scène sous les applaudissements. À essayer : ne comptez pas seulement sur l’effort pour être découvert, allez chercher la scène que vous méritez.',
'La première impression : mûr, prudent, fiable ; au fond, minutieux et concret, toujours à vouloir faire au mieux. Deux énergies de terre vous rendent très compétent. Vos rapports ne contiennent jamais d’erreur, même la ponctuation a été vérifiée. Votre responsable est serein, mais vous êtes souvent trop sévère envers vous-même. Une phrase pour vous : autorisez-vous parfois à vous tromper, cela n’enlève rien à votre fiabilité.',
'À la première rencontre, on vous trouve sérieux, mesuré, pas très abordable ; au fond, vous tenez à l’harmonie et à la beauté, et vous voulez vous entendre avec tout le monde. En réunion, vous êtes très professionnel, et en aparté vous remarquez qui est mis de côté et prenez discrètement sa défense. Sous la distance apparente, il y a de la délicatesse. Un conseil : laissez voir votre douceur, vous êtes plus apprécié que vous ne le pensez.',
'Vous paraissez posé, imposant, on vous respecte ; au fond, vous êtes profond et intense, vous voulez percer la nature des choses. Au travail, vous parlez peu, mais chaque fois que vous ouvrez la bouche, vous touchez le cœur du problème, et tout le monde est obligé de vous prendre au sérieux. Vous êtes de ceux qui ont du poids sans hausser la voix. À essayer : mise au service de la collaboration, votre perspicacité donnera plus de résultats qu’en solitaire.',
'À la première rencontre, on vous trouve mûr, posé, voire un peu conservateur ; au fond, vous aspirez à la liberté et à un monde plus vaste. Au travail, vous êtes appliqué, et dans votre tête vous prévoyez depuis longtemps d’aller un jour étudier ou vivre quelque temps à l’étranger. Une phrase pour vous : inscrivez ce rêve dans votre plan à long terme, votre sérieux est justement ce qui vous aidera à le réaliser.',
'Ascendant et Soleil en Capricorne : votre apparence et votre nature sont aussi mûres, concrètes et responsables l’une que l’autre, et la première impression est votre vrai visage. Dès l’école, vous saviez ce que vous vouliez et avanciez pas à pas vers votre but, sans presque jamais dévier. On vous fait très confiance, et on vous trouve aussi trop sérieux. Un conseil : détendez-vous de temps en temps et savourez les fruits de vos efforts.',
'La première impression : mûr, fiable, respectueux des règles ; au fond, vous êtes indépendant, avant-gardiste, vous voulez sortir des cadres. Au travail, vous suivez les règles, et le nouveau fonctionnement que vous poussez de votre côté améliore nettement l’efficacité de tout le service. C’est parce qu’on fait confiance à votre stabilité qu’on accepte vos nouveautés. À essayer : proposez hardiment vos idées, votre fiabilité est la meilleure des garanties.',
'À la première rencontre, on vous trouve calme, rationnel, distant ; au fond, vous êtes sensible et doux, plein d’imagination. Au travail, vous êtes décidé et efficace, et chez vous un film peut vous faire pleurer sans que vous puissiez vous arrêter. Dehors, un mur solide ; dedans, un jardin. Une phrase pour vous : laissez vos proches voir votre tendresse, vous n’avez pas besoin de toujours tenir bon.'
],
/* Ascendant Verseau */
[
'Votre première impression : amical, singulier, un peu insaisissable ; au fond, un élan qui veut entreprendre et gagner. En équipe, vous proposez toujours des idées hors du commun, et vous êtes le premier à les mettre à l’essai. Dehors, le calme ; dans l’action, le feu. Un conseil : votre créativité et votre sens de l’action sont forts, pensez à faire avancer l’équipe avec vous, sans foncer seul trop loin devant.',
'À la première rencontre, on vous trouve avant-gardiste, indépendant, imprévisible ; au fond, vous tenez à la stabilité et au concret. Votre style vestimentaire est très personnel, mais votre gestion de l’argent est très prudente, chaque euro est dépensé à bon escient. Dehors, l’originalité ; dedans, les pieds sur terre. À essayer : laissez votre stabilité servir de socle à votre créativité, les deux peuvent se soutenir.',
'Vous paraissez amical, intelligent, ouvert d’esprit ; au fond, vous êtes curieux et aimez échanger des idées neuves. Deux énergies d’air rendent votre esprit particulièrement agile. Vous discutez avec des gens de tous horizons et savez relier des savoirs de domaines différents pour inventer des combinaisons auxquelles personne n’avait pensé. Une phrase pour vous : quand les idées abondent, choisissez-en une et creusez-la, c’est ainsi que viennent les résultats.',
'À la première rencontre, on vous trouve indépendant, calme, un peu distant ; votre cœur est sentimental, et ce qui compte le plus, ce sont le foyer et vos proches. Dehors, vous êtes très rationnel ; de retour chez vous, c’est vous qui prenez le plus soin des vôtres, le plus nostalgique, incapable de jeter vos jouets d’enfance. Un conseil : laissez vos amis voir aussi votre chaleur, ils oseront davantage s’approcher.',
'L’Ascendant Verseau et le Soleil Lion se font face : vous donnez l’image de quelqu’un de singulier, calme, indifférent au regard des autres ; au fond, vous désirez être vu et reconnu. Vous dites que le nombre de « j’aime » vous est égal, alors qu’après chaque publication vous allez discrètement vérifier plusieurs fois. À essayer : admettez que vous voulez être vu, votre originalité n’en sera en rien diminuée.',
'La première impression : amical, indépendant, avant-gardiste ; au fond, vous êtes minutieux et pragmatique, toujours à vouloir faire au mieux. Vos propositions innovantes s’accompagnent toujours d’étapes de mise en œuvre et d’un calendrier détaillés, difficiles à contester. Idées neuves et bonne exécution : c’est votre force. Une phrase pour vous : votre minutie rend votre créativité plus crédible, ne craignez pas de paraître trop pointilleux.',
'À la première rencontre, on vous trouve amical, singulier, ouvert d’esprit ; au fond, vous tenez à l’harmonie et à l’équité dans les relations. Deux énergies d’air vous rendent très doué pour échanger. En réunion d’association, vous savez faire dialoguer sereinement ceux qui ne sont pas d’accord, et chacun se sent respecté. Un conseil : au-delà de prendre soin des autres, dites aussi votre propre position.',
'Votre première impression est calme, indépendante, un peu distante ; au fond, vous êtes profond et intense, entier dans l’amour comme dans la rancune. En soirée, vous avez l’air d’un spectateur, mais une fois que vous avez adopté un ami, vous vous donnez entièrement, jusqu’à prendre soin de sa famille. À essayer : faites savoir que sous votre calme se cachent des sentiments profonds, on vous chérira davantage.',
'À la première rencontre, on vous trouve amical, avant-gardiste, épris de liberté ; votre cœur aspire au lointain et cherche le sens de la vie. Les deux s’accordent bien. Vous partez souvent seul en voyage, et au retour vous écrivez vos observations sur les différentes cultures et les partagez avec vos amis jusque tard dans la nuit. Une phrase pour vous : votre expérience est précieuse, partagez-la plus largement, elle éclairera bien des gens.',
'Vous paraissez singulier, avant-gardiste, hors des normes ; au fond, vous êtes pragmatique et responsable, tourné vers la réussite durable. Vos idées surprennent souvent, mais vous savez aussi planifier pas à pas pour les transformer en résultats concrets. Ascendant et Soleil sont tous deux liés à Saturne : vous êtes plus endurant que vous n’en avez l’air. Un conseil : innovation et compétence permettent de grandes choses, ne vous sous-estimez pas.',
'Ascendant et Soleil en Verseau : votre apparence et votre nature sont aussi indépendantes, avant-gardistes et attachées aux idées l’une que l’autre, et la première impression est votre vrai visage. Vous ne suivez jamais la mode, vous tracez votre propre chemin, et vous entraînez souvent tout un groupe dans le changement. On vous trouve très cool, et un peu difficile d’accès. À essayer : laissez parfois les autres s’approcher, votre bienveillance mérite d’être vue.',
'À la première rencontre, on vous trouve calme, indépendant, un peu distant ; au fond, vous êtes sensible et doux, facilement ému. En groupe, vous paraissez très rationnel, mais face à quelqu’un qui a besoin d’aide, vous êtes le premier à tendre discrètement la main. Le calme est un manteau, la compassion est votre vraie nature. Une phrase pour vous : laissez voir votre empathie, votre influence n’en sera que plus grande.'
],
/* Ascendant Poissons */
[
'Votre première impression est douce, rêveuse, arrangeante ; au fond, un élan qui veut entreprendre et gagner. Vous avez l’air facile à convaincre, mais une fois que vous avez décidé de faire quelque chose, personne ne peut vous arrêter. Dehors, de l’eau ; dedans, du feu. Un conseil : faites connaître votre détermination plus tôt, on ne vous croira pas facile à influencer.',
'À la première rencontre, on vous trouve doux, romantique, un peu évanescent ; au fond, vous tenez à la stabilité et au concret. Vous avez l’air d’un artiste, mais vous gérez très bien votre argent, avec plus d’épargne que la plupart des gens de votre âge. La douceur extérieure et la solidité intérieure vont bien ensemble. À essayer : laissez voir votre stabilité, on osera davantage compter sur vous.',
'Vous paraissez doux, sensible, un peu mystérieux ; au fond, vous êtes curieux et aimez échanger des idées neuves. En soirée, vous écoutez en silence, et une fois rentré vous débattez avec ardeur en ligne, un message après l’autre. Dehors, le calme ; dans la tête, l’effervescence. Une phrase pour vous : laissez voir votre curiosité, vous vous ferez davantage d’amis qui vous ressemblent.',
'À la première rencontre, on vous trouve doux, accessible, plein d’empathie ; au fond, vous êtes sentimental, et ce qui compte le plus, ce sont le foyer et vos proches. Deux énergies d’eau vous rendent extrêmement attentionné. Le soir où un ami se fait quitter, vous êtes le premier en bas de chez lui, et vous vous souvenez de la pâtisserie qu’il préfère. Un conseil : au-delà de prendre soin des autres, pensez à prendre soin de vous.',
'Votre première impression est douce, rêveuse, artistique ; votre cœur désire être vu et créer une œuvre bien à vous. Vous dessinez ou écrivez souvent en silence, en espérant secrètement que quelqu’un apprécie votre travail. Dehors, la timidité ; dedans, l’envie de briller. À essayer : partagez hardiment vos créations, votre talent mérite d’être vu.',
'L’Ascendant Poissons et le Soleil Vierge se font face : vous paraissez doux, accommodant, un peu tête en l’air ; au fond, vous êtes minutieux et concret, toujours à vouloir bien faire. On vous croit très spontané, alors que vous avez déjà pensé à chaque détail, simplement sans le dire. Une phrase pour vous : laissez voir votre sens de l’organisation, on vous fera davantage confiance.',
'À la première rencontre, on vous trouve doux, élégant, facile à vivre ; au fond, vous tenez à l’harmonie, à la beauté et à l’équité. En groupe, vous faites en sorte que chacun se sente pris en charge, et tout le monde aime être avec vous. Dehors comme dedans, vous êtes doux, mais vous vous sacrifiez facilement. Un conseil : au-delà de prendre soin des autres, dites aussi vos propres besoins.',
'Votre première impression est douce, mystérieuse, empathique ; au fond, vous êtes profond et intense, entier dans l’amour comme dans la rancune. Deux énergies d’eau vous donnent une intuition très juste. Vous devinez d’un regard les soucis des autres, mais vous parlez rarement des vôtres. À essayer : trouvez des personnes de confiance et laissez-les voir vos profondeurs.',
'À la première rencontre, on vous trouve doux, rêveur, arrangeant ; votre cœur aspire à la liberté et au sens de la vie. Ascendant et Soleil sont tous deux liés à Jupiter : vous croyez naturellement en ce qui est beau. Vous avez l’air accommodant, et dans votre tête vous prévoyez depuis longtemps de partir loin, explorer d’autres cultures et d’autres croyances. Une phrase pour vous : passez du rêve à l’action, votre douceur rendra le voyage plus riche.',
'Vous paraissez doux, accommodant, un peu rêveur ; au fond, vous êtes pragmatique et responsable, tourné vers la réussite durable. On vous croit facile à convaincre, mais au travail vous êtes très professionnel, avec des objectifs clairs et jamais de retard. Un conseil : laissez voir votre compétence, on respectera davantage votre avis.',
'À la première rencontre, on vous trouve doux, sensible, accessible ; au fond, vous êtes indépendant et avant-gardiste, attaché à vos idées. Vous avez l’air arrangeant, mais quand vous voyez quelqu’un se faire harceler ou traiter injustement, vous vous interposez et tenez à vos principes. À essayer : faites savoir que votre douceur a des limites, on vous respectera davantage.',
'Ascendant et Soleil en Poissons : votre apparence et votre nature sont aussi douces, sensibles et imaginatives l’une que l’autre, et la première impression est votre vrai visage. La musique et les histoires vous émeuvent facilement, et vous ressentez si bien les émotions des autres que vous percevez souvent leur peine avant eux. On vous trouve très accessible, et vous êtes facilement submergé par les émotions. Une phrase pour vous : établissez des limites pour protéger votre sensibilité.'
]
]
};
